"""Production GEX UI wrapper with IV Rank overlay.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- production GEX overview overlays, including IV Rank / valuation reference;
- routing the stable GEX v3 renderer to the production GEX calculation adapter;
- GEX Refresh All scheduler concurrency when the E*TRADE request-rate gate remains authoritative.

DO NOT EDIT THIS FILE FOR:
- TradingView/Pine serialization details unless explicitly requested;
- E*TRADE/session plumbing or MARKET request throttling;
- Risk Sizing, OAuth, Holdings, navigation, or shared terminal infrastructure.

The previously deployed interaction/TradingView implementation is preserved
byte-for-byte as ``src.gex_ui_v3_proven``. This wrapper only adds IV Rank to the
overview, points its calculation dependency at ``src.gex_ui``, and can tune the
number of ticker workers without modifying the proven TradingView serializer.
"""

from __future__ import annotations

import html
import re
from typing import Any, Callable

from src import gex_ui as _core
from src import gex_ui_v3_proven as _proven


# ==============================
# PRODUCTION ROUTING / REFRESH CONCURRENCY
# ==============================
_proven._base.core = _core

# The workspace-level background client applies one shared ~3.7 MARKET
# request-starts/sec gate across quotes, expiration lists, and option chains.
# Four ticker workers can leave that gate idle whenever E*TRADE responses take
# several seconds, especially while each ticker is waiting for its expiration
# list before chain prefetch can begin. Twenty ticker workers match the existing
# twenty chain-fetch slots so Refresh All keeps the bounded MARKET pipeline full
# without increasing the request-start rate or changing any GEX calculation.
_BACKGROUND_TICKER_WORKERS = 20
_proven._BACKGROUND_MAX_WORKERS = _BACKGROUND_TICKER_WORKERS


# ==============================
# IV RANK OVERVIEW OVERLAY
# ==============================
def _inject_iv_rank_column(markup: str, vault_key: str) -> str:
    """Add one compact ``IV RANK / REF`` cell without touching Pine/A6 output."""
    if 'class="gexv3-summary"' not in markup or "<th>IV RANK / REF</th>" in markup:
        return markup

    markup = markup.replace(
        "<th>CALL WALL</th><th>RANGE</th>",
        "<th>CALL WALL</th><th>IV RANK / REF</th><th>RANGE</th>",
        1,
    )
    new_colgroup = (
        "<colgroup>"
        '<col style="width:11%"><col style="width:5%"><col style="width:9%">'
        '<col style="width:9%"><col style="width:9%"><col style="width:9%">'
        '<col style="width:13%"><col style="width:26%"><col style="width:9%">'
        "</colgroup>"
    )
    markup = re.sub(
        r"<colgroup>.*?</colgroup>",
        new_colgroup,
        markup,
        count=1,
        flags=re.DOTALL,
    )

    result_map = _core._results(str(vault_key or "default"))

    def add_cell(match: re.Match[str]) -> str:
        inner = match.group(1)
        ticker_match = re.search(r'gexv3-symbol-text">([^<]+)</span>', inner)
        if ticker_match is None:
            return match.group(0)
        ticker = html.unescape(ticker_match.group(1)).strip().upper()
        result = result_map.get(ticker)
        if not isinstance(result, dict):
            iv_cell = '<td class="orange">N/A | Refresh</td>'
            marker = '<td class="orange">REFRESH</td>'
            if marker in inner:
                inner = inner.replace(marker, iv_cell + marker, 1)
            return "<tr>" + inner + "</tr>"

        display = html.escape(str(result.get("ivRankDisplay") or "N/A | Building"))
        tone = str(result.get("ivRankTone") or "orange")
        if tone not in {"green", "red", "orange"}:
            tone = "orange"
        iv_cell = f'<td class="{tone}">{display}</td>'
        marker = '<td class="gexv3-range-col">'
        if marker in inner:
            inner = inner.replace(marker, iv_cell + marker, 1)
        return "<tr>" + inner + "</tr>"

    return re.sub(r"<tr>(.*?)</tr>", add_cell, markup, flags=re.DOTALL)


# ==============================
# PUBLIC RENDER WRAPPER
# ==============================
def render_gex(
    client: Any,
    vault_key: str,
    touch_session: Any,
    *,
    background_client_factory: Callable[[], Any] | None = None,
) -> None:
    """Render the proven GEX workspace with calculation parity + IV Rank."""
    vault_key = str(vault_key or "default")
    original_decorate = _proven._decorate_overview
    original_overview = _proven._base._overview_html
    original_remove = _proven._base._remove_ticker

    def overview_with_iv_rank(state: dict[str, Any], result_map: dict[str, Any]) -> str:
        saved_state = _core._apply_iv_rank_history(vault_key, state, result_map)
        if saved_state is not state:
            state.clear()
            state.update(saved_state)
        return original_overview(state, result_map)

    def remove_with_iv_rank(
        key: str,
        state: dict[str, Any],
        result_map: dict[str, Any],
        ticker: str,
    ) -> dict[str, Any]:
        normalized = _core._normalize_ticker(ticker)
        if normalized:
            state.setdefault("iv_history", {}).pop(normalized, None)
        return original_remove(key, state, result_map, ticker)

    def decorate_with_iv_rank(markup: str, key: str) -> str:
        decorated = original_decorate(markup, key)
        return _inject_iv_rank_column(decorated, key)

    _proven._base._overview_html = overview_with_iv_rank
    _proven._base._remove_ticker = remove_with_iv_rank
    _proven._decorate_overview = decorate_with_iv_rank
    try:
        _proven.render_gex(
            client,
            vault_key,
            touch_session,
            background_client_factory=background_client_factory,
        )
    finally:
        _proven._decorate_overview = original_decorate
        _proven._base._remove_ticker = original_remove
        _proven._base._overview_html = original_overview


background_refresh_status = _proven.background_refresh_status

__all__ = ["render_gex", "background_refresh_status"]
