"""CBOE delayed-options GEX source for Raj's Terminal.

OWNERSHIP / EDITING NOTES
EDIT THIS FILE FOR:
- CBOE delayed option-chain retrieval and normalization;
- CBOE-only GEX calculations and result caching;
- CBOE source diagnostics.

DO NOT EDIT THIS FILE FOR:
- E*TRADE GEX calculations or session plumbing;
- GEX tab layout / controls / TradingView presentation;
- Risk Sizing, OAuth, Holdings, navigation, or shared terminal infrastructure.

The CBOE calculation definitions intentionally mirror Raj's supplied Google Apps
Script (Code.gs) so the Streamlit CBOE Overview, the CBOE raw TXT bridge, and the
sheet all use the same wall / flip methodology.
"""

from __future__ import annotations

import copy
import json
import math
import re
import urllib.request
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

import numpy as np
import streamlit as st

from src import gex_ui as etrade_gex


# ==============================
# CBOE SOURCE / NORMALIZATION
# ==============================
INDEX_SYMBOLS = {"SPX", "XSP", "NDX", "RUT", "VIX", "DJX", "OEX"}
DEFAULT_IV = 0.30
REQUEST_TIMEOUT_SECONDS = 20
GAMMA_FLIP_STEPS = 1000
_GAMMA_FLIP_BATCH = 32


def _safe_float(value: Any, default: float | None = None) -> float | None:
    try:
        if value is None:
            return default
        if isinstance(value, (int, float)):
            number = float(value)
        else:
            text = str(value).strip().replace(",", "").replace("%", "")
            if not text or text.lower() in {"nan", "none", "null", "-"}:
                return default
            number = float(text)
        return number if math.isfinite(number) else default
    except (TypeError, ValueError):
        return default


def _normalize_symbol(symbol: Any) -> str:
    return re.sub(r"[^A-Z0-9]", "", str(symbol or "").upper().replace("^", ""))


def _url_candidates(symbol: str) -> list[str]:
    normalized = _normalize_symbol(symbol)
    normal = f"https://cdn.cboe.com/api/global/delayed_quotes/options/{normalized}.json"
    index = f"https://cdn.cboe.com/api/global/delayed_quotes/options/_{normalized}.json"
    return [index, normal] if normalized in INDEX_SYMBOLS else [normal, index]


def _fetch_cboe_chain(symbol: str) -> tuple[dict[str, Any], str]:
    headers = {
        "User-Agent": "Mozilla/5.0 (Raj-Terminal-GEX)",
        "Accept": "application/json,text/plain,*/*",
    }
    last_error: Exception | None = None
    for url in _url_candidates(symbol):
        try:
            request = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT_SECONDS) as response:
                payload = json.loads(response.read().decode("utf-8", errors="replace"))
            options = ((payload.get("data") or {}).get("options") or [])
            if isinstance(options, list) and options:
                return payload, url
        except Exception as exc:
            last_error = exc
    raise RuntimeError(
        f"Could not fetch CBOE delayed options for {symbol}. "
        f"Last error: {last_error}"
    )


def _extract_spot(payload: dict[str, Any]) -> float | None:
    data = payload.get("data") or {}
    possible = (
        "current_price",
        "last_price",
        "last",
        "price",
        "close",
        "underlying_price",
    )
    for key in possible:
        value = _safe_float(data.get(key))
        if value is not None and value > 0:
            return value
    for nested_key in ("quote", "underlying", "equity", "symbol"):
        nested = data.get(nested_key)
        if not isinstance(nested, dict):
            continue
        for key in possible:
            value = _safe_float(nested.get(key))
            if value is not None and value > 0:
                return value
    return None


def _parse_occ_symbol(option_symbol: Any):
    match = re.search(r"(\d{6})([CP])(\d{8})$", str(option_symbol or ""))
    if not match:
        return None
    expiry_text, cp, strike_raw = match.groups()
    expiry = datetime.strptime(expiry_text, "%y%m%d").date()
    return expiry, cp, int(strike_raw) / 1000.0


def _normalize_iv(raw_iv: Any) -> float:
    iv = _safe_float(raw_iv, DEFAULT_IV)
    if iv is None or iv <= 0:
        return DEFAULT_IV
    if iv > 5.0:
        iv /= 100.0
    return max(iv, 0.0001)


def _bs_gamma(spot: float, strike: float, iv: float, dte_days: int) -> float:
    if spot <= 0 or strike <= 0:
        return 0.0
    sigma = max(float(iv), 0.0001)
    t = max(float(dte_days) / 365.0, 0.5 / 365.0)
    sqrt_t = math.sqrt(t)
    d1 = (
        math.log(spot / strike)
        + (etrade_gex.RISK_FREE_RATE + 0.5 * sigma * sigma) * t
    ) / (sigma * sqrt_t)
    return math.exp(-0.5 * d1 * d1) / math.sqrt(2.0 * math.pi) / (
        spot * sigma * sqrt_t
    )


def _estimate_apps_script_gamma_flip(
    contracts: list[dict[str, Any]],
    spot: float,
) -> float | None:
    """Match the supplied Code.gs 1,000-step Black-Scholes gamma-flip scan.

    Code.gs recomputes gamma at each candidate underlying price using each
    contract's IV/OI/DTE, a 4.5% risk-free rate, a 0.5-day time floor, and the
    full strike-range scan.  When several sign crossings exist, it keeps the
    crossing nearest current spot.
    """
    if not contracts or spot <= 0:
        return None

    strikes = sorted(
        {
            float(contract["strike"])
            for contract in contracts
            if float(contract.get("strike", 0.0) or 0.0) > 0
        }
    )
    if not strikes:
        return None

    valid = [
        contract
        for contract in contracts
        if float(contract.get("strike", 0.0) or 0.0) > 0
        and float(contract.get("oi", 0.0) or 0.0) > 0
        and str(contract.get("cp") or "").upper() in {"C", "P"}
    ]
    if not valid:
        return None

    c_strikes = np.asarray([float(contract["strike"]) for contract in valid], dtype=float)[None, :]
    c_iv = np.maximum(
        np.asarray([float(contract["iv"]) for contract in valid], dtype=float),
        0.0001,
    )[None, :]
    c_t = np.maximum(
        np.asarray([float(contract["dte"]) for contract in valid], dtype=float) / 365.0,
        0.5 / 365.0,
    )[None, :]
    c_sqrt_t = np.sqrt(c_t)
    c_oi = np.asarray([float(contract["oi"]) for contract in valid], dtype=float)[None, :]
    c_sign = np.asarray(
        [1.0 if str(contract["cp"]).upper() == "C" else -1.0 for contract in valid],
        dtype=float,
    )[None, :]

    min_strike = strikes[0]
    max_strike = strikes[-1]
    scan_low = max(0.01, min(min_strike, float(spot) * 0.50))
    scan_high = max(max_strike, float(spot) * 1.50)
    scan = np.linspace(scan_low, scan_high, GAMMA_FLIP_STEPS + 1, dtype=float)
    totals = np.empty_like(scan)

    sigma_sqrt_t = c_iv * c_sqrt_t
    drift = (float(etrade_gex.RISK_FREE_RATE) + 0.5 * c_iv * c_iv) * c_t
    normalizer = math.sqrt(2.0 * math.pi)

    for start in range(0, len(scan), _GAMMA_FLIP_BATCH):
        stop = min(start + _GAMMA_FLIP_BATCH, len(scan))
        test_spots = scan[start:stop, None]
        d1 = (
            np.log(test_spots / c_strikes) + drift
        ) / sigma_sqrt_t
        gamma = (
            np.exp(-0.5 * d1 * d1)
            / normalizer
            / (test_spots * sigma_sqrt_t)
        )
        exposure = (
            gamma
            * c_oi
            * etrade_gex.CONTRACT_SIZE
            * test_spots
            * test_spots
            * 0.01
        )
        totals[start:stop] = np.sum(c_sign * exposure, axis=1)

    gamma_flip: float | None = None
    best_distance_to_spot: float | None = None
    prev_px = float(scan[0])
    prev_gex = float(totals[0])

    for index in range(1, len(scan)):
        px = float(scan[index])
        now_gex = float(totals[index])
        crossed = (
            (prev_gex < 0.0 and now_gex > 0.0)
            or (prev_gex > 0.0 and now_gex < 0.0)
            or now_gex == 0.0
        )
        if crossed and abs(now_gex - prev_gex) > 0.0:
            candidate = (
                prev_px
                - prev_gex * (px - prev_px) / (now_gex - prev_gex)
            )
            distance_to_spot = abs(candidate - float(spot))
            if (
                best_distance_to_spot is None
                or distance_to_spot < best_distance_to_spot
            ):
                gamma_flip = candidate
                best_distance_to_spot = distance_to_spot
        prev_px = px
        prev_gex = now_gex

    return gamma_flip


# ==============================
# CBOE GEX CALCULATION
# ==============================
def build_cboe_gex(
    symbol: str,
    max_dte: int,
    timezone_name: str,
    wall_value_mode: str,
) -> dict[str, Any]:
    """Build one CBOE result in the same structured shape as production E*TRADE."""
    symbol = etrade_gex._normalize_ticker(symbol)
    if not symbol:
        raise ValueError("Enter a ticker first.")

    payload, source_url = _fetch_cboe_chain(symbol)
    options = ((payload.get("data") or {}).get("options") or [])
    spot = _extract_spot(payload)
    if spot is None or spot <= 0:
        raise RuntimeError(f"CBOE did not return a usable underlying price for {symbol}.")

    tz = ZoneInfo(str(timezone_name or "America/New_York"))
    today = datetime.now(tz).date()
    max_dte = int(max_dte)
    contracts: list[dict[str, Any]] = []
    expiries_used: set[str] = set()

    for raw in options:
        if not isinstance(raw, dict):
            continue
        parsed = _parse_occ_symbol(
            raw.get("option") or raw.get("option_symbol") or raw.get("symbol")
        )
        if not parsed:
            continue
        expiry, cp, strike = parsed
        dte = (expiry - today).days
        if dte < 0 or dte > max_dte:
            continue

        oi = (
            _safe_float(raw.get("open_interest"))
            or _safe_float(raw.get("openInterest"))
            or _safe_float(raw.get("openinterest"))
            or _safe_float(raw.get("oi"))
            or 0.0
        )
        if oi <= 0:
            continue

        iv = _normalize_iv(
            raw.get("iv")
            or raw.get("implied_volatility")
            or raw.get("impliedVolatility")
        )
        gamma_feed = _safe_float(raw.get("gamma"))
        gamma_now = (
            float(gamma_feed)
            if gamma_feed is not None and gamma_feed > 0
            else _bs_gamma(float(spot), float(strike), iv, int(dte))
        )
        contracts.append(
            {
                "expiry": expiry,
                "cp": cp,
                "strike": float(strike),
                "dte": int(dte),
                "oi": float(oi),
                "iv": float(iv),
                "gamma_now": float(gamma_now),
            }
        )
        expiries_used.add(expiry.isoformat())

    if not contracts:
        raise RuntimeError(
            f"No usable CBOE option contracts for {symbol} inside <= {max_dte} DTE."
        )

    aggregate: dict[float, dict[str, float]] = {}
    for contract in contracts:
        strike = float(contract["strike"])
        row = aggregate.setdefault(
            strike,
            {
                "strike": strike,
                "call_oi": 0.0,
                "put_oi": 0.0,
                "call_gex": 0.0,
                "put_gex": 0.0,
                "net_gex": 0.0,
                "cum_gex": 0.0,
                "rank": 0,
            },
        )
        exposure = (
            float(contract["gamma_now"])
            * float(contract["oi"])
            * etrade_gex.CONTRACT_SIZE
            * float(spot)
            * float(spot)
            * 0.01
        )
        if contract["cp"] == "C":
            row["call_oi"] += float(contract["oi"])
            row["call_gex"] += exposure
            row["net_gex"] += exposure
        else:
            row["put_oi"] += float(contract["oi"])
            row["put_gex"] -= exposure
            row["net_gex"] -= exposure

    rows = sorted(aggregate.values(), key=lambda row: row["strike"])
    cumulative = 0.0
    for row in rows:
        cumulative += row["net_gex"]
        row["cum_gex"] = cumulative

    ranked = sorted(rows, key=lambda row: abs(row["net_gex"]), reverse=True)
    for rank, row in enumerate(ranked, 1):
        row["rank"] = rank

    max_call_oi = max(rows, key=lambda row: row["call_oi"])
    max_put_oi = max(rows, key=lambda row: row["put_oi"])

    # Code.gs parity: CALLWALL is the max-call-OI strike. PUTWALL is the
    # strike with the most negative combined/net GEX.  Do not substitute the
    # E*TRADE component-GEX wall selectors in this CBOE-only engine.
    call_wall_raw = max_call_oi
    put_wall_raw = min(rows, key=lambda row: row["net_gex"])

    gamma_flip = _estimate_apps_script_gamma_flip(contracts, float(spot))
    mode = str(wall_value_mode or "NET_GEX").upper()
    if mode == "COMPONENT_GEX":
        call_wall_value = call_wall_raw["call_gex"]
        put_wall_value = put_wall_raw["put_gex"]
    else:
        call_wall_value = call_wall_raw["net_gex"]
        put_wall_value = put_wall_raw["net_gex"]

    call_wall = {"strike": call_wall_raw["strike"], "value": call_wall_value}
    put_wall = {"strike": put_wall_raw["strike"], "value": put_wall_value}
    top_gex = ranked[: etrade_gex.TOP_N]
    net_current = sum(row["net_gex"] for row in rows)

    fmt = etrade_gex._legacy._fmt_num
    packed_rows = [f"SPOT,{fmt(spot)},0"]
    if gamma_flip:
        packed_rows.append(f"GFLIP,{fmt(gamma_flip)},0")
    packed_rows.extend(
        [
            f"CALLWALL,{fmt(call_wall['strike'])},{fmt(call_wall['value'], 2)}",
            f"PUTWALL,{fmt(put_wall['strike'])},{fmt(put_wall['value'], 2)}",
            f"MAXCALLOI,{fmt(max_call_oi['strike'])},{fmt(max_call_oi['call_oi'], 0)}",
            f"MAXPUTOI,{fmt(max_put_oi['strike'])},{fmt(max_put_oi['put_oi'], 0)}",
        ]
    )
    for index, values in enumerate(top_gex, 1):
        tag = "GEXPOS" if values["net_gex"] >= 0 else "GEXNEG"
        packed_rows.append(
            f"{tag}{index},{fmt(values['strike'])},{fmt(values['net_gex'], 2)}"
        )
    packed = "\n".join(packed_rows)

    updated = datetime.now(tz)
    summary_text = (
        f"Ticker: {symbol}\n"
        f"Mode: BARCHART_STYLE\n"
        f"Spot: {fmt(spot)}\n"
        f"Max DTE Used: {max_dte}\n"
        f"Contracts Used: {len(contracts)}\n"
        f"Net Current GEX: {net_current:,.2f}\n"
        f"Source URL: {source_url}\n\n"
        "PASTE EVERYTHING BELOW INTO PINE INPUT: Packed Gamma Levels\n"
        "------------------------------------------------------------\n"
        f"{packed}\n"
    )

    return {
        "symbol": symbol,
        "mode": "BARCHART_STYLE",
        "spot": float(spot),
        "maxDte": max_dte,
        "contractsUsed": len(contracts),
        "netCurrent": net_current,
        "sourceUrl": source_url,
        "gammaFlip": gamma_flip,
        "callWall": call_wall,
        "putWall": put_wall,
        "maxCallOi": max_call_oi,
        "maxPutOi": max_put_oi,
        "topGex": top_gex,
        "packed": packed,
        "summaryText": summary_text,
        "rawRows": rows,
        "updated": updated.isoformat(),
        "expiriesUsed": sorted(expiries_used),
        "chainErrors": [],
    }


# ==============================
# CBOE RESULT VAULT
# ==============================
@st.cache_resource
def _cboe_vault() -> dict[str, dict[str, Any]]:
    return {}


def cboe_snapshot(vault_key: str) -> dict[str, Any]:
    key = str(vault_key or "default")
    snapshot = _cboe_vault().setdefault(
        key,
        {"results": {}, "failures": {}, "updated": ""},
    )
    return snapshot


def cboe_results(vault_key: str) -> dict[str, Any]:
    return cboe_snapshot(vault_key)["results"]


def save_cboe_refresh(
    vault_key: str,
    results: dict[str, Any],
    failures: dict[str, str],
    timezone_name: str,
) -> dict[str, Any]:
    snapshot = cboe_snapshot(vault_key)
    snapshot["results"].update(copy.deepcopy(results))
    snapshot["failures"] = copy.deepcopy(failures)
    try:
        tz = ZoneInfo(str(timezone_name or "America/New_York"))
    except Exception:
        tz = ZoneInfo("America/New_York")
    snapshot["updated"] = datetime.now(tz).isoformat()
    return snapshot
