"""GEX-only realized-volatility support for Raj's Terminal.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- GEX IV-vs-historical-volatility data retrieval;
- 30-day close-to-close realized/historical volatility calculations;
- GEX-only caching for the external adjusted-close history source.

DO NOT EDIT THIS FILE FOR:
- E*TRADE OAuth/session behavior;
- GEX wall/gamma-flip formulas;
- GEX table/layout presentation;
- Risk Sizing, Holdings, navigation, or shared terminal infrastructure.

The production IV source remains E*TRADE OptionGreeks.iv. Historical closes are
used only to calculate trailing historical volatility (HV) for the IV/HV
reference. A Tiingo API token is kept in server memory only and is never written
to browser state, GitHub, or logs.
"""

from __future__ import annotations

import math
import statistics
import threading
import time
from datetime import date, timedelta
from typing import Any
from urllib.parse import quote

import requests


# ==============================
# REALIZED-VOLATILITY CONSTANTS
# ==============================
HV_WINDOW_RETURNS = 30
ANNUAL_TRADING_DAYS = 252
_HISTORY_LOOKBACK_CALENDAR_DAYS = 75
_CACHE_TTL_SECONDS = 4 * 60 * 60
_REQUEST_TIMEOUT_SECONDS = 8.0

_TOKEN_LOCK = threading.RLock()
_TIINGO_TOKEN = ""

_CACHE_LOCK = threading.RLock()
_HISTORY_CACHE: dict[str, dict[str, Any]] = {}


# ==============================
# SERVER-SIDE PROVIDER CONFIG
# ==============================
def configure_tiingo_token(token: str | None) -> None:
    """Install the app's Tiingo token in process memory only."""
    global _TIINGO_TOKEN
    clean = str(token or "").strip()
    with _TOKEN_LOCK:
        _TIINGO_TOKEN = clean


def _tiingo_token() -> str:
    with _TOKEN_LOCK:
        return _TIINGO_TOKEN


# ==============================
# 30-DAY HISTORICAL VOLATILITY
# ==============================
def historical_volatility_30d(closes: list[float]) -> float | None:
    """Return annualized 30-return close-to-close volatility.

    Method:
    - use the latest 31 positive closes, which produce 30 daily log returns;
    - r_t = ln(P_t / P_{t-1});
    - sample standard deviation (n-1);
    - annualize with sqrt(252).

    This matches the standard close-to-close historical-volatility method
    documented in Fidelity's IV Index guide and the annualization convention
    used in listed-volatility methodology.
    """
    clean: list[float] = []
    for raw in closes:
        try:
            value = float(raw)
        except (TypeError, ValueError):
            continue
        if math.isfinite(value) and value > 0:
            clean.append(value)

    needed = HV_WINDOW_RETURNS + 1
    if len(clean) < needed:
        return None

    window = clean[-needed:]
    returns = [
        math.log(window[index] / window[index - 1])
        for index in range(1, len(window))
    ]
    if len(returns) != HV_WINDOW_RETURNS:
        return None

    daily_sample_stdev = statistics.stdev(returns)
    hv = daily_sample_stdev * math.sqrt(float(ANNUAL_TRADING_DAYS))
    return hv if math.isfinite(hv) and hv > 0 else None


# ==============================
# TIINGO ADJUSTED-CLOSE HISTORY
# ==============================
def _cached(symbol: str) -> dict[str, Any] | None:
    now = time.time()
    with _CACHE_LOCK:
        row = _HISTORY_CACHE.get(symbol)
        if not row:
            return None
        if now - float(row.get("loaded_at", 0.0) or 0.0) > _CACHE_TTL_SECONDS:
            _HISTORY_CACHE.pop(symbol, None)
            return None
        return dict(row.get("value") or {})


def _store(symbol: str, value: dict[str, Any]) -> dict[str, Any]:
    with _CACHE_LOCK:
        _HISTORY_CACHE[symbol] = {
            "loaded_at": time.time(),
            "value": dict(value),
        }
    return dict(value)


def load_30d_historical_volatility(symbol: str) -> dict[str, Any]:
    """Load adjusted daily closes and calculate 30-day annualized HV.

    Tiingo is used because its documented EOD endpoint supplies adjusted closes
    and explicitly accounts for splits and dividends. The token is optional at
    code level; when it is not configured, callers receive a transparent
    unavailable status rather than a fabricated volatility value.
    """
    symbol = str(symbol or "").strip().upper()
    if not symbol:
        return {
            "historicalVolatility": None,
            "observations": 0,
            "source": "TIINGO ADJUSTED CLOSE",
            "status": "INVALID_SYMBOL",
        }

    cached = _cached(symbol)
    if cached is not None:
        return cached

    token = _tiingo_token()
    if not token:
        return {
            "historicalVolatility": None,
            "observations": 0,
            "source": "TIINGO ADJUSTED CLOSE",
            "status": "TIINGO_TOKEN_NOT_CONFIGURED",
        }

    today = date.today()
    start = today - timedelta(days=_HISTORY_LOOKBACK_CALENDAR_DAYS)
    url = (
        "https://api.tiingo.com/tiingo/daily/"
        + quote(symbol, safe=".-^")
        + "/prices"
    )
    params = {
        "startDate": start.isoformat(),
        "endDate": today.isoformat(),
        "resampleFreq": "daily",
    }
    headers = {
        "Authorization": f"Token {token}",
        "Content-Type": "application/json",
        "User-Agent": "Rajs-Terminal-GEX/1.0",
    }

    try:
        response = requests.get(
            url,
            params=params,
            headers=headers,
            timeout=_REQUEST_TIMEOUT_SECONDS,
        )
        response.raise_for_status()
        payload = response.json()
    except Exception as exc:
        return {
            "historicalVolatility": None,
            "observations": 0,
            "source": "TIINGO ADJUSTED CLOSE",
            "status": "DATA_ERROR",
            "error": str(exc)[:180],
        }

    if not isinstance(payload, list):
        return {
            "historicalVolatility": None,
            "observations": 0,
            "source": "TIINGO ADJUSTED CLOSE",
            "status": "BAD_RESPONSE",
        }

    rows: list[tuple[str, float]] = []
    for item in payload:
        if not isinstance(item, dict):
            continue
        raw_date = str(item.get("date") or "")[:10]
        try:
            close = float(item.get("adjClose"))
        except (TypeError, ValueError):
            continue
        if raw_date and math.isfinite(close) and close > 0:
            rows.append((raw_date, close))

    rows.sort(key=lambda row: row[0])
    closes = [close for _, close in rows]
    hv = historical_volatility_30d(closes)
    value = {
        "historicalVolatility": hv,
        "observations": max(0, len(closes) - 1),
        "source": "TIINGO ADJUSTED CLOSE",
        "asOf": rows[-1][0] if rows else "",
        "status": "OK" if hv is not None else "INSUFFICIENT_HISTORY",
    }
    return _store(symbol, value)


__all__ = [
    "ANNUAL_TRADING_DAYS",
    "HV_WINDOW_RETURNS",
    "configure_tiingo_token",
    "historical_volatility_30d",
    "load_30d_historical_volatility",
]
