"""Production GEX terminal wrapper for Raj's Terminal.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE ONLY for:
- obtaining the live E*TRADE client for GEX;
- resolving the terminal vault/session context;
- GEX-only wrapper CSS that is emitted while the GEX tab renders;
- eliminating GEX-owned hidden style rows that create blank vertical space.

DO NOT edit this file for:
- Risk Sizing;
- OAuth layout;
- Holdings;
- top-level terminal navigation;
- GEX tables/subtabs/analytics themselves (edit `src/gex_ui_v3.py`).

IMPORTANT: this module must NOT monkey-patch Streamlit at module import time.
A temporary wrapper is allowed only inside `render_gex()` and must always be
restored in `finally`.
"""

from __future__ import annotations

import inspect
import sys
from typing import Any

import streamlit as st

from src.gex_ui_v3 import render_gex as _render_gex_v3


# ==============================
# GEX-ONLY CSS
# ==============================

def _gex_subtab_skin_css() -> str:
    """Return GEX-only CSS without creating a standalone Streamlit row.

    A standalone ``st.markdown(<style>...)`` still becomes an element in
    Streamlit's vertical stack. Even when the style has no visible height, the
    surrounding stack can reserve a normal element gap. GEX previously emitted
    two such invisible rows before its first visible header, which is why the
    black gap survived navigation-frame fixes.
    """
    return """
        <style>
        /* Pull only the first visible GEX header up through Streamlit's normal
           inter-element gap. This rule is GEX-scoped because .gexv3-head only
           exists while the GEX feature is rendered. */
        [data-testid="stElementContainer"]:has(.gexv3-head) {
            margin-top: -1rem !important;
            padding-top: 0 !important;
        }

        /* GEX SECONDARY NAVIGATION */
        div[data-testid="stTabs"] > div[data-baseweb="tab-list"] {
            gap: .42rem !important;
            padding: .34rem 0 .48rem 0 !important;
            margin: .20rem 0 .58rem 0 !important;
            border-bottom: 1px solid #fb8b1e !important;
            overflow-x: visible !important;
            flex-wrap: wrap !important;
        }

        div[data-testid="stTabs"] button[role="tab"] {
            flex: 0 0 auto !important;
            min-width: 118px !important;
            min-height: 38px !important;
            padding: .46rem .82rem !important;
            margin: 0 !important;
            border: 1px solid #fb8b1e !important;
            border-radius: 0 !important;
            background: #050505 !important;
            color: #fb8b1e !important;
            box-shadow: none !important;
            font-family: "Courier New", monospace !important;
            font-size: .74rem !important;
            font-weight: 900 !important;
            letter-spacing: .02em !important;
            text-transform: uppercase !important;
        }

        div[data-testid="stTabs"] button[role="tab"]:hover {
            background: #171007 !important;
            color: #ffad52 !important;
        }

        div[data-testid="stTabs"] button[role="tab"][aria-selected="true"] {
            background: #fb8b1e !important;
            color: #000000 !important;
            border-color: #fb8b1e !important;
            box-shadow: inset 0 -3px 0 #a64b00 !important;
        }

        div[data-testid="stTabs"] button[role="tab"] * {
            color: inherit !important;
            font-family: "Courier New", monospace !important;
            font-weight: 900 !important;
        }

        div[data-testid="stTabs"] div[data-baseweb="tab-highlight"] {
            display: none !important;
        }

        div[data-testid="stTabs"] div[data-baseweb="tab-panel"] {
            padding-top: .22rem !important;
        }
        </style>
    """


def _is_style_only_markdown(body: Any) -> bool:
    if not isinstance(body, str):
        return False
    stripped = body.strip()
    return stripped.startswith("<style>") and stripped.endswith("</style>")


# ==============================
# E*TRADE / TERMINAL CONTEXT
# ==============================

def _discover_terminal_context() -> tuple[Any, str, Any]:
    """Resolve the live terminal client, access-code vault key, and touch hook.

    This is context plumbing only. GEX calculations and presentation belong in
    `src/gex_ui_v3.py`.
    """
    candidates: list[dict[str, Any]] = []
    main = sys.modules.get("__main__")
    if main is not None:
        candidates.append(vars(main))
    for frame in inspect.stack()[1:18]:
        candidates.append(frame.frame.f_globals)

    for scope in candidates:
        live_factory = scope.get("_live_etrade_client")
        factory = live_factory if callable(live_factory) else scope.get("_etrade_client")
        hash_fn = scope.get("_trade_access_code_hash")
        touch = scope.get("_touch_etrade_session")
        if not callable(factory):
            continue

        try:
            client = factory()
        except Exception:
            client = None
        try:
            vault_key = str(hash_fn()) if callable(hash_fn) else "default"
        except Exception:
            vault_key = "default"
        return client, vault_key or "default", touch

    return None, "default", None


# ==============================
# COMPACT GEX RENDER BRIDGE
# ==============================

def _render_without_hidden_style_rows(client: Any, vault_key: str, touch: Any) -> None:
    """Render GEX while folding leading CSS into its first visible header.

    `src.gex_ui_v3.py` begins with its own style-only markdown call. Rendering
    that call normally creates another invisible Streamlit element before the
    workspace header. Intercept only style-only markdown calls while GEX is
    rendering, buffer them, and prepend them to the first visible markdown
    block. The original ``st.markdown`` is restored unconditionally.
    """
    original_markdown = st.markdown
    pending_css: list[str] = [_gex_subtab_skin_css()]
    flushed = False

    def compact_markdown(body: Any, *args: Any, **kwargs: Any):
        nonlocal flushed

        if not flushed and _is_style_only_markdown(body):
            pending_css.append(str(body))
            return None

        if not flushed and isinstance(body, str):
            combined = "\n".join(pending_css) + "\n" + body
            pending_css.clear()
            flushed = True
            local_kwargs = dict(kwargs)
            local_kwargs["unsafe_allow_html"] = True
            return original_markdown(combined, *args, **local_kwargs)

        return original_markdown(body, *args, **kwargs)

    st.markdown = compact_markdown
    try:
        _render_gex_v3(client, vault_key, touch)
    finally:
        st.markdown = original_markdown


# ==============================
# PUBLIC GEX ENTRYPOINT
# ==============================

def render_gex() -> None:
    """Render only the GEX feature with no hidden pre-header spacer rows."""
    client, vault_key, touch = _discover_terminal_context()
    _render_without_hidden_style_rows(client, vault_key, touch)


__all__ = ["render_gex"]
