"""Production GEX UI interaction layer.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- row-level GEX watchlist actions layered onto the stable GEX v3 UI;
- non-blocking/background GEX refresh-all interaction;
- compact Overview presentation overlays such as range/regime visualization;
- TradingView/Pine router export compatibility;
- small interaction adapters that must not disturb GEX calculations.

DO NOT EDIT THIS FILE FOR:
- Risk Sizing, OAuth, Holdings, navigation, or shared authentication;
- GEX calculation formulas (owned by ``src.gex_ui``);
- the stable bulk of the GEX v3 renderer (preserved in ``src.gex_ui_v3_base``).

This file intentionally stays small. The proven GEX v3 implementation is kept
in ``src/gex_ui_v3_base.py``; this layer adds requested interaction/presentation
behavior and delegates the analytics/layout renderer unchanged.
"""

from __future__ import annotations

import copy
import html
import re
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any, Callable
from urllib.parse import urlencode

import streamlit as st

from src import gex_ui_v3_base as _base


# ==============================
# BACKGROUND REFRESH-ALL ENGINE
# ==============================
# IMPORTANT: Worker threads must never call Streamlit APIs or touch
# st.session_state. The worker receives a dedicated E*TRADE client factory made
# from a main-thread credential/token snapshot and writes only to this
# thread-safe process-memory job registry. Completed results are merged into the
# normal GEX result vault later from the Streamlit render thread.
#
# E*TRADE requires separate quote, expiration-list, and per-expiration chain
# requests for each ticker. Refreshing 49 symbols serially therefore spends most
# of its time waiting on network round-trips. Keep concurrency deliberately
# bounded: four independent OAuth clients can refresh four tickers at once
# without changing which expirations or calculations are used.
_BACKGROUND_MAX_WORKERS = 4
_BACKGROUND_LOCK = threading.RLock()
_BACKGROUND_JOBS: dict[str, dict[str, Any]] = {}


def _background_job(vault_key: str) -> dict[str, Any] | None:
    with _BACKGROUND_LOCK:
        job = _BACKGROUND_JOBS.get(str(vault_key or "default"))
        if not job:
            return None
        active = sorted(str(value) for value in (job.get("active") or set()) if value)
        current = ", ".join(active) if active else str(job.get("current") or "")
        return {
            "status": str(job.get("status") or ""),
            "total": int(job.get("total", 0) or 0),
            "completed": int(job.get("completed", 0) or 0),
            "updated": int(job.get("updated", 0) or 0),
            "current": current,
            "workers": int(job.get("workers", 1) or 1),
            "failures": dict(job.get("failures") or {}),
            "started_at": float(job.get("started_at", 0.0) or 0.0),
            "finished_at": float(job.get("finished_at", 0.0) or 0.0),
        }


def background_refresh_status(vault_key: str) -> dict[str, Any] | None:
    """Read-only status hook for future terminal-level background indicators."""
    return _background_job(vault_key)


def _background_running(vault_key: str) -> bool:
    snapshot = _background_job(vault_key)
    return bool(snapshot and snapshot.get("status") in {"QUEUED", "RUNNING"})


def _run_background_refresh(
    vault_key: str,
    state_snapshot: dict[str, Any],
    tickers: list[str],
    client_factory: Callable[[], Any],
) -> None:
    """Refresh tickers in a small parallel pool without using Streamlit APIs."""
    key = str(vault_key or "default")
    workers = max(1, min(_BACKGROUND_MAX_WORKERS, len(tickers)))
    thread_local = threading.local()

    def worker_client() -> Any:
        client = getattr(thread_local, "client", None)
        if client is None:
            client = client_factory()
            if client is None:
                raise RuntimeError("E*TRADE background client is unavailable")
            thread_local.client = client
        return client

    def refresh_ticker(ticker: str) -> tuple[str, Any | None, str | None]:
        with _BACKGROUND_LOCK:
            job = _BACKGROUND_JOBS.get(key)
            if job is None:
                return ticker, None, "Background GEX job was cancelled"
            job.setdefault("active", set()).add(ticker)

        try:
            dte = int(
                state_snapshot.get("dte_overrides", {}).get(
                    ticker,
                    state_snapshot["global_dte"],
                )
            )
            result = _base.core._build_gex(
                worker_client(),
                ticker,
                dte,
                state_snapshot["timezone"],
                state_snapshot["wall_value_mode"],
                force_refresh=True,
            )
            return ticker, result, None
        except Exception as exc:
            return ticker, None, str(exc)[:500]
        finally:
            with _BACKGROUND_LOCK:
                job = _BACKGROUND_JOBS.get(key)
                if job is not None:
                    job.setdefault("active", set()).discard(ticker)

    with _BACKGROUND_LOCK:
        job = _BACKGROUND_JOBS.get(key)
        if job is not None:
            job["status"] = "RUNNING"
            job["workers"] = workers

    try:
        with ThreadPoolExecutor(
            max_workers=workers,
            thread_name_prefix="raj-gex-fetch",
        ) as pool:
            futures = [pool.submit(refresh_ticker, ticker) for ticker in tickers]
            for future in as_completed(futures):
                try:
                    ticker, result, error = future.result()
                except Exception as exc:
                    ticker, result, error = "E*TRADE", None, str(exc)[:500]

                with _BACKGROUND_LOCK:
                    job = _BACKGROUND_JOBS.get(key)
                    if job is None:
                        return
                    job["completed"] = int(job.get("completed", 0) or 0) + 1
                    if error:
                        job["failures"][ticker] = error
                    elif result is not None:
                        job["results"][ticker] = result
                        job["updated"] = len(job["results"])
    except Exception as exc:
        with _BACKGROUND_LOCK:
            job = _BACKGROUND_JOBS.get(key)
            if job is not None:
                job["status"] = "FAILED"
                job["failures"]["E*TRADE"] = str(exc)[:500]
                job["finished_at"] = time.time()
        return

    with _BACKGROUND_LOCK:
        job = _BACKGROUND_JOBS.get(key)
        if job is not None:
            job["current"] = ""
            job["active"] = set()
            job["status"] = "DONE_WITH_ERRORS" if job["failures"] else "DONE"
            job["finished_at"] = time.time()


def _start_background_refresh(
    vault_key: str,
    state_snapshot: dict[str, Any],
    client_factory: Callable[[], Any],
) -> bool:
    """Start at most one bounded-parallel refresh-all worker for a GEX vault."""
    key = str(vault_key or "default")
    tickers = [
        _base.core._normalize_ticker(value)
        for value in state_snapshot.get("tickers", [])
        if _base.core._normalize_ticker(value)
    ]
    if not tickers:
        return False
    workers = max(1, min(_BACKGROUND_MAX_WORKERS, len(tickers)))

    with _BACKGROUND_LOCK:
        existing = _BACKGROUND_JOBS.get(key)
        if existing and existing.get("status") in {"QUEUED", "RUNNING"}:
            return False
        _BACKGROUND_JOBS[key] = {
            "status": "QUEUED",
            "total": len(tickers),
            "completed": 0,
            "updated": 0,
            "current": "",
            "active": set(),
            "workers": workers,
            "failures": {},
            "results": {},
            "synced": set(),
            "started_at": time.time(),
            "finished_at": 0.0,
        }

    worker = threading.Thread(
        target=_run_background_refresh,
        args=(key, copy.deepcopy(state_snapshot), list(tickers), client_factory),
        name="raj-gex-refresh-all",
        daemon=True,
    )
    worker.start()
    return True


def _sync_background_results(vault_key: str) -> int:
    """Merge newly completed worker results into the normal GEX vault."""
    key = str(vault_key or "default")
    pending: dict[str, Any] = {}
    with _BACKGROUND_LOCK:
        job = _BACKGROUND_JOBS.get(key)
        if not job:
            return 0
        synced = job.setdefault("synced", set())
        for ticker, result in (job.get("results") or {}).items():
            if ticker not in synced:
                pending[ticker] = copy.deepcopy(result)
        synced.update(pending)

    if not pending:
        return 0
    result_map = _base.core._results(key)
    result_map.update(pending)
    return len(pending)


def _render_background_status(vault_key: str) -> None:
    """Show a compact animated status line when a background job exists."""
    _sync_background_results(vault_key)
    job = _background_job(vault_key)
    if not job:
        return

    status = job["status"]
    if status in {"QUEUED", "RUNNING"}:
        current = f" // ACTIVE {html.escape(job['current'])}" if job["current"] else ""
        st.html(
            '<div class="gexv3-running-status">'
            '<span class="gexv3-running-icon">↻</span>'
            '<span>BACKGROUND GEX // '
            f"{job['workers']}-WAY // {job['completed']}/{job['total']} PROCESSED // "
            f"{job['updated']} UPDATED{current} // YOU CAN SWITCH TABS WHILE THIS RUNS"
            "</span></div>"
        )
        return

    failures = len(job["failures"])
    if status == "DONE":
        st.caption(
            f"BACKGROUND GEX COMPLETE // {job['updated']}/{job['total']} UPDATED"
        )
    elif status == "DONE_WITH_ERRORS":
        st.caption(
            f"BACKGROUND GEX COMPLETE // {job['updated']}/{job['total']} UPDATED // "
            f"{failures} FAILED"
        )
    elif status == "FAILED":
        st.caption("BACKGROUND GEX FAILED // reconnect E*TRADE and retry")


# ==============================
# OVERVIEW TABLE PRESENTATION
# ==============================
# Gamma regime is displayed relative to the calculated gamma flip. A small
# +/-0.50% neutral band prevents tiny spot/flip differences from oscillating
# between POSITIVE and NEGATIVE labels on routine quote noise.
_GAMMA_NEUTRAL_BAND = 0.005

_ROW_ACTION_CSS = """
<style>
/* GEX OVERVIEW TYPE — approximately +3 points from the legacy .69rem table. */
.gexv3-summary {
    font-size:11.25pt !important;
    line-height:1.18 !important;
}
.gexv3-summary th,
.gexv3-summary td {
    font-size:inherit !important;
    line-height:inherit !important;
}

/* Keep the delete affordance inside the TICKER cell, aligned left beside symbol. */
.gexv3-summary td.sym {
    overflow: visible !important;
    text-align: left !important;
    padding-left: .48rem !important;
}
.gexv3-symbol-wrap {
    display:inline-flex !important;
    align-items:center !important;
    justify-content:flex-start !important;
    gap:.38rem !important;
    width:100% !important;
    white-space:nowrap !important;
}
.gexv3-symbol-text {
    color:#4af6c3 !important;
    font-weight:900 !important;
}
.gexv3-trash-link {
    display:inline-flex !important;
    align-items:center !important;
    justify-content:center !important;
    flex:0 0 auto !important;
    width:1.42rem !important;
    height:1.32rem !important;
    padding:0 !important;
    margin:0 !important;
    border:1px solid #5d3605 !important;
    background:#050505 !important;
    color:#fb8b1e !important;
    -webkit-text-fill-color:#fb8b1e !important;
    text-decoration:none !important;
    font-size:10.5pt !important;
    line-height:1 !important;
    cursor:pointer !important;
}
.gexv3-trash-link:hover {
    border-color:#ff433d !important;
    color:#ff433d !important;
    -webkit-text-fill-color:#ff433d !important;
    background:#160606 !important;
}

/* Interactive range/regime line: PUT wall, gamma flip, SPOT, CALL wall. */
.gexv3-summary td.gexv3-range-col {
    overflow:visible !important;
    white-space:normal !important;
    padding:.38rem .42rem !important;
    position:relative !important;
}
.gexv3-summary tbody tr:hover td.gexv3-range-col,
.gexv3-summary td.gexv3-range-col:focus-within {
    background:#0c0905 !important;
    z-index:40 !important;
}
.gexv3-range-mini {
    position:relative !important;
    height:20px !important;
    margin:.08rem .18rem .14rem !important;
}
.gexv3-range-line {
    position:absolute !important;
    left:3% !important;
    right:3% !important;
    top:9px !important;
    height:2px !important;
    background:#8d5b1d !important;
    transition:background .12s ease,height .12s ease,top .12s ease !important;
}
.gexv3-range-zone {
    position:absolute !important;
    top:7px !important;
    height:6px !important;
    min-width:4px !important;
    border-radius:3px !important;
    opacity:.30 !important;
    pointer-events:none !important;
    z-index:1 !important;
}
.gexv3-range-zone.positive{background:#4af6c3 !important;}
.gexv3-range-zone.neutral{background:#fb8b1e !important;}
.gexv3-range-zone.negative{background:#ff5757 !important;}
.gexv3-range-col:hover .gexv3-range-line,
.gexv3-range-col:focus-within .gexv3-range-line {
    background:#fb8b1e !important;
    height:3px !important;
    top:8.5px !important;
}
.gexv3-range-dot {
    position:absolute !important;
    top:4px !important;
    width:12px !important;
    height:12px !important;
    margin-left:-6px !important;
    border-radius:50% !important;
    border:1px solid #020202 !important;
    box-shadow:0 0 0 1px rgba(255,255,255,.18) !important;
    cursor:help !important;
    z-index:3 !important;
    transition:transform .12s ease,box-shadow .12s ease !important;
    outline:none !important;
}
.gexv3-range-dot.put{background:#ff5757 !important;}
.gexv3-range-dot.flip{background:#fb8b1e !important;}
.gexv3-range-dot.spot{background:#f2f2f2 !important;}
.gexv3-range-dot.call{background:#4af6c3 !important;}
.gexv3-range-dot:hover,
.gexv3-range-dot:focus-visible {
    transform:scale(1.45) !important;
    box-shadow:0 0 0 2px #fb8b1e,0 0 8px rgba(251,139,30,.55) !important;
    z-index:30 !important;
}
.gexv3-range-dot::after {
    content:attr(data-tip) !important;
    position:absolute !important;
    left:50% !important;
    bottom:18px !important;
    transform:translateX(-50%) scale(.96) !important;
    transform-origin:bottom center !important;
    opacity:0 !important;
    pointer-events:none !important;
    white-space:nowrap !important;
    background:#050505 !important;
    border:1px solid #fb8b1e !important;
    color:#f2f2f2 !important;
    -webkit-text-fill-color:#f2f2f2 !important;
    padding:.20rem .34rem !important;
    font:900 8.5pt/1.05 "Courier New",monospace !important;
    letter-spacing:.01em !important;
    transition:opacity .10s ease,transform .10s ease !important;
    z-index:60 !important;
}
.gexv3-range-dot:hover::after,
.gexv3-range-dot:focus-visible::after {
    opacity:1 !important;
    transform:translateX(-50%) scale(1) !important;
}
.gexv3-range-meta {
    font:900 8.8pt/1.12 "Courier New",monospace !important;
    letter-spacing:.01em !important;
    text-align:center !important;
    white-space:nowrap !important;
}
.gexv3-range-meta.positive{color:#4af6c3 !important;}
.gexv3-range-meta.neutral{color:#fb8b1e !important;}
.gexv3-range-meta.negative{color:#ff5757 !important;}

/* Real animated work indicator for the detached backend refresh. */
.gexv3-running-status {
    display:flex !important;
    align-items:center !important;
    gap:.45rem !important;
    width:fit-content !important;
    max-width:100% !important;
    border:1px solid #fb8b1e !important;
    background:#050505 !important;
    color:#fb8b1e !important;
    padding:.24rem .48rem !important;
    margin:.04rem 0 .30rem !important;
    font:900 9pt/1.1 "Courier New",monospace !important;
}
.gexv3-running-icon {
    display:inline-block !important;
    color:#4af6c3 !important;
    font-size:13pt !important;
    line-height:1 !important;
    animation:gexv3-spin .75s linear infinite !important;
}
@keyframes gexv3-spin {
    to { transform:rotate(360deg); }
}
</style>
"""


def _delete_href(ticker: str) -> str:
    """Build a same-page delete URL while preserving unrelated query state."""
    params: dict[str, Any] = {}
    try:
        for key in st.query_params:
            values = st.query_params.get_all(key)
            params[key] = values if len(values) > 1 else (values[0] if values else "")
    except Exception:
        params = {}
    params["gex_delete"] = ticker
    return "?" + urlencode(params, doseq=True)


def _inject_row_trash(markup: str) -> str:
    """Place one left-aligned clickable trash icon inside every ticker cell."""
    if 'class="gexv3-summary"' not in markup:
        return markup

    def replace_symbol(match: re.Match[str]) -> str:
        ticker = html.unescape(match.group(1)).strip().upper()
        ticker_html = html.escape(ticker)
        href = html.escape(_delete_href(ticker), quote=True)
        return (
            '<td class="sym">'
            '<span class="gexv3-symbol-wrap">'
            f'<a class="gexv3-trash-link" href="{href}" target="_self" '
            f'aria-label="Delete {ticker_html} from GEX" '
            f'title="Delete {ticker_html} from GEX">🗑</a>'
            f'<span class="gexv3-symbol-text">{ticker_html}</span>'
            '</span>'
            '</td>'
        )

    return re.sub(
        r'<td class="sym">([^<]+)</td>',
        replace_symbol,
        markup,
    )


def _gamma_regime(result: dict[str, Any]) -> tuple[str, str]:
    """Classify spot relative to gamma flip with a small neutral noise band."""
    try:
        spot = float(result.get("spot"))
        flip = float(result.get("gammaFlip"))
    except (TypeError, ValueError):
        return "NEUTRAL", "neutral"
    if spot <= 0 or flip <= 0:
        return "NEUTRAL", "neutral"

    distance = (spot - flip) / flip
    if abs(distance) <= _GAMMA_NEUTRAL_BAND:
        return "NEUTRAL", "neutral"
    if distance > 0:
        return "POSITIVE", "positive"
    return "NEGATIVE", "negative"


def _range_visual(result: dict[str, Any]) -> str:
    """Build an interactive line/dot range with gamma-flip regime metadata."""
    try:
        spot = float(result["spot"])
        put_wall = float(result["putWall"]["strike"])
        call_wall = float(result["callWall"]["strike"])
    except (KeyError, TypeError, ValueError):
        return '<span class="gexv3-range-meta neutral">RANGE WAITING</span>'

    try:
        gamma_flip = float(result.get("gammaFlip"))
        has_flip = gamma_flip > 0
    except (TypeError, ValueError):
        gamma_flip = 0.0
        has_flip = False

    points = [put_wall, spot, call_wall]
    if has_flip:
        points.append(gamma_flip)
    low = min(points)
    high = max(points)
    span = high - low

    def position(value: float) -> float:
        if span <= 0:
            return 50.0
        return max(3.0, min(97.0, 3.0 + 94.0 * ((value - low) / span)))

    def dot(kind: str, label: str, value: float) -> str:
        tip = html.escape(f"{label} ${value:,.2f}", quote=True)
        return (
            f'<span class="gexv3-range-dot {kind}" tabindex="0" role="img" '
            f'aria-label="{tip}" data-tip="{tip}" '
            f'style="left:{position(value):.2f}%"></span>'
        )

    regime, tone = _gamma_regime(result)
    flip_text = f"${gamma_flip:,.2f}" if has_flip else "—"
    distance_text = "—"
    zone = ""
    flip_dot = ""
    if has_flip:
        distance_pct = ((spot - gamma_flip) / gamma_flip) * 100.0
        distance_text = f"{distance_pct:+.2f}%"
        flip_position = position(gamma_flip)
        spot_position = position(spot)
        zone_left = min(flip_position, spot_position)
        zone_width = max(0.7, abs(spot_position - flip_position))
        zone = (
            f'<span class="gexv3-range-zone {tone}" '
            f'style="left:{zone_left:.2f}%;width:{zone_width:.2f}%"></span>'
        )
        flip_dot = dot("flip", "GAMMA FLIP", gamma_flip)

    range_label = html.escape(
        f"PUT WALL ${put_wall:,.2f}; GAMMA FLIP {flip_text}; "
        f"SPOT ${spot:,.2f}; CALL WALL ${call_wall:,.2f}",
        quote=True,
    )
    return (
        f'<div class="gexv3-range-mini" aria-label="{range_label}">'
        '<span class="gexv3-range-line"></span>'
        f"{zone}"
        f'{dot("put", "PUT WALL", put_wall)}'
        f"{flip_dot}"
        f'{dot("spot", "SPOT", spot)}'
        f'{dot("call", "CALL WALL", call_wall)}'
        "</div>"
        f'<div class="gexv3-range-meta {tone}">'
        f"GF {flip_text} // {regime} GAMMA // Δ {distance_text}"
        "</div>"
    )


def _decorate_overview(markup: str, vault_key: str) -> str:
    """Add row trash, wider range column, and gamma regime visualization."""
    if 'class="gexv3-summary"' not in markup:
        return markup

    if "<colgroup>" not in markup:
        colgroup = (
            "<colgroup>"
            '<col style="width:12%"><col style="width:6%"><col style="width:10%">'
            '<col style="width:10%"><col style="width:10%"><col style="width:10%">'
            '<col style="width:28%"><col style="width:14%">'
            "</colgroup>"
        )
        markup = markup.replace(
            '<table class="gexv3-summary"><thead>',
            '<table class="gexv3-summary">' + colgroup + "<thead>",
            1,
        )

    result_map = _base.core._results(str(vault_key or "default"))

    def decorate_row(match: re.Match[str]) -> str:
        inner = match.group(1)
        ticker_match = re.search(r'<td class="sym">([^<]+)</td>', inner)
        if not ticker_match:
            return match.group(0)
        ticker = html.unescape(ticker_match.group(1)).strip().upper()
        result = result_map.get(ticker)
        if not result:
            return match.group(0)

        status, tone = _base._range_status(result)
        legacy = f'<td class="{tone}">{status}</td>'
        replacement = f'<td class="gexv3-range-col">{_range_visual(result)}</td>'
        inner = inner.replace(legacy, replacement, 1)
        return "<tr>" + inner + "</tr>"

    markup = re.sub(r"<tr>(.*?)</tr>", decorate_row, markup, flags=re.DOTALL)
    return _inject_row_trash(markup)


def _consume_delete_request(vault_key: str) -> None:
    """Persist a row-trash request, clear only that query parameter, and rerun."""
    try:
        raw = st.query_params.get("gex_delete")
    except Exception:
        raw = None
    ticker = _base.core._normalize_ticker(raw)
    if not ticker:
        return

    state = copy.deepcopy(_base.core._load_state(str(vault_key or "default")))
    result_map = _base.core._results(str(vault_key or "default"))
    if ticker in state.get("tickers", []):
        _base._remove_ticker(str(vault_key or "default"), state, result_map, ticker)

    try:
        del st.query_params["gex_delete"]
    except Exception:
        pass
    st.rerun()


# ==============================
# TRADINGVIEW / PINE ROUTER BRIDGE
# ==============================
# The supplied Google Apps Script is the MASTER A6 serialization contract.
# Successful tickers keep its full human-readable summary + packed rows, while
# failed tickers keep the Apps Script ``Ticker:`` / ``ERROR:`` block. The fixed
# Pine router ignores metadata and consumes the packed row types after matching
# the ticker header, so one failed symbol must never hide the copyable A6 block.
_PINE_TEXT_LIMIT = 40_960
_PINE_REQUIRED_TYPES = {"SPOT", "CALLWALL", "PUTWALL", "MAXCALLOI", "MAXPUTOI"}


def _pine_router_block(result: dict[str, Any]) -> str:
    """Emit only the rows consumed by Pine; retained as a compact diagnostic."""
    symbol = _base.core._normalize_ticker(result.get("symbol"))
    if not symbol:
        return ""
    packed_rows = _base._packed_gamma_lines(result)
    return "\n".join([f"Ticker: {symbol}", *packed_rows])


def _pine_master_bridge_text(result_map: dict[str, Any], tickers: list[str]) -> str:
    """Build a compact all-successful-ticker payload for parser diagnostics."""
    blocks: list[str] = []
    for raw_ticker in tickers:
        ticker = _base.core._normalize_ticker(raw_ticker)
        result = result_map.get(ticker)
        if not result:
            continue
        block = _pine_router_block(result)
        if block:
            blocks.append(block)
    return "\n\n".join(blocks).strip()


def _google_sheets_master_text(
    result_map: dict[str, Any],
    tickers: list[str],
    failures: dict[str, str] | None = None,
) -> str:
    """Mirror ``refreshGEX`` -> ``allOutputLines`` -> TradingView A6 exactly.

    The supplied Apps Script appends successful ``summaryText.split('\\n')``
    rows plus one extra blank row. Failed tickers append ``Ticker:``, ``ERROR:``,
    and one blank row. Joining with ``\\n`` and trimming produces the exact A6
    shape expected by the user's existing Pine input workflow.
    """
    normalized_failures = {
        _base.core._normalize_ticker(key): " ".join(str(value).split())
        for key, value in (failures or {}).items()
        if _base.core._normalize_ticker(key)
    }
    all_output_lines: list[str] = []

    for raw_ticker in tickers:
        ticker = _base.core._normalize_ticker(raw_ticker)
        if not ticker:
            continue

        if ticker in normalized_failures:
            all_output_lines.extend(
                [
                    f"Ticker: {ticker}",
                    f"ERROR: {normalized_failures[ticker]}",
                    "",
                ]
            )
            continue

        result = result_map.get(ticker)
        if result:
            summary = _base._google_sheets_summary_text(result)
            all_output_lines.extend(summary.split("\n"))
            all_output_lines.append("")
            continue

        all_output_lines.extend(
            [
                f"Ticker: {ticker}",
                "ERROR: No refreshed GEX result available.",
                "",
            ]
        )

    if not all_output_lines:
        all_output_lines.append("")
    return "\n".join(all_output_lines).strip()


def _pine_router_headers(text: str) -> list[str]:
    """Return normalized Ticker headers exactly as the Pine router sees them."""
    return [
        _base.core._normalize_ticker(value)
        for value in re.findall(r"(?m)^Ticker:\s*([^\r\n]+)\s*$", str(text or ""))
        if _base.core._normalize_ticker(value)
    ]


def _pine_ticker_block(text: str, ticker: str) -> str:
    """Extract one routed block using the same Ticker-header boundary Pine uses."""
    target = _base.core._normalize_ticker(ticker)
    if not target:
        return ""
    normalized = str(text or "").replace("\r\n", "\n").replace("\r", "\n")
    active = False
    out: list[str] = []
    for row in normalized.split("\n"):
        header = re.match(r"^\s*Ticker:\s*([^\r\n]+?)\s*$", row, flags=re.IGNORECASE)
        if header:
            found = _base.core._normalize_ticker(header.group(1))
            if active and found != target:
                break
            active = found == target
        if active:
            out.append(row)
    return "\n".join(out).strip()


def _pine_parsed_types(block: str) -> list[str]:
    """Replica of the fixed Pine row parser for Streamlit-side preflight checks."""
    parsed: list[str] = []
    for raw_row in str(block or "").replace("\r", "").split("\n"):
        compact = raw_row.replace("|", ",").replace(" ", "").replace("\t", "")
        parts = compact.split(",")
        if len(parts) < 2:
            continue
        typ = parts[0].strip().upper()
        is_packed = (
            typ in {"SPOT", "GFLIP", "CALLWALL", "PUTWALL", "MAXCALLOI", "MAXPUTOI"}
            or typ.startswith("GEXPOS")
            or typ.startswith("GEXNEG")
        )
        if not is_packed:
            continue
        try:
            float(parts[1])
        except (TypeError, ValueError):
            continue
        parsed.append(typ)
    return parsed


def _pine_ticker_issues(text: str, ticker: str) -> tuple[list[str], int]:
    """Validate one ticker exactly enough to guarantee Pine has drawable levels."""
    target = _base.core._normalize_ticker(ticker)
    block = _pine_ticker_block(text, target)
    if not block:
        return [f"{target}:NO_HEADER"], 0
    parsed = _pine_parsed_types(block)
    parsed_set = set(parsed)
    issues = [f"{target}:NO_{typ}" for typ in sorted(_PINE_REQUIRED_TYPES - parsed_set)]
    if not any(typ.startswith("GEXPOS") or typ.startswith("GEXNEG") for typ in parsed):
        issues.append(f"{target}:NO_GEX")
    return issues, len(parsed)


def _pine_master_issues(text: str, expected: list[str]) -> tuple[list[str], dict[str, int]]:
    """Run the fixed Pine routing/parsing contract against successful tickers."""
    issues: list[str] = []
    counts: dict[str, int] = {}
    headers = _pine_router_headers(text)
    duplicate_headers = sorted({ticker for ticker in headers if headers.count(ticker) > 1})
    issues.extend(f"{ticker}:DUPLICATE_HEADER" for ticker in duplicate_headers)
    for ticker in expected:
        ticker_issues, parsed_count = _pine_ticker_issues(text, ticker)
        counts[ticker] = parsed_count
        issues.extend(ticker_issues)
    return issues, counts


_TRADINGVIEW_CODE_CSS = """
<style>
/* GEX TradingView bridge only: keep code and copy affordance visible on black. */
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] {
    background:#030303 !important;
    border:1px solid #5d3605 !important;
    box-shadow:0 0 0 1px rgba(251,139,30,.08) !important;
}
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] pre,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] code {
    background:#030303 !important;
    color:#f4f4f4 !important;
    -webkit-text-fill-color:#f4f4f4 !important;
}
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"],
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"] {
    background:#050505 !important;
    color:#fb8b1e !important;
    -webkit-text-fill-color:#fb8b1e !important;
    border:1px solid #fb8b1e !important;
    opacity:1 !important;
    visibility:visible !important;
    box-shadow:0 0 0 1px rgba(251,139,30,.16) !important;
}
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"],
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button[aria-label*="Copy"] {
    min-width:7.8rem !important;
    min-height:2rem !important;
    padding:.22rem .48rem !important;
    display:inline-flex !important;
    align-items:center !important;
    justify-content:center !important;
    gap:.32rem !important;
    font:900 8.5pt/1 "Courier New",monospace !important;
}
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"]::after,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button[aria-label*="Copy"]::after {
    content:"COPY A6" !important;
    color:inherit !important;
    -webkit-text-fill-color:inherit !important;
    font:900 8.5pt/1 "Courier New",monospace !important;
    letter-spacing:.02em !important;
}
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"] svg,
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"] svg *,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button svg,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button svg *,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"] svg,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"] svg * {
    color:#fb8b1e !important;
    stroke:#fb8b1e !important;
    fill:#fb8b1e !important;
}
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"]:hover,
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"]:focus-visible,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button:hover,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button:focus-visible,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"]:hover,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"]:focus-visible {
    background:#fb8b1e !important;
    color:#020202 !important;
    -webkit-text-fill-color:#020202 !important;
    border-color:#ffad52 !important;
    box-shadow:0 0 0 2px rgba(251,139,30,.30) !important;
}
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"]:hover svg *,
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"]:focus-visible svg *,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button:hover svg *,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button:focus-visible svg *,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"]:hover svg *,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"]:focus-visible svg * {
    color:#020202 !important;
    stroke:#020202 !important;
    fill:#020202 !important;
}
/* Make Streamlit's real clipboard control unmistakable instead of an icon-only affordance. */
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"],
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"] {
    min-width:10.4rem !important;
    width:auto !important;
    padding:.34rem .58rem !important;
    gap:.32rem !important;
}
.st-key-gexv3_bridge_code [data-testid="stCodeBlockCopyButton"]::after,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] button::after,
.st-key-gexv3_bridge_code [data-testid="stCodeBlock"] [role="button"]::after {
    content:"COPY MASTER A6" !important;
    display:inline-block !important;
    color:inherit !important;
    -webkit-text-fill-color:inherit !important;
    font:900 8.5pt/1 "Courier New",monospace !important;
    letter-spacing:.02em !important;
    white-space:nowrap !important;
}
</style>
"""


def _render_tradingview_pine(
    state: dict[str, Any],
    result_map: dict[str, Any],
    failures: dict[str, str] | None = None,
) -> None:
    """Render the supplied Apps Script MASTER A6 shape without hiding failures."""
    saved: list[str] = []
    for value in state.get("tickers", []):
        ticker = _base.core._normalize_ticker(value)
        if ticker and ticker not in saved:
            saved.append(ticker)
    if not saved:
        st.info("Add GEX tickers first.")
        return

    normalized_failures = {
        _base.core._normalize_ticker(key): str(value)
        for key, value in (failures or {}).items()
        if _base.core._normalize_ticker(key)
    }
    available = [
        ticker
        for ticker in saved
        if ticker in result_map and ticker not in normalized_failures
    ]
    unavailable = [ticker for ticker in saved if ticker not in available]

    master_label = "MASTER A6 // GOOGLE APPS SCRIPT FORMAT — COPY THIS"
    compact_label = "COMPACT PINE // DIAGNOSTIC ONLY"
    options = [master_label, compact_label] + available
    choice = st.selectbox(
        "PACKED GAMMA BLOCK",
        options,
        key="gexv3_bridge_choice_google_a6_v3",
    )

    is_master = choice == master_label
    is_compact = choice == compact_label
    if is_master:
        text = _google_sheets_master_text(result_map, saved, normalized_failures)
        filename = "raj_terminal_MASTER_A6.txt"
        expected_headers = saved
        parser_expected = available
        mode_text = "GOOGLE APPS SCRIPT A6 // FULL SUMMARY + PACKED ROWS + ERROR BLOCKS"
    elif is_compact:
        text = _pine_master_bridge_text(result_map, available)
        filename = "raj_terminal_gex_compact_pine.txt"
        expected_headers = available
        parser_expected = available
        mode_text = "COMPACT PACKED ROWS // DIAGNOSTIC ONLY"
    else:
        text = _base._google_sheets_summary_text(result_map[choice]).strip()
        filename = f"{choice}_gex_A6.txt"
        expected_headers = [choice]
        parser_expected = [choice]
        mode_text = f"{choice} // GOOGLE APPS SCRIPT TICKER BLOCK"

    byte_count = len(text.encode("utf-8"))
    headers = _pine_router_headers(text)
    missing_headers = [ticker for ticker in expected_headers if ticker not in headers]
    pine_issues, parsed_counts = _pine_master_issues(text, parser_expected)
    too_large = byte_count > _PINE_TEXT_LIMIT
    transport_ok = not missing_headers and not pine_issues and not too_large

    st.caption(
        "TRADINGVIEW BRIDGE // "
        + mode_text
        + f" // {len(headers)}/{len(expected_headers)} HEADERS // {byte_count:,}/{_PINE_TEXT_LIMIT:,} CHARS"
    )

    if is_master:
        if missing_headers:
            st.error("MASTER A6 HEADER CHECK FAILED // " + ", ".join(missing_headers[:16]))
        elif pine_issues:
            st.error("MASTER A6 PINE PARSER CHECK FAILED // " + ", ".join(pine_issues[:16]))
        elif too_large:
            st.warning(
                f"MASTER A6 IS {byte_count:,} CHARS // ABOVE {_PINE_TEXT_LIMIT:,}; THE BLOCK REMAINS COPYABLE, "
                "BUT TRADINGVIEW MAY TRUNCATE IT. USE COMPACT PINE ONLY IF THAT ACTUALLY HAPPENS."
            )
        elif unavailable:
            st.warning(
                f"MASTER A6 READY // {len(available)} GEX DATA BLOCKS // {len(unavailable)} ERROR BLOCKS // "
                "FAILED TICKERS ARE KEPT AS Ticker:/ERROR: JUST LIKE THE SUPPLIED GOOGLE APPS SCRIPT."
            )
        elif transport_ok:
            min_rows = min(parsed_counts.values()) if parsed_counts else 0
            max_rows = max(parsed_counts.values()) if parsed_counts else 0
            st.success(
                f"MASTER A6 READY // {len(available)}/{len(saved)} TICKERS HAVE GEX // "
                f"{min_rows}-{max_rows} PACKED ROWS EACH"
            )
    elif is_compact:
        if transport_ok:
            st.success(
                f"COMPACT PINE CHECK PASS // {len(available)} SUCCESSFUL TICKERS // DIAGNOSTIC ONLY"
            )
        else:
            details = pine_issues or missing_headers or (["TEXT_LIMIT"] if too_large else [])
            st.error("COMPACT PINE CHECK FAILED // " + ", ".join(details[:12]))
    elif transport_ok:
        st.success(f"{choice} // PINE ROUTER TEST PASS // {parsed_counts.get(choice, 0)} PACKED ROWS")
    else:
        details = pine_issues or missing_headers or (["TEXT_LIMIT"] if too_large else [])
        st.error(f"{choice} // PINE ROUTER TEST FAILED // " + ", ".join(details[:12]))

    verify_ticker = st.selectbox(
        "PINE CHART TICKER CHECK",
        saved,
        key="gexv3_pine_chart_ticker_check",
        help="Pick the same symbol as your TradingView chart. Failed/no-data tickers can stay in MASTER A6 as ERROR blocks.",
    )
    master_text = _google_sheets_master_text(result_map, saved, normalized_failures)
    if verify_ticker not in available:
        error_text = normalized_failures.get(
            verify_ticker,
            "No refreshed GEX result available.",
        )
        st.warning(
            f"{verify_ticker} // NO GEX DATA IN THIS RUN // MASTER A6 STILL CONTAINS ITS Ticker:/ERROR: BLOCK // "
            + " ".join(str(error_text).split())[:180]
        )
    else:
        target_issues, target_count = _pine_ticker_issues(master_text, verify_ticker)
        if target_issues:
            st.error(f"{verify_ticker} // PINE TARGET FAIL // " + ", ".join(target_issues))
        else:
            st.success(f"{verify_ticker} // PINE TARGET PASS // {target_count} DRAWABLE PACKED ROWS")

    st.caption(
        "MASTER A6 NOW MIRRORS THE SUPPLIED GOOGLE APPS SCRIPT: Ticker/Mode/Spot/DTE/Contracts/Net GEX/Source, "
        "THEN THE PINE INSTRUCTION + PACKED ROWS. FAILED SYMBOLS STAY AS Ticker:/ERROR: BLOCKS. "
        "PASTE THE ENTIRE MASTER A6 INTO GEX TEST → PACKED GAMMA LEVELS."
    )

    block_name = "MASTER A6 BLOCK" if is_master else "A6 / PINE BLOCK"
    if is_master:
        st.markdown(
            "**MASTER A6 BLOCK // GOOGLE APPS SCRIPT FORMAT // CLICK COPY MASTER A6 IN THE TOP-RIGHT**"
        )
    else:
        st.markdown(f"**{block_name} // USE THE ORANGE COPY BUTTON IN THE TOP-RIGHT OF THE BLOCK**")
    st.html(_TRADINGVIEW_CODE_CSS)
    with st.container(key="gexv3_bridge_code"):
        st.code(text or "", language=None, wrap_lines=False)
    st.download_button(
        "DOWNLOAD MASTER A6" if is_master else "DOWNLOAD PACKED GAMMA BLOCK",
        data=text,
        file_name=filename,
        mime="text/plain",
        width="stretch",
        disabled=not bool(text.strip()),
        key="gexv3_download_bridge",
    )


# ==============================
# PUBLIC GEX RENDERER
# ==============================
def render_gex(
    client: Any,
    vault_key: str,
    touch_session: Any,
    *,
    background_client_factory: Callable[[], Any] | None = None,
) -> None:
    """Render stable GEX v3 with non-blocking refresh-all and row enhancements."""
    vault_key = str(vault_key or "default")
    _consume_delete_request(vault_key)
    _sync_background_results(vault_key)

    # CSS must exist before the animated status element is rendered.
    st.html(_ROW_ACTION_CSS)
    _render_background_status(vault_key)

    original_markdown = st.markdown
    original_button = st.button
    original_tradingview = _base._render_tradingview
    start_requested = {"value": False}

    def row_action_markdown(body: Any, *args: Any, **kwargs: Any):
        if isinstance(body, str) and 'class="gexv3-summary"' in body:
            body = _decorate_overview(body, vault_key)
        return original_markdown(body, *args, **kwargs)

    def background_button(label: Any, *args: Any, **kwargs: Any):
        if kwargs.get("key") != "gexv3_refresh_all":
            return original_button(label, *args, **kwargs)

        if background_client_factory is None:
            # Safe fallback: preserve the legacy synchronous behavior if a
            # dedicated background client cannot be created.
            return original_button(label, *args, **kwargs)

        job = _background_job(vault_key)
        if job and job.get("status") in {"QUEUED", "RUNNING"}:
            kwargs["disabled"] = True
            label = f"↻ GEX {job['workers']}-WAY {job['completed']}/{job['total']}"
        clicked = original_button(label, *args, **kwargs)
        if clicked:
            start_requested["value"] = True
            # Return False so the preserved base renderer does NOT enter its
            # synchronous multi-ticker refresh loop.
            return False
        return clicked

    def tradingview_renderer(state: dict[str, Any], result_map: dict[str, Any]) -> None:
        job = _background_job(vault_key) or {}
        failures = dict(job.get("failures") or {})
        _render_tradingview_pine(state, result_map, failures)

    st.markdown = row_action_markdown
    st.button = background_button
    _base._render_tradingview = tradingview_renderer
    try:
        _base.render_gex(client, vault_key, touch_session)
    finally:
        _base._render_tradingview = original_tradingview
        st.button = original_button
        st.markdown = original_markdown

    if start_requested["value"]:
        state_snapshot = copy.deepcopy(
            st.session_state.get("_gex_state") or _base.core.DEFAULT_STATE
        )
        started = _start_background_refresh(
            vault_key,
            state_snapshot,
            background_client_factory,
        )
        if started:
            if callable(touch_session):
                try:
                    touch_session()
                except Exception:
                    pass
            st.toast("4-WAY BACKGROUND GEX REFRESH STARTED // switch tabs and keep working")
            st.rerun()


__all__ = ["render_gex", "background_refresh_status"]
