"""Production GEX UI interaction layer.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- row-level GEX watchlist actions layered onto the stable GEX v3 UI;
- non-blocking/background GEX refresh-all interaction;
- small interaction adapters that must not disturb GEX calculations.

DO NOT EDIT THIS FILE FOR:
- Risk Sizing, OAuth, Holdings, navigation, or shared authentication;
- GEX calculation formulas (owned by ``src.gex_ui``);
- the stable bulk of the GEX v3 renderer (preserved in ``src.gex_ui_v3_base``).

This file intentionally stays small. The proven GEX v3 implementation is kept
in ``src.gex_ui_v3_base.py``; this layer adds requested interaction behavior and
delegates the analytics/layout renderer unchanged.
"""

from __future__ import annotations

import copy
import html
import re
import threading
import time
from typing import Any, Callable
from urllib.parse import urlencode

import streamlit as st

from src import gex_ui_v3_base as _base


# ==============================
# BACKGROUND REFRESH-ALL ENGINE
# ==============================
# IMPORTANT: Worker threads must never call Streamlit APIs or touch
# st.session_state. The worker receives a dedicated E*TRADE client factory made
# from a main-thread credential/token snapshot and writes only to this
# thread-safe process-memory job registry. Completed results are merged into the
# normal GEX result vault later from the Streamlit render thread.
_BACKGROUND_LOCK = threading.RLock()
_BACKGROUND_JOBS: dict[str, dict[str, Any]] = {}


def _background_job(vault_key: str) -> dict[str, Any] | None:
    with _BACKGROUND_LOCK:
        job = _BACKGROUND_JOBS.get(str(vault_key or "default"))
        if not job:
            return None
        return {
            "status": str(job.get("status") or ""),
            "total": int(job.get("total", 0) or 0),
            "completed": int(job.get("completed", 0) or 0),
            "updated": int(job.get("updated", 0) or 0),
            "current": str(job.get("current") or ""),
            "failures": dict(job.get("failures") or {}),
            "started_at": float(job.get("started_at", 0.0) or 0.0),
            "finished_at": float(job.get("finished_at", 0.0) or 0.0),
        }


def _background_running(vault_key: str) -> bool:
    snapshot = _background_job(vault_key)
    return bool(snapshot and snapshot.get("status") in {"QUEUED", "RUNNING"})


def _run_background_refresh(
    vault_key: str,
    state_snapshot: dict[str, Any],
    tickers: list[str],
    client_factory: Callable[[], Any],
) -> None:
    """Refresh a stable ticker/settings snapshot without using Streamlit APIs."""
    key = str(vault_key or "default")
    try:
        client = client_factory()
        if client is None:
            raise RuntimeError("E*TRADE background client is unavailable")
    except Exception as exc:
        with _BACKGROUND_LOCK:
            job = _BACKGROUND_JOBS.get(key)
            if job is not None:
                job["status"] = "FAILED"
                job["failures"]["E*TRADE"] = str(exc)[:500]
                job["finished_at"] = time.time()
        return

    with _BACKGROUND_LOCK:
        job = _BACKGROUND_JOBS.get(key)
        if job is not None:
            job["status"] = "RUNNING"

    for index, ticker in enumerate(tickers, 1):
        with _BACKGROUND_LOCK:
            job = _BACKGROUND_JOBS.get(key)
            if job is None:
                return
            job["current"] = ticker

        try:
            dte = int(
                state_snapshot.get("dte_overrides", {}).get(
                    ticker,
                    state_snapshot["global_dte"],
                )
            )
            result = _base.core._build_gex(
                client,
                ticker,
                dte,
                state_snapshot["timezone"],
                state_snapshot["wall_value_mode"],
                force_refresh=True,
            )
        except Exception as exc:
            with _BACKGROUND_LOCK:
                job = _BACKGROUND_JOBS.get(key)
                if job is not None:
                    job["failures"][ticker] = str(exc)[:500]
        else:
            with _BACKGROUND_LOCK:
                job = _BACKGROUND_JOBS.get(key)
                if job is not None:
                    job["results"][ticker] = result
                    job["updated"] = len(job["results"])
        finally:
            with _BACKGROUND_LOCK:
                job = _BACKGROUND_JOBS.get(key)
                if job is not None:
                    job["completed"] = index

    with _BACKGROUND_LOCK:
        job = _BACKGROUND_JOBS.get(key)
        if job is not None:
            job["current"] = ""
            job["status"] = "DONE_WITH_ERRORS" if job["failures"] else "DONE"
            job["finished_at"] = time.time()


def _start_background_refresh(
    vault_key: str,
    state_snapshot: dict[str, Any],
    client_factory: Callable[[], Any],
) -> bool:
    """Start at most one refresh-all worker for a GEX vault."""
    key = str(vault_key or "default")
    tickers = [
        _base.core._normalize_ticker(value)
        for value in state_snapshot.get("tickers", [])
        if _base.core._normalize_ticker(value)
    ]
    if not tickers:
        return False

    with _BACKGROUND_LOCK:
        existing = _BACKGROUND_JOBS.get(key)
        if existing and existing.get("status") in {"QUEUED", "RUNNING"}:
            return False
        _BACKGROUND_JOBS[key] = {
            "status": "QUEUED",
            "total": len(tickers),
            "completed": 0,
            "updated": 0,
            "current": "",
            "failures": {},
            "results": {},
            "synced": set(),
            "started_at": time.time(),
            "finished_at": 0.0,
        }

    worker = threading.Thread(
        target=_run_background_refresh,
        args=(key, copy.deepcopy(state_snapshot), list(tickers), client_factory),
        name="raj-gex-refresh-all",
        daemon=True,
    )
    worker.start()
    return True


def _sync_background_results(vault_key: str) -> int:
    """Merge newly completed worker results into the normal GEX vault."""
    key = str(vault_key or "default")
    pending: dict[str, Any] = {}
    with _BACKGROUND_LOCK:
        job = _BACKGROUND_JOBS.get(key)
        if not job:
            return 0
        synced = job.setdefault("synced", set())
        for ticker, result in (job.get("results") or {}).items():
            if ticker not in synced:
                pending[ticker] = copy.deepcopy(result)
        synced.update(pending)

    if not pending:
        return 0
    result_map = _base.core._results(key)
    result_map.update(pending)
    return len(pending)


def _render_background_status(vault_key: str) -> None:
    """Show a compact status line only when a background job exists."""
    _sync_background_results(vault_key)
    job = _background_job(vault_key)
    if not job:
        return

    status = job["status"]
    if status in {"QUEUED", "RUNNING"}:
        current = f" // {job['current']}" if job["current"] else ""
        st.caption(
            f"BACKGROUND GEX // {job['completed']}/{job['total']} PROCESSED // "
            f"{job['updated']} UPDATED{current} // YOU CAN SWITCH TABS WHILE THIS RUNS"
        )
        return

    failures = len(job["failures"])
    if status == "DONE":
        st.caption(
            f"BACKGROUND GEX COMPLETE // {job['updated']}/{job['total']} UPDATED"
        )
    elif status == "DONE_WITH_ERRORS":
        st.caption(
            f"BACKGROUND GEX COMPLETE // {job['updated']}/{job['total']} UPDATED // "
            f"{failures} FAILED"
        )
    elif status == "FAILED":
        st.caption("BACKGROUND GEX FAILED // reconnect E*TRADE and retry")


# ==============================
# ROW-LEVEL DELETE ACTION
# ==============================
_ROW_ACTION_CSS = """
<style>
/* Keep the delete affordance inside the TICKER cell, aligned left beside symbol. */
.gexv3-summary td.sym {
    overflow: visible !important;
    text-align: left !important;
    padding-left: .48rem !important;
}
.gexv3-symbol-wrap {
    display:inline-flex !important;
    align-items:center !important;
    justify-content:flex-start !important;
    gap:.38rem !important;
    width:100% !important;
    white-space:nowrap !important;
}
.gexv3-symbol-text {
    color:#4af6c3 !important;
    font-weight:900 !important;
}
.gexv3-trash-link {
    display:inline-flex !important;
    align-items:center !important;
    justify-content:center !important;
    flex:0 0 auto !important;
    width:1.25rem !important;
    height:1.18rem !important;
    padding:0 !important;
    margin:0 !important;
    border:1px solid #5d3605 !important;
    background:#050505 !important;
    color:#fb8b1e !important;
    -webkit-text-fill-color:#fb8b1e !important;
    text-decoration:none !important;
    font-size:.72rem !important;
    line-height:1 !important;
    cursor:pointer !important;
}
.gexv3-trash-link:hover {
    border-color:#ff433d !important;
    color:#ff433d !important;
    -webkit-text-fill-color:#ff433d !important;
    background:#160606 !important;
}
</style>
"""


def _delete_href(ticker: str) -> str:
    """Build a same-page delete URL while preserving unrelated query state."""
    params: dict[str, Any] = {}
    try:
        for key in st.query_params:
            values = st.query_params.get_all(key)
            params[key] = values if len(values) > 1 else (values[0] if values else "")
    except Exception:
        params = {}
    params["gex_delete"] = ticker
    return "?" + urlencode(params, doseq=True)


def _inject_row_trash(markup: str) -> str:
    """Place one left-aligned clickable trash icon inside every ticker cell."""
    if 'class="gexv3-summary"' not in markup:
        return markup

    def replace_symbol(match: re.Match[str]) -> str:
        ticker = html.unescape(match.group(1)).strip().upper()
        ticker_html = html.escape(ticker)
        href = html.escape(_delete_href(ticker), quote=True)
        return (
            '<td class="sym">'
            '<span class="gexv3-symbol-wrap">'
            f'<a class="gexv3-trash-link" href="{href}" target="_self" '
            f'aria-label="Delete {ticker_html} from GEX" '
            f'title="Delete {ticker_html} from GEX">🗑</a>'
            f'<span class="gexv3-symbol-text">{ticker_html}</span>'
            '</span>'
            '</td>'
        )

    return re.sub(
        r'<td class="sym">([^<]+)</td>',
        replace_symbol,
        markup,
    )


def _consume_delete_request(vault_key: str) -> None:
    """Persist a row-trash request, clear only that query parameter, and rerun."""
    try:
        raw = st.query_params.get("gex_delete")
    except Exception:
        raw = None
    ticker = _base.core._normalize_ticker(raw)
    if not ticker:
        return

    state = copy.deepcopy(_base.core._load_state(str(vault_key or "default")))
    result_map = _base.core._results(str(vault_key or "default"))
    if ticker in state.get("tickers", []):
        _base._remove_ticker(str(vault_key or "default"), state, result_map, ticker)

    try:
        del st.query_params["gex_delete"]
    except Exception:
        pass
    st.rerun()


# ==============================
# PUBLIC GEX RENDERER
# ==============================
def render_gex(
    client: Any,
    vault_key: str,
    touch_session: Any,
    *,
    background_client_factory: Callable[[], Any] | None = None,
) -> None:
    """Render stable GEX v3 with non-blocking refresh-all and row delete actions."""
    vault_key = str(vault_key or "default")
    _consume_delete_request(vault_key)
    _sync_background_results(vault_key)
    _render_background_status(vault_key)
    st.html(_ROW_ACTION_CSS)

    original_markdown = st.markdown
    original_button = st.button
    start_requested = {"value": False}

    def row_action_markdown(body: Any, *args: Any, **kwargs: Any):
        if isinstance(body, str) and 'class="gexv3-summary"' in body:
            body = _inject_row_trash(body)
        return original_markdown(body, *args, **kwargs)

    def background_button(label: Any, *args: Any, **kwargs: Any):
        if kwargs.get("key") != "gexv3_refresh_all":
            return original_button(label, *args, **kwargs)

        if background_client_factory is None:
            # Safe fallback: preserve the legacy synchronous behavior if a
            # dedicated background client cannot be created.
            return original_button(label, *args, **kwargs)

        job = _background_job(vault_key)
        if job and job.get("status") in {"QUEUED", "RUNNING"}:
            kwargs["disabled"] = True
            label = f"GEX RUNNING {job['completed']}/{job['total']}"
        clicked = original_button(label, *args, **kwargs)
        if clicked:
            start_requested["value"] = True
            # Return False so the preserved base renderer does NOT enter its
            # synchronous 49-ticker refresh loop.
            return False
        return clicked

    st.markdown = row_action_markdown
    st.button = background_button
    try:
        _base.render_gex(client, vault_key, touch_session)
    finally:
        st.button = original_button
        st.markdown = original_markdown

    if start_requested["value"]:
        state_snapshot = copy.deepcopy(
            st.session_state.get("_gex_state") or _base.core.DEFAULT_STATE
        )
        started = _start_background_refresh(
            vault_key,
            state_snapshot,
            background_client_factory,
        )
        if started:
            if callable(touch_session):
                try:
                    touch_session()
                except Exception:
                    pass
            st.toast("BACKGROUND GEX REFRESH STARTED // switch tabs and keep working")
            st.rerun()


__all__ = ["render_gex"]
