"""Production GEX terminal wrapper for Raj's Terminal.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE ONLY for:
- obtaining the live E*TRADE client for GEX;
- resolving the terminal vault/session context;
- building a dedicated background E*TRADE client snapshot for GEX refresh-all;
- GEX-only background market-data caching/session plumbing;
- GEX-only wrapper CSS emitted while the GEX tab renders;
- keeping GEX style-only CSS out of Streamlit's visible vertical stack.

DO NOT edit this file for:
- Risk Sizing;
- OAuth layout;
- Holdings;
- top-level terminal navigation;
- GEX tables/subtabs/analytics themselves (edit `src/gex_ui_v3.py`).

IMPORTANT: this module must NOT monkey-patch Streamlit at module import time.
Any temporary wrapper must exist only inside `render_gex()` and must always be
restored in `finally`.
"""

from __future__ import annotations

import hashlib
import inspect
import sys
import threading
import time
from typing import Any, Callable

import streamlit as st

from src.etrade_client import ETradeClient
from src.gex_ui_v3 import render_gex as _render_gex_v3


# ==============================
# GEX-ONLY CSS
# ==============================

def _gex_subtab_skin_css() -> str:
    """Return GEX navigation/control CSS as style-only HTML.

    This stylesheet is emitted on every GEX render so the controls do not rely
    on process-global theme state. Streamlit's global ``textColor`` is black to
    support black dataframe-header text on orange, so every GEX select value and
    menu option is explicitly recolored here for dark-background readability.
    """
    return """
        <style>
        /* GEX SECONDARY NAVIGATION */
        div[data-testid="stTabs"] > div[data-baseweb="tab-list"] {
            gap: .42rem !important;
            padding: .34rem 0 .48rem 0 !important;
            margin: .20rem 0 .58rem 0 !important;
            border-bottom: 1px solid #fb8b1e !important;
            overflow-x: visible !important;
            flex-wrap: wrap !important;
        }

        div[data-testid="stTabs"] button[role="tab"] {
            flex: 0 0 auto !important;
            min-width: 118px !important;
            min-height: 38px !important;
            padding: .46rem .82rem !important;
            margin: 0 !important;
            border: 1px solid #fb8b1e !important;
            border-radius: 0 !important;
            background: #050505 !important;
            color: #fb8b1e !important;
            box-shadow: none !important;
            font-family: "Courier New", monospace !important;
            font-size: .74rem !important;
            font-weight: 900 !important;
            letter-spacing: .02em !important;
            text-transform: uppercase !important;
        }

        div[data-testid="stTabs"] button[role="tab"]:hover {
            background: #171007 !important;
            color: #ffad52 !important;
        }

        div[data-testid="stTabs"] button[role="tab"][aria-selected="true"] {
            background: #fb8b1e !important;
            color: #000000 !important;
            border-color: #fb8b1e !important;
            box-shadow: inset 0 -3px 0 #a64b00 !important;
        }

        div[data-testid="stTabs"] button[role="tab"] * {
            color: inherit !important;
            font-family: "Courier New", monospace !important;
            font-weight: 900 !important;
        }

        div[data-testid="stTabs"] div[data-baseweb="tab-highlight"] {
            display: none !important;
        }

        div[data-testid="stTabs"] div[data-baseweb="tab-panel"] {
            padding-top: .22rem !important;
        }

        /* GEX SELECTBOX SHELL + SELECTED VALUE */
        div[data-testid="stSelectbox"] div[data-baseweb="select"] > div,
        div[data-testid="stSelectbox"] div[data-baseweb="select"] > div > div,
        div[data-testid="stSelectbox"] [role="combobox"] {
            background:#050505 !important;
            border-color:#fb8b1e !important;
            color:#fb8b1e !important;
            -webkit-text-fill-color:#fb8b1e !important;
            box-shadow:none !important;
        }

        div[data-testid="stSelectbox"] div[data-baseweb="select"] > div *,
        div[data-testid="stSelectbox"] div[data-baseweb="select"] span,
        div[data-testid="stSelectbox"] div[data-baseweb="select"] p,
        div[data-testid="stSelectbox"] div[data-baseweb="select"] input,
        div[data-testid="stSelectbox"] [role="combobox"] * {
            color:#fb8b1e !important;
            -webkit-text-fill-color:#fb8b1e !important;
            font-family:"Courier New",monospace !important;
            font-weight:800 !important;
            opacity:1 !important;
        }

        div[data-testid="stSelectbox"] div[data-baseweb="select"] svg {
            color:#fb8b1e !important;
            fill:#fb8b1e !important;
        }

        /*
           BaseWeb mounts the OPEN dropdown menu in a portal outside the
           stSelectbox DOM. Target every listbox/menu option descendant so a
           nested div/span cannot inherit Streamlit's black global text color.
        */
        div[data-baseweb="popover"],
        div[data-baseweb="popover"] [role="listbox"],
        div[data-baseweb="popover"] [data-baseweb="menu"],
        div[data-baseweb="menu"],
        [role="listbox"] {
            background:#050505 !important;
            color:#f2f2f2 !important;
        }

        div[data-baseweb="popover"] [role="listbox"],
        div[data-baseweb="popover"] [data-baseweb="menu"] {
            border:1px solid #fb8b1e !important;
        }

        div[data-baseweb="popover"] [role="option"],
        div[data-baseweb="popover"] [role="option"] *,
        div[data-baseweb="menu"] [role="option"],
        div[data-baseweb="menu"] [role="option"] *,
        [role="listbox"] [role="option"],
        [role="listbox"] [role="option"] * {
            background:#050505 !important;
            color:#f2f2f2 !important;
            -webkit-text-fill-color:#f2f2f2 !important;
            font-family:"Courier New",monospace !important;
            font-weight:800 !important;
            opacity:1 !important;
        }

        div[data-baseweb="popover"] [role="option"]:hover,
        div[data-baseweb="popover"] [role="option"]:focus,
        div[data-baseweb="menu"] [role="option"]:hover,
        div[data-baseweb="menu"] [role="option"]:focus,
        [role="listbox"] [role="option"]:hover,
        [role="listbox"] [role="option"]:focus {
            background:#171007 !important;
            color:#ffad52 !important;
            -webkit-text-fill-color:#ffad52 !important;
        }

        div[data-baseweb="popover"] [role="option"][aria-selected="true"],
        div[data-baseweb="popover"] [role="option"][aria-selected="true"] *,
        div[data-baseweb="menu"] [role="option"][aria-selected="true"],
        div[data-baseweb="menu"] [role="option"][aria-selected="true"] *,
        [role="listbox"] [role="option"][aria-selected="true"],
        [role="listbox"] [role="option"][aria-selected="true"] * {
            background:#fb8b1e !important;
            color:#000000 !important;
            -webkit-text-fill-color:#000000 !important;
        }
        </style>
    """


def _is_style_only_markdown(body: Any) -> bool:
    """Return True only for a standalone <style>...</style> markdown body."""
    if not isinstance(body, str):
        return False
    stripped = body.strip()
    return stripped.startswith("<style>") and stripped.endswith("</style>")


# ==============================
# BACKGROUND MARKET-DATA CACHE
# ==============================
# The original terminal routes live E*TRADE reads through a short-lived smart
# cache. The detached GEX worker cannot safely call that Streamlit/session-aware
# wrapper from a background thread, so keep an equivalent GEX-only process cache
# here. This restores the original fast behavior without touching Streamlit from
# worker threads and without changing GEX formulas.
#
# These TTLs intentionally match the terminal's shared E*TRADE cache:
# - quotes: 5 seconds
# - expiration metadata: 6 hours
# - option chains: 5 minutes
_GEX_BACKGROUND_TTLS = {
    "quote": 5,
    "option_expirations": 6 * 60 * 60,
    "option_chain": 5 * 60,
}
_GEX_BACKGROUND_CACHE_RETENTION = 24 * 60 * 60
_GEX_BACKGROUND_CACHE_LIMIT = 1200
_GEX_BACKGROUND_CACHE_LOCK = threading.RLock()
_GEX_BACKGROUND_CACHE: dict[tuple[str, str, str], dict[str, Any]] = {}


def _gex_cache_namespace(oauth_token: str) -> str:
    """Return a non-reversible namespace; never put the OAuth token in cache keys."""
    return hashlib.sha256(str(oauth_token).encode("utf-8")).hexdigest()[:32]


def _prune_gex_background_cache(namespace: str, now: float) -> None:
    keys = [key for key in _GEX_BACKGROUND_CACHE if key[0] == namespace]
    for key in keys:
        loaded_at = float(_GEX_BACKGROUND_CACHE[key].get("loaded_at", 0.0) or 0.0)
        if now - loaded_at > _GEX_BACKGROUND_CACHE_RETENTION:
            _GEX_BACKGROUND_CACHE.pop(key, None)

    keys = [key for key in _GEX_BACKGROUND_CACHE if key[0] == namespace]
    if len(keys) <= _GEX_BACKGROUND_CACHE_LIMIT:
        return
    keys.sort(
        key=lambda key: float(
            _GEX_BACKGROUND_CACHE[key].get("loaded_at", 0.0) or 0.0
        )
    )
    for key in keys[: len(keys) - _GEX_BACKGROUND_CACHE_LIMIT]:
        _GEX_BACKGROUND_CACHE.pop(key, None)


def _gex_cached_market_read(
    namespace: str,
    resource_type: str,
    resource_key: str,
    loader: Callable[[], Any],
) -> Any:
    """Return fresh cached market data or load it once from E*TRADE.

    If a live request fails after a prior successful load, keep the last-known
    payload available to the background calculation instead of losing the whole
    ticker. This mirrors the terminal's existing stale-safe cache behavior.
    """
    ttl = int(_GEX_BACKGROUND_TTLS[resource_type])
    now = time.time()
    key = (namespace, resource_type, str(resource_key))
    stale_value: Any = None

    with _GEX_BACKGROUND_CACHE_LOCK:
        _prune_gex_background_cache(namespace, now)
        entry = _GEX_BACKGROUND_CACHE.get(key)
        if entry is not None:
            stale_value = entry.get("value")
            age = now - float(entry.get("loaded_at", 0.0) or 0.0)
            if age < ttl:
                return stale_value

    try:
        value = loader()
    except Exception:
        if stale_value is not None:
            return stale_value
        raise

    with _GEX_BACKGROUND_CACHE_LOCK:
        _GEX_BACKGROUND_CACHE[key] = {
            "loaded_at": time.time(),
            "value": value,
        }
        _prune_gex_background_cache(namespace, time.time())
    return value


class _GEXBackgroundCachedClient:
    """Thread-safe cache-aware market client used only by GEX Refresh All.

    ``core._build_gex(..., force_refresh=True)`` historically meant that every
    refresh-all pass bypassed the terminal cache. For a 49-ticker watchlist that
    can cause hundreds of duplicate option-chain requests. This adapter accepts
    the force-refresh keyword for compatibility but intentionally treats Refresh
    All as "ensure data is fresh within the terminal TTL". A manual single-ticker
    refresh still uses the foreground client and retains its existing hard-refresh
    behavior.
    """

    def __init__(self, client: ETradeClient, namespace: str) -> None:
        self._client = client
        self._namespace = namespace

    def get_quote(self, symbol: str, force_refresh: bool = False) -> dict[str, Any]:
        symbol = str(symbol).strip().upper()
        return _gex_cached_market_read(
            self._namespace,
            "quote",
            symbol,
            lambda: self._client.get_quote(symbol),
        )

    def get_option_expirations(
        self,
        symbol: str,
        force_refresh: bool = False,
    ) -> dict[str, Any]:
        symbol = str(symbol).strip().upper()
        return _gex_cached_market_read(
            self._namespace,
            "option_expirations",
            symbol,
            lambda: self._client.get_option_expirations(symbol),
        )

    def get_option_chain(
        self,
        symbol: str,
        expiry_year: int,
        expiry_month: int,
        expiry_day: int,
        no_of_strikes: int | None = 100,
        chain_type: str = "CALLPUT",
        force_refresh: bool = False,
    ) -> dict[str, Any]:
        symbol = str(symbol).strip().upper()
        strikes_key = "ALL" if no_of_strikes is None else str(int(no_of_strikes))
        chain_type = str(chain_type).upper()
        resource_key = (
            f"{symbol}:{int(expiry_year):04d}-{int(expiry_month):02d}-{int(expiry_day):02d}:"
            f"{chain_type}:{strikes_key}"
        )
        return _gex_cached_market_read(
            self._namespace,
            "option_chain",
            resource_key,
            lambda: self._client.get_option_chain(
                symbol,
                int(expiry_year),
                int(expiry_month),
                int(expiry_day),
                no_of_strikes=no_of_strikes,
                chain_type=chain_type,
            ),
        )


# ==============================
# E*TRADE / TERMINAL CONTEXT
# ==============================

def _background_client_factory(scope: dict[str, Any]) -> Callable[[], Any] | None:
    """Capture a cache-aware thread-safe E*TRADE client factory.

    Background workers must not read ``st.session_state`` or call terminal
    helpers after the worker starts. Capture credential/token strings and the
    non-reversible cache namespace here, then create fresh OAuth sessions inside
    worker threads. Market payloads are shared only through the GEX process cache
    above; credentials/tokens are never written to that cache.
    """
    credentials_factory = scope.get("_etrade_credentials")
    if not callable(credentials_factory):
        return None

    try:
        consumer_key, consumer_secret, environment = credentials_factory()
    except Exception:
        return None

    token = st.session_state.get("etrade_access_token") or {}
    oauth_token = str(token.get("oauth_token") or "").strip()
    oauth_secret = str(token.get("oauth_token_secret") or "").strip()
    consumer_key = str(consumer_key or "").strip()
    consumer_secret = str(consumer_secret or "").strip()
    environment = str(environment or "live").strip() or "live"

    if not (consumer_key and consumer_secret and oauth_token and oauth_secret):
        return None

    cache_namespace = _gex_cache_namespace(oauth_token)

    def build_client(
        _consumer_key: str = consumer_key,
        _consumer_secret: str = consumer_secret,
        _oauth_token: str = oauth_token,
        _oauth_secret: str = oauth_secret,
        _environment: str = environment,
        _cache_namespace: str = cache_namespace,
    ) -> _GEXBackgroundCachedClient:
        raw = ETradeClient(
            _consumer_key,
            _consumer_secret,
            _oauth_token,
            _oauth_secret,
            _environment,
        )
        return _GEXBackgroundCachedClient(raw, _cache_namespace)

    return build_client


def _discover_terminal_context() -> tuple[Any, str, Any, Callable[[], Any] | None]:
    """Resolve live GEX context plus a dedicated background-client factory."""
    candidates: list[dict[str, Any]] = []
    main = sys.modules.get("__main__")
    if main is not None:
        candidates.append(vars(main))
    for frame in inspect.stack()[1:18]:
        candidates.append(frame.frame.f_globals)

    for scope in candidates:
        live_factory = scope.get("_live_etrade_client")
        factory = live_factory if callable(live_factory) else scope.get("_etrade_client")
        hash_fn = scope.get("_trade_access_code_hash")
        touch = scope.get("_touch_etrade_session")
        if not callable(factory):
            continue

        try:
            client = factory()
        except Exception:
            client = None
        try:
            vault_key = str(hash_fn()) if callable(hash_fn) else "default"
        except Exception:
            vault_key = "default"
        return (
            client,
            vault_key or "default",
            touch,
            _background_client_factory(scope),
        )

    return None, "default", None, None


# ==============================
# SAFE GEX RENDER BRIDGE
# ==============================

def _render_with_style_only_html(
    client: Any,
    vault_key: str,
    touch: Any,
    background_client_factory: Callable[[], Any] | None,
) -> None:
    """Render GEX while routing only style-only markdown through ``st.html``.

    `src.gex_ui_v3_base.py` emits its feature CSS with a standalone
    ``st.markdown(<style>...</style>)`` call. For GEX only, route that exact
    style-only case through ``st.html`` so Streamlit applies it without adding
    a visible layout row. All normal markdown is passed through unchanged.

    This intentionally does NOT concatenate CSS with visible content and does
    NOT use negative margins. The original ``st.markdown`` is always restored.
    """
    original_markdown = st.markdown

    def gex_markdown(body: Any, *args: Any, **kwargs: Any):
        if _is_style_only_markdown(body):
            st.html(str(body))
            return None
        return original_markdown(body, *args, **kwargs)

    st.markdown = gex_markdown
    try:
        _render_gex_v3(
            client,
            vault_key,
            touch,
            background_client_factory=background_client_factory,
        )
    finally:
        st.markdown = original_markdown


# ==============================
# PUBLIC GEX ENTRYPOINT
# ==============================

def render_gex() -> None:
    """Render GEX with non-blocking refresh-all support and compact styling."""
    client, vault_key, touch, background_factory = _discover_terminal_context()

    # Style-only HTML is applied without creating a visible Streamlit row.
    st.html(_gex_subtab_skin_css())
    _render_with_style_only_html(
        client,
        vault_key,
        touch,
        background_factory,
    )


__all__ = ["render_gex"]
