"""Pure Option Book helpers for E*TRADE option-ticket previewing.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- option-leg normalization and market-price math;
- E*TRADE PreviewOrderRequest payload construction;
- broker preview-response normalization.

DO NOT EDIT THIS FILE FOR:
- Streamlit layout/widgets (``src/option_book_ui.py`` owns those);
- OAuth/session plumbing;
- live order placement. Option Book intentionally builds PREVIEW requests only.
"""

from __future__ import annotations

import secrets
from datetime import date
from typing import Any


OPTION_ACTIONS = ("BUY_OPEN", "SELL_OPEN", "BUY_CLOSE", "SELL_CLOSE")
SINGLE_PRICE_TYPES = ("LIMIT", "STOP", "STOP_LIMIT", "MARKET")
SPREAD_PRICE_TYPES = ("NET_DEBIT", "NET_CREDIT", "MARKET")
ORDER_TERMS = ("GOOD_FOR_DAY", "GOOD_UNTIL_CANCEL")


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def _find_key(value: Any, wanted: str) -> Any:
    wanted = str(wanted).casefold()
    if isinstance(value, dict):
        for key, child in value.items():
            if str(key).casefold() == wanted:
                return child
        for child in value.values():
            found = _find_key(child, wanted)
            if found is not None:
                return found
    elif isinstance(value, list):
        for child in value:
            found = _find_key(child, wanted)
            if found is not None:
                return found
    return None


def _number(value: Any, *keys: str) -> float | None:
    for key in keys:
        child = _find_key(value, key)
        try:
            return float(child)
        except (TypeError, ValueError):
            continue
    return None


def new_client_order_id() -> str:
    """Return an E*TRADE-safe unique client order id (<=20 alphanumeric chars)."""
    return "OB" + secrets.token_hex(8).upper()


def extract_option_rows(payload: dict[str, Any], expiry: date) -> list[dict[str, Any]]:
    """Normalize an E*TRADE CALLPUT chain into one row per call/put contract."""
    rows: list[dict[str, Any]] = []
    for pair in _as_list(_find_key(payload, "OptionPair")):
        if not isinstance(pair, dict):
            continue
        for source_key, call_put in (("Call", "CALL"), ("Put", "PUT")):
            option = pair.get(source_key) or pair.get(source_key.lower())
            if not isinstance(option, dict):
                continue
            strike = _number(option, "strikePrice", "strike")
            if strike is None:
                continue
            bid = _number(option, "bid")
            ask = _number(option, "ask")
            rows.append(
                {
                    "expiry": expiry,
                    "call_put": call_put,
                    "strike": float(strike),
                    "bid": bid,
                    "ask": ask,
                    "last": _number(option, "lastPrice", "lastTrade"),
                    "volume": _number(option, "volume"),
                    "open_interest": _number(option, "openInterest"),
                    "osi": str(
                        option.get("osiKey")
                        or option.get("displaySymbol")
                        or option.get("symbol")
                        or ""
                    ),
                }
            )
    return sorted(rows, key=lambda row: (row["call_put"], row["strike"]))


def strikes_for(rows: list[dict[str, Any]], call_put: str) -> list[float]:
    wanted = str(call_put).upper()
    return sorted(
        {
            float(row["strike"])
            for row in rows
            if str(row.get("call_put")).upper() == wanted and row.get("strike") is not None
        }
    )


def contract_quote(
    rows: list[dict[str, Any]],
    call_put: str,
    strike: float,
) -> dict[str, Any] | None:
    wanted_type = str(call_put).upper()
    wanted_strike = float(strike)
    for row in rows:
        if str(row.get("call_put")).upper() != wanted_type:
            continue
        try:
            if abs(float(row.get("strike")) - wanted_strike) < 1e-8:
                return dict(row)
        except (TypeError, ValueError):
            continue
    return None


def _mid(bid: Any, ask: Any) -> float | None:
    try:
        bid_value = float(bid)
        ask_value = float(ask)
    except (TypeError, ValueError):
        return None
    if bid_value < 0 or ask_value < 0:
        return None
    return (bid_value + ask_value) / 2.0


def net_price_snapshot(legs: list[dict[str, Any]]) -> dict[str, float | str | None]:
    """Calculate natural/opposite/mid net debit using the selected leg quotes.

    Positive values are debits; negative values are credits. Natural uses ask
    for buys and bid for sells, matching executable-side conservative pricing.
    """
    natural = 0.0
    opposite = 0.0
    midpoint = 0.0
    usable = True

    for leg in legs:
        action = str(leg.get("action") or "").upper()
        try:
            qty = int(leg.get("quantity") or 0)
        except (TypeError, ValueError):
            qty = 0
        if qty <= 0 or action not in OPTION_ACTIONS:
            usable = False
            continue

        bid = leg.get("bid")
        ask = leg.get("ask")
        mid = _mid(bid, ask)
        try:
            bid_value = float(bid)
            ask_value = float(ask)
        except (TypeError, ValueError):
            usable = False
            continue
        if bid_value < 0 or ask_value < 0 or mid is None:
            usable = False
            continue

        sign = 1.0 if action.startswith("BUY") else -1.0
        natural_reference = ask_value if sign > 0 else bid_value
        opposite_reference = bid_value if sign > 0 else ask_value
        natural += sign * natural_reference * qty
        opposite += sign * opposite_reference * qty
        midpoint += sign * mid * qty

    if not usable:
        return {"natural": None, "opposite": None, "mid": None, "side": "UNKNOWN"}

    side = "DEBIT" if midpoint >= 0 else "CREDIT"
    return {
        "natural": natural,
        "opposite": opposite,
        "mid": midpoint,
        "side": side,
    }


def build_preview_payload(
    *,
    symbol: str,
    legs: list[dict[str, Any]],
    price_type: str,
    limit_price: float | None,
    stop_price: float | None,
    order_term: str,
    client_order_id: str | None = None,
) -> dict[str, Any]:
    """Build the supported E*TRADE Preview Order JSON request.

    This helper deliberately cannot build a PlaceOrderRequest.
    """
    symbol = str(symbol or "").strip().upper()
    if not symbol:
        raise ValueError("A ticker is required.")
    if not 1 <= len(legs) <= 4:
        raise ValueError("Option Book supports between 1 and 4 option legs.")

    price_type = str(price_type or "").strip().upper()
    order_term = str(order_term or "").strip().upper()
    is_spread = len(legs) > 1
    allowed_price_types = SPREAD_PRICE_TYPES if is_spread else SINGLE_PRICE_TYPES
    if price_type not in allowed_price_types:
        raise ValueError(f"{price_type or 'Price type'} is not valid for this ticket.")
    if order_term not in ORDER_TERMS:
        raise ValueError("Order duration must be DAY or GTC.")
    if is_spread and price_type in {"STOP", "STOP_LIMIT"}:
        raise ValueError("E*TRADE does not allow stop/stop-limit on multi-leg option orders.")

    instruments: list[dict[str, Any]] = []
    for leg_number, leg in enumerate(legs, start=1):
        action = str(leg.get("action") or "").upper()
        call_put = str(leg.get("call_put") or "").upper()
        expiry = leg.get("expiry")
        if action not in OPTION_ACTIONS:
            raise ValueError(f"Leg {leg_number} has an invalid action.")
        if call_put not in {"CALL", "PUT"}:
            raise ValueError(f"Leg {leg_number} must be a Call or Put.")
        if not isinstance(expiry, date):
            raise ValueError(f"Leg {leg_number} needs a valid expiration date.")
        try:
            strike = float(leg.get("strike"))
            quantity = int(leg.get("quantity"))
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Leg {leg_number} has an invalid strike or quantity.") from exc
        if strike <= 0 or quantity <= 0:
            raise ValueError(f"Leg {leg_number} strike and quantity must be positive.")

        instruments.append(
            {
                "Product": {
                    "symbol": symbol,
                    "securityType": "OPTN",
                    "callPut": call_put,
                    "expiryYear": int(expiry.year),
                    "expiryMonth": int(expiry.month),
                    "expiryDay": int(expiry.day),
                    "strikePrice": strike,
                },
                "orderAction": action,
                "orderedQuantity": quantity,
                "quantity": quantity,
            }
        )

    limit_value = 0.0
    stop_value = 0.0
    if price_type in {"LIMIT", "NET_DEBIT", "NET_CREDIT", "STOP_LIMIT"}:
        try:
            limit_value = float(limit_price)
        except (TypeError, ValueError) as exc:
            raise ValueError("Enter a valid limit price.") from exc
        if limit_value <= 0:
            raise ValueError("Limit price must be positive.")
    if price_type in {"STOP", "STOP_LIMIT"}:
        try:
            stop_value = float(stop_price)
        except (TypeError, ValueError) as exc:
            raise ValueError("Enter a valid stop price.") from exc
        if stop_value <= 0:
            raise ValueError("Stop price must be positive.")

    client_order_id = str(client_order_id or new_client_order_id()).strip()
    if not client_order_id.isalnum() or len(client_order_id) > 20:
        raise ValueError("Client order id must be <=20 alphanumeric characters.")

    order = {
        "allOrNone": False,
        "priceType": price_type,
        "limitPrice": 0.0,
        "stopPrice": round(stop_value, 4),
        "orderTerm": order_term,
        "marketSession": "REGULAR",
        "Instrument": instruments,
    }
    if price_type in {"LIMIT", "NET_DEBIT", "NET_CREDIT"}:
        order["limitPrice"] = round(limit_value, 4)
    elif price_type == "STOP_LIMIT":
        # E*TRADE's option-order schema has a distinct stopLimitPrice field.
        order["stopLimitPrice"] = round(limit_value, 4)
    return {
        "PreviewOrderRequest": {
            "orderType": "SPREADS" if is_spread else "OPTN",
            "clientOrderId": client_order_id,
            "Order": [order],
        }
    }


def preview_details(payload: dict[str, Any]) -> dict[str, Any]:
    """Return compact useful fields from an E*TRADE preview response."""
    response = _find_key(payload, "PreviewOrderResponse")
    response = response if isinstance(response, dict) else payload

    preview_ids = _as_list(_find_key(response, "PreviewIds"))
    preview_id = None
    for item in preview_ids:
        if isinstance(item, dict):
            preview_id = _find_key(item, "previewId")
        elif item is not None:
            preview_id = item
        if preview_id is not None:
            break
    if preview_id is None:
        preview_id = _find_key(response, "previewId")

    messages: list[str] = []
    raw_messages = _find_key(response, "Message")
    for message in _as_list(raw_messages):
        if isinstance(message, dict):
            description = message.get("description") or message.get("message")
            code = message.get("code")
            message_type = message.get("type")
            parts = [str(part) for part in (message_type, code, description) if part not in (None, "")]
            if parts:
                messages.append(" // ".join(parts))
        elif message not in (None, ""):
            messages.append(str(message))

    return {
        "preview_id": preview_id,
        "total_order_value": _number(response, "totalOrderValue", "estimatedTotalAmount"),
        "estimated_commission": _number(response, "estimatedCommission", "totalCommission"),
        "preview_time": _find_key(response, "previewTime"),
        "messages": messages,
    }
