"""Production UI for Raj's Terminal Option Book.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR: Option Book ticker/account selection, option legs, pricing,
local drafts, and E*TRADE broker-preview presentation.
DO NOT EDIT THIS FILE FOR: OAuth/session transport, Risk Sizing, GEX, Holdings,
navigation, the legacy Orders simulator, or live order placement.
"""

from __future__ import annotations

import html
from datetime import date, datetime
from typing import Any

import pandas as pd
import streamlit as st

from src.etrade_client import (
    ETradeError,
    find_number,
    option_expiration_dates,
    quote_summary,
    total_account_value,
)
from src.option_book import (
    build_preview_payload,
    contract_quote,
    extract_option_rows,
    net_price_snapshot,
    new_client_order_id,
    preview_details,
    strikes_for,
)
from src.ticker_autocomplete import company_name, record_lookup, smart_ticker_selector


# ==============================
# UI / CSS
# ==============================

_OPTION_BOOK_CSS = """
<style>
.ob-card{
    border:1px solid #394554;
    background:#050505;
    padding:.42rem .52rem;
    margin:.05rem 0 .34rem;
    font-family:"Courier New",monospace;
}
.ob-name{
    font-size:.76rem;
    line-height:1.15;
    font-weight:900;
    color:#b9c0ca!important;
    overflow-wrap:anywhere;
}
.ob-quote{
    display:flex;
    flex-wrap:wrap;
    gap:.18rem 1rem;
    margin-top:.16rem;
    font-size:.74rem;
    line-height:1.15;
    font-weight:900;
    color:#eee!important;
}
.ob-quote b{color:#4af6c3!important;margin-left:.18rem}
.ob-note{
    border-left:3px solid #fb8b1e;
    background:#101216;
    padding:.28rem .46rem;
    margin:.06rem 0 .34rem;
    font:.68rem/1.22 "Courier New",monospace;
    color:#c8ced8!important;
}
.ob-note strong{color:#fb8b1e!important}
.ob-leg-quote{
    border:1px solid #394554;
    background:#08090b;
    min-height:58px;
    padding:.34rem .42rem;
    display:flex;
    flex-direction:column;
    justify-content:center;
    overflow:hidden;
    font-family:"Courier New",monospace;
}
.ob-leg-quote-label{
    color:#fb8b1e!important;
    font-size:.62rem;
    line-height:1;
    font-weight:900;
    text-transform:uppercase;
    margin-bottom:.2rem;
}
.ob-leg-quote-value{
    color:#4af6c3!important;
    font-size:1rem;
    line-height:1.05;
    font-weight:900;
    white-space:nowrap;
    overflow:hidden;
    text-overflow:ellipsis;
}
.ob-price{
    border-top:1px solid #a970ff;
    padding-top:.24rem;
    margin:.28rem 0 .08rem;
    font:.73rem/1.22 "Courier New",monospace;
    font-weight:900;
    overflow-wrap:anywhere;
}
.ob-price b{color:#a970ff!important}
.ob-ticket-summary{
    border-left:2px solid #fb8b1e;
    padding:.22rem .42rem;
    margin:.16rem 0 .3rem;
    font:.72rem/1.25 "Courier New",monospace;
    color:#c07a1e!important;
    overflow-wrap:anywhere;
}
.ob-action-note{
    padding-top:.35rem;
    font:.64rem/1.2 "Courier New",monospace;
    color:#8f99a8!important;
}
.ob-preview-stats{
    display:grid;
    grid-template-columns:repeat(2,minmax(0,1fr));
    gap:.35rem;
    margin:.28rem 0;
}
.ob-preview-stat{
    border:1px solid #394554;
    background:#08090b;
    padding:.34rem .46rem;
    min-width:0;
}
.ob-preview-stat-label{
    color:#fb8b1e!important;
    font:.62rem/1 "Courier New",monospace;
    font-weight:900;
    text-transform:uppercase;
}
.ob-preview-stat-value{
    color:#4af6c3!important;
    font:.96rem/1.1 "Courier New",monospace;
    font-weight:900;
    margin-top:.18rem;
    white-space:nowrap;
    overflow:hidden;
    text-overflow:ellipsis;
}
</style>
"""

_ACTIONS = {
    "BUY_OPEN": "Buy to Open",
    "SELL_OPEN": "Sell to Open",
    "BUY_CLOSE": "Buy to Close",
    "SELL_CLOSE": "Sell to Close",
}
_PRICES = {
    "LIMIT": "Limit",
    "STOP": "Stop",
    "STOP_LIMIT": "Stop Limit",
    "MARKET": "Market",
    "NET_DEBIT": "Limit Debit",
    "NET_CREDIT": "Limit Credit",
}
_DURATIONS = {"GOOD_FOR_DAY": "DAY", "GOOD_UNTIL_CANCEL": "GTC"}
_STRATEGIES = ("Call/Put", "Call Vertical", "Put Vertical", "Custom Spread")


def _money(value: Any) -> str:
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return "—"


_DEFAULT_ACCOUNT_SUFFIX = "5474"


def _account_label(account: dict[str, Any]) -> str:
    name = str(account.get("accountDesc") or account.get("accountName") or "E*TRADE")
    ident = str(account.get("accountId") or account.get("accountIdKey") or "")
    return f"{name} // x{ident[-4:]}" if ident else name


def _account_matches_default(account: dict[str, Any]) -> bool:
    """Prefer Raj's x5474 account without overriding later manual selections."""
    for key in ("accountId", "accountDesc", "accountName", "accountIdKey"):
        raw = str(account.get(key) or "")
        digits = "".join(ch for ch in raw if ch.isdigit())
        if digits.endswith(_DEFAULT_ACCOUNT_SUFFIX):
            return True
    return False


def _default_account_index(accounts: list[dict[str, Any]]) -> int:
    return next(
        (index for index, account in enumerate(accounts) if _account_matches_default(account)),
        0,
    )


def _leg_quote_markup(label: str, value: Any) -> str:
    return (
        '<div class="ob-leg-quote">'
        '<div class="ob-leg-quote-label">' + html.escape(str(label)) + "</div>"
        '<div class="ob-leg-quote-value">' + html.escape(_money(value)) + "</div>"
        "</div>"
    )


def _date_label(expiry: date) -> str:
    return expiry.strftime("%b-%d-%y")


def _default_expiry(expirations: list[date]) -> date:
    today = date.today()
    return next((d for d in expirations if (d - today).days >= 14), expirations[0])


def _closest(strikes: list[float], spot: float, offset: int = 0) -> float:
    base = min(range(len(strikes)), key=lambda i: abs(strikes[i] - spot))
    return float(strikes[max(0, min(len(strikes) - 1, base + offset))])


def _strategy_defaults(strategy: str, symbol: str) -> None:
    signature = f"{symbol}:{strategy}"
    if st.session_state.get("_ob_strategy") == signature:
        return
    defaults = {
        "Call/Put": [("BUY_OPEN", "CALL")],
        "Call Vertical": [("BUY_OPEN", "CALL"), ("SELL_OPEN", "CALL")],
        "Put Vertical": [("BUY_OPEN", "PUT"), ("SELL_OPEN", "PUT")],
        "Custom Spread": [("BUY_OPEN", "CALL"), ("SELL_OPEN", "CALL")],
    }[strategy]
    st.session_state["ob_leg_count"] = len(defaults)
    for i, (action, call_put) in enumerate(defaults):
        st.session_state[f"ob_{i}_action"] = action
        st.session_state[f"ob_{i}_type"] = call_put
    st.session_state["_ob_strategy"] = signature
    st.session_state.pop("_ob_price_seed", None)


def _add_leg() -> None:
    count = int(st.session_state.get("ob_leg_count", 1) or 1)
    if count >= 4:
        return
    st.session_state["option_book_strategy"] = "Custom Spread"
    st.session_state["ob_leg_count"] = count + 1
    st.session_state[f"ob_{count}_action"] = "BUY_OPEN"
    st.session_state[f"ob_{count}_type"] = "CALL"
    symbol = str(st.session_state.get("ob_symbol_value", "SPY") or "SPY").upper()
    st.session_state["_ob_strategy"] = f"{symbol}:Custom Spread"
    st.session_state.pop("_ob_price_seed", None)


def _remove_leg(index: int) -> None:
    count = int(st.session_state.get("ob_leg_count", 1) or 1)
    if count <= 1:
        return
    fields = ("action", "qty", "expiry", "type", "strike")
    for i in range(index, count - 1):
        for field in fields:
            src, dst = f"ob_{i + 1}_{field}", f"ob_{i}_{field}"
            if src in st.session_state:
                st.session_state[dst] = st.session_state[src]
            else:
                st.session_state.pop(dst, None)
    for field in fields:
        st.session_state.pop(f"ob_{count - 1}_{field}", None)
    st.session_state["ob_leg_count"] = count - 1
    st.session_state["option_book_strategy"] = "Custom Spread"
    symbol = str(st.session_state.get("ob_symbol_value", "SPY") or "SPY").upper()
    st.session_state["_ob_strategy"] = f"{symbol}:Custom Spread"
    st.session_state.pop("_ob_price_seed", None)


def _expirations(client, symbol: str, touch_session) -> list[date]:
    payload = client.get_option_expirations(symbol)
    touch_session()
    out = []
    for year, month, day in option_expiration_dates(payload):
        try:
            out.append(date(year, month, day))
        except ValueError:
            pass
    return sorted(set(out))


def _chain(client, symbol: str, expiry: date, touch_session) -> list[dict[str, Any]]:
    payload = client.get_option_chain(
        symbol, expiry.year, expiry.month, expiry.day,
        no_of_strikes=None, chain_type="CALLPUT",
    )
    touch_session()
    return extract_option_rows(payload, expiry)


def _save(ticket: dict[str, Any]) -> None:
    rows = list(st.session_state.get("option_book_saved_tickets") or [])
    rows.insert(0, ticket)
    st.session_state["option_book_saved_tickets"] = rows[:25]


# ==============================
# OPTION BOOK TICKET
# ==============================

def render_option_book(client, touch_session) -> None:
    """Render the production E*TRADE Option Book ticket."""
    st.html(_OPTION_BOOK_CSS)
    st.markdown(
        '<div class="ob-note"><strong>E*TRADE API MODE</strong> // Broker PREVIEW is supported. '
        'The public API does not document a Power E*TRADE Saved Orders endpoint, so this tab stores '
        'drafts in Option Book and uses PREVIEW for broker validation. It never submits a live order.</div>',
        unsafe_allow_html=True,
    )
    if client is None:
        st.info("Connect E*TRADE to load accounts, quotes, expirations, strikes, and broker preview.")
        return
    offline = bool(getattr(client, "is_offline", False))
    if offline:
        st.warning("OFFLINE SNAPSHOT MODE // ticket data may be cached; broker preview is disabled.")

    # ==============================
    # TICKER / ACCOUNT / STRATEGY
    # ==============================
    c1, c2, c3 = st.columns([1.7, 1.45, 1.15], gap="small")
    with c1:
        current = str(st.session_state.get("ob_symbol_value", "SPY") or "SPY").upper()
        symbol = smart_ticker_selector(
            st.selectbox, label="Ticker / Company", current=current,
            key="ob_symbol_selector", help_text="Type ticker or company name.",
        ).upper()
        st.session_state["ob_symbol_value"] = symbol
    try:
        accounts = [a for a in client.list_accounts() if isinstance(a, dict)]
    except Exception as exc:
        accounts = []
        st.error(f"E*TRADE accounts unavailable: {exc}")
    with c2:
        labels = [_account_label(a) for a in accounts] or ["No account loaded"]
        default_account_index = _default_account_index(accounts) if accounts else 0
        if accounts and st.session_state.get("ob_account") not in labels:
            st.session_state["ob_account"] = labels[default_account_index]
        selected_account = st.selectbox(
            "Account",
            labels,
            index=default_account_index,
            disabled=not accounts,
            key="ob_account",
            help="Defaults to the E*TRADE account ending in 5474 when available.",
        )
        account = accounts[labels.index(selected_account)] if accounts else {}
        account_key = str(account.get("accountIdKey") or "")
    with c3:
        strategy = st.selectbox("Strategy", _STRATEGIES, key="option_book_strategy")
    _strategy_defaults(strategy, symbol)

    try:
        quote = quote_summary(client.get_quote(symbol))
        touch_session()
        name = str(quote.get("description") or company_name(symbol) or "").strip()
        record_lookup(symbol, name)
        spot = float(quote.get("last") or 0.0)
    except Exception as exc:
        quote, name, spot = {}, company_name(symbol), 0.0
        st.warning(f"Quote unavailable for {symbol}: {exc}")

    account_value = buying_power = None
    if account_key:
        try:
            balance = client.get_balance(account_key)
            account_value = total_account_value(balance)
            buying_power = find_number(balance, "buyingPower", "cashBuyingPower", "marginBuyingPower")
            touch_session()
        except Exception:
            pass
    st.markdown(
        '<div class="ob-card"><div class="ob-name">'
        + html.escape(f"{symbol} — {name or 'COMPANY NAME UNAVAILABLE'}")
        + '</div><div class="ob-quote">'
        + '<span>LAST <b>' + html.escape(_money(quote.get("last"))) + "</b></span>"
        + '<span>BID <b>' + html.escape(_money(quote.get("bid"))) + "</b></span>"
        + '<span>ASK <b>' + html.escape(_money(quote.get("ask"))) + "</b></span>"
        + '<span>ACCOUNT <b>' + html.escape(_money(account_value)) + "</b></span>"
        + '<span>BUYING POWER <b>' + html.escape(_money(buying_power)) + "</b></span>"
        + "</div></div>",
        unsafe_allow_html=True,
    )

    try:
        expirations = _expirations(client, symbol, touch_session)
    except Exception as exc:
        st.error(f"Option expirations unavailable for {symbol}: {exc}")
        return
    if not expirations:
        st.info("No option expirations are available for this symbol.")
        return

    # ==============================
    # OPTION LEGS
    # ==============================
    add_col, hint_col = st.columns([1.15, 4.85], gap="small")
    add_col.button(
        "+ ADD OPTION LEG",
        on_click=_add_leg,
        key="ob_add",
        width="content",
        disabled=int(st.session_state.get("ob_leg_count", 1) or 1) >= 4,
    )
    hint_col.caption("1–4 legs // expiration and strike selections come from the E*TRADE option chain")
    count = int(st.session_state.get("ob_leg_count", 1) or 1)
    chains: dict[date, list[dict[str, Any]]] = {}
    legs: list[dict[str, Any]] = []

    for i in range(count):
        exp_key, type_key, strike_key = f"ob_{i}_expiry", f"ob_{i}_type", f"ob_{i}_strike"
        if st.session_state.get(exp_key) not in expirations:
            st.session_state[exp_key] = _default_expiry(expirations)
        if st.session_state.get(type_key) not in {"CALL", "PUT"}:
            st.session_state[type_key] = "CALL"
        row = st.columns([1.42, .56, 1.18, .84, .7, .72, .72, .4], gap="small")
        action = row[0].selectbox("Action" if i == 0 else "Action ", list(_ACTIONS), key=f"ob_{i}_action", format_func=_ACTIONS.get)
        qty = int(row[1].number_input("Qty" if i == 0 else "Qty ", 1, 5000, 1, key=f"ob_{i}_qty"))
        expiry = row[2].selectbox("Expiration" if i == 0 else "Expiration ", expirations, key=exp_key, format_func=_date_label)
        call_put = row[4].selectbox("Type" if i == 0 else "Type ", ["CALL", "PUT"], key=type_key, format_func=str.title)
        if expiry not in chains:
            try:
                chains[expiry] = _chain(client, symbol, expiry, touch_session)
            except Exception as exc:
                chains[expiry] = []
                st.warning(f"{_date_label(expiry)} chain unavailable: {exc}")
        strikes = strikes_for(chains[expiry], call_put)
        if not strikes:
            st.error(f"No {call_put.lower()} strikes available for {_date_label(expiry)}.")
            continue
        if st.session_state.get(strike_key) not in strikes:
            offset = i if strategy == "Call Vertical" else (1 - i if strategy == "Put Vertical" else 0)
            st.session_state[strike_key] = _closest(strikes, spot or strikes[len(strikes)//2], offset)
        strike = float(row[3].selectbox("Strike" if i == 0 else "Strike ", strikes, key=strike_key, format_func=lambda x: f"{x:,.2f}"))
        market = contract_quote(chains[expiry], call_put, strike) or {}
        row[5].markdown(_leg_quote_markup("Bid", market.get("bid")), unsafe_allow_html=True)
        row[6].markdown(_leg_quote_markup("Ask", market.get("ask")), unsafe_allow_html=True)
        row[7].button(
            "✕",
            key=f"ob_remove_{i}",
            on_click=_remove_leg,
            args=(i,),
            disabled=count <= 1,
            width="content",
            help="Remove this option leg.",
        )
        legs.append({"action": action, "quantity": qty, "expiry": expiry, "call_put": call_put,
                     "strike": strike, "bid": market.get("bid"), "ask": market.get("ask")})
    if len(legs) != count:
        return

    # ==============================
    # PRICE / DURATION
    # ==============================
    net = net_price_snapshot(legs)
    spread = count > 1
    price_choices = ["NET_DEBIT", "NET_CREDIT", "MARKET"] if spread else ["LIMIT", "STOP", "STOP_LIMIT", "MARKET"]
    default_price = "NET_CREDIT" if spread and net.get("side") == "CREDIT" else ("NET_DEBIT" if spread else ("STOP" if legs[0]["action"].startswith("SELL") else "LIMIT"))
    if st.session_state.get("ob_price_type") not in price_choices:
        st.session_state["ob_price_type"] = default_price
    signature = "|".join(f"{x['action']}:{x['call_put']}:{x['expiry']}:{x['strike']}:{x['quantity']}" for x in legs)
    if st.session_state.get("_ob_price_seed") != signature:
        mid = net.get("mid")
        st.session_state["ob_limit"] = max(.01, round(abs(float(mid)), 2)) if mid is not None else .01
        try:
            st.session_state["ob_stop"] = max(.01, round(float(legs[0].get("bid")) - .05, 2))
        except (TypeError, ValueError):
            st.session_state["ob_stop"] = st.session_state["ob_limit"]
        st.session_state["_ob_price_seed"] = signature
    p1, p2, p3, p4 = st.columns([1.3, .85, .85, .8], gap="small")
    price_type = p1.selectbox("Price Type", price_choices, key="ob_price_type", format_func=_PRICES.get)
    needs_limit = price_type in {"LIMIT", "STOP_LIMIT", "NET_DEBIT", "NET_CREDIT"}
    needs_stop = price_type in {"STOP", "STOP_LIMIT"}
    limit_price = float(p2.number_input("Limit / Stop-Limit", min_value=.01, step=.01, format="%.2f", key="ob_limit", disabled=not needs_limit)) if needs_limit else None
    stop_price = float(p3.number_input("Stop", min_value=.01, step=.01, format="%.2f", key="ob_stop", disabled=not needs_stop)) if needs_stop else None
    order_term = p4.selectbox("Duration", list(_DURATIONS), key="ob_duration", format_func=_DURATIONS.get)
    st.markdown(
        '<div class="ob-price"><b>NATURAL</b> ' + html.escape(_money(abs(net["natural"])) if net.get("natural") is not None else "—") +
        ' &nbsp; <b>MID</b> ' + html.escape(_money(abs(net["mid"])) if net.get("mid") is not None else "—") +
        ' &nbsp; <b>OPPOSITE</b> ' + html.escape(_money(abs(net["opposite"])) if net.get("opposite") is not None else "—") +
        ' &nbsp; <b>NET</b> ' + html.escape(str(net.get("side") or "UNKNOWN")) + '</div>', unsafe_allow_html=True,
    )

    description = " | ".join(
        f"{_ACTIONS[x['action']]} {x['quantity']} {_date_label(x['expiry'])} {x['strike']:g} {x['call_put'].title()}" for x in legs
    )
    st.markdown(
        '<div class="ob-ticket-summary">TICKET // '
        + html.escape(description)
        + "</div>",
        unsafe_allow_html=True,
    )
    b1, b2, b3 = st.columns([1.0, 1.15, 3.85], gap="small")
    local_click = b1.button("SAVE DRAFT", key="ob_save", width="content")
    preview_click = b2.button(
        "PREVIEW IN E*TRADE",
        key="ob_preview",
        type="primary",
        width="content",
        disabled=offline or not account_key,
        help="Broker-validates with E*TRADE Preview; never places the order.",
    )
    b3.markdown(
        '<div class="ob-action-note">BROKER PREVIEW ONLY // no live-order submission path is implemented</div>',
        unsafe_allow_html=True,
    )
    ticket = {
        "saved_at": datetime.now().astimezone().isoformat(timespec="seconds"), "symbol": symbol,
        "strategy": strategy, "description": description, "price_type": price_type,
        "limit_price": limit_price, "stop_price": stop_price, "duration": _DURATIONS[order_term],
        "status": "LOCAL DRAFT",
    }
    if local_click:
        _save(dict(ticket))
        st.success("OPTION BOOK SAVED // local draft only // no live order submitted")
    if preview_click:
        try:
            payload = build_preview_payload(
                symbol=symbol, legs=legs, price_type=price_type, limit_price=limit_price,
                stop_price=stop_price, order_term=order_term, client_order_id=new_client_order_id(),
            )
            details = preview_details(client.preview_order(account_key, payload))
            touch_session()
            ticket.update({"status": "E*TRADE PREVIEWED", "preview_id": details.get("preview_id"),
                           "total_order_value": details.get("total_order_value"),
                           "estimated_commission": details.get("estimated_commission")})
            _save(dict(ticket))
            st.success(f"E*TRADE PREVIEW ACCEPTED // Preview ID {details.get('preview_id') or 'N/A'} // NOT PLACED")
            st.markdown(
                '<div class="ob-preview-stats">'
                '<div class="ob-preview-stat"><div class="ob-preview-stat-label">Estimated Order Value</div>'
                '<div class="ob-preview-stat-value">'
                + html.escape(_money(details.get("total_order_value")))
                + '</div></div>'
                '<div class="ob-preview-stat"><div class="ob-preview-stat-label">Estimated Commission</div>'
                '<div class="ob-preview-stat-value">'
                + html.escape(_money(details.get("estimated_commission")))
                + "</div></div></div>",
                unsafe_allow_html=True,
            )
            for message in details.get("messages") or []:
                st.warning(str(message))
        except (ETradeError, ValueError) as exc:
            st.error(f"E*TRADE PREVIEW REJECTED // {exc}")
        except Exception as exc:
            st.error(f"E*TRADE PREVIEW FAILED // {exc}")

    saved = list(st.session_state.get("option_book_saved_tickets") or [])
    if saved:
        st.markdown("**SAVED OPTION BOOK // MOST RECENT FIRST**")
        frame = pd.DataFrame(saved)
        columns = [c for c in ("saved_at", "symbol", "strategy", "description", "price_type", "limit_price", "stop_price", "duration", "status", "preview_id", "total_order_value", "estimated_commission") if c in frame.columns]
        st.dataframe(frame[columns], hide_index=True, width="stretch", height=min(460, 38 * len(frame) + 42))
