"""Production UI for Raj's Terminal Option Book.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR: Option Book ticker/account selection, option legs, pricing,
local drafts, and E*TRADE broker-preview presentation.
DO NOT EDIT THIS FILE FOR: OAuth/session transport, Risk Sizing, GEX, Holdings,
navigation, the legacy Orders simulator, or live order placement.

LAYOUT RULES
------------
- Keep the ticket dense and horizontal like a professional order-entry screen.
- Do not use st.metric for option-leg quotes; narrow metric cards clip prices.
- Do not stretch action buttons across columns.
- Keep each leg in one compact bordered row with its market strip directly below.
"""

from __future__ import annotations

import html
from datetime import date, datetime
from typing import Any

import pandas as pd
import streamlit as st

from src.etrade_client import (
    ETradeError,
    find_number,
    option_expiration_dates,
    quote_summary,
    total_account_value,
)
from src.option_book import (
    build_preview_payload,
    contract_quote,
    extract_option_rows,
    net_price_snapshot,
    new_client_order_id,
    preview_details,
    strikes_for,
)
from src.ticker_autocomplete import company_name, record_lookup, smart_ticker_selector


# ==============================
# UI / CSS
# ==============================

_OPTION_BOOK_CSS = """
<style>
/*
   OPTION BOOK VISUAL CONTRACT
   E*TRADE Risk Sizing is the reference surface:
   - Courier New
   - orange filled section bars with black text
   - 38px controls
   - 52px metric cards
   - 4px vertical / 8px horizontal grid rhythm
   - black surfaces + orange borders; green/red/blue only for financial meaning
*/
.st-key-option_book_workspace{
    --ob-orange:#fb8b1e;
    --ob-green:#4af6c3;
    --ob-red:#ff433d;
    --ob-blue:#0068ff;
    --ob-border:#5d3605;
    --ob-black:#000000;
    --ob-panel:#050505;
    --ob-muted:#8f99a8;
    margin:0!important;
    padding:0!important;
    font-family:"Courier New",monospace!important;
}

.st-key-option_book_workspace [data-testid="stVerticalBlock"]{gap:4px!important;}
.st-key-option_book_workspace [data-testid="stHorizontalBlock"]{gap:8px!important;}
.st-key-option_book_workspace [data-testid="stColumn"]{min-width:0!important;}

.st-key-option_book_workspace [data-testid="stWidgetLabel"]{
    min-height:20px!important;
    margin:0 0 3px 0!important;
    padding:0!important;
    display:flex!important;
    align-items:center!important;
}
.st-key-option_book_workspace [data-testid="stWidgetLabel"] p{
    margin:0!important;
    padding:0!important;
    color:#f2f2f2!important;
    -webkit-text-fill-color:#f2f2f2!important;
    font-family:"Courier New",monospace!important;
    font-size:.64rem!important;
    font-weight:900!important;
    line-height:1!important;
}

.st-key-option_book_workspace [data-testid="stSelectbox"]{margin:0!important;min-width:0!important;}
.st-key-option_book_workspace [data-testid="stSelectbox"] div[data-baseweb="select"]>div{
    min-height:38px!important;
    height:38px!important;
    background:var(--ob-panel)!important;
    border-color:var(--ob-orange)!important;
    border-radius:0!important;
    box-shadow:none!important;
}
.st-key-option_book_workspace [data-testid="stSelectbox"] div[data-baseweb="select"] span,
.st-key-option_book_workspace [data-testid="stSelectbox"] div[data-baseweb="select"] input{
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    font-family:"Courier New",monospace!important;
    font-size:.72rem!important;
    font-weight:800!important;
    white-space:nowrap!important;
    overflow:hidden!important;
    text-overflow:ellipsis!important;
}

.st-key-option_book_workspace [data-testid="stNumberInput"]{margin:0!important;min-width:0!important;}
.st-key-option_book_workspace [data-testid="stNumberInput"] input{
    height:38px!important;
    min-height:38px!important;
    padding-top:0!important;
    padding-bottom:0!important;
    background:var(--ob-panel)!important;
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    border-color:var(--ob-orange)!important;
    font-family:"Courier New",monospace!important;
    font-size:.72rem!important;
    font-weight:900!important;
}
.st-key-option_book_workspace [data-testid="stNumberInputStepDown"],
.st-key-option_book_workspace [data-testid="stNumberInputStepUp"]{
    position:relative!important;
    min-width:38px!important;
    width:38px!important;
    height:38px!important;
    flex:0 0 38px!important;
    padding:0!important;
    background:var(--ob-panel)!important;
    border-color:var(--ob-orange)!important;
    border-radius:0!important;
    box-shadow:none!important;
}
.st-key-option_book_workspace [data-testid="stNumberInputStepDown"]>*,
.st-key-option_book_workspace [data-testid="stNumberInputStepUp"]>*{display:none!important;}
.st-key-option_book_workspace [data-testid="stNumberInputStepDown"]::after,
.st-key-option_book_workspace [data-testid="stNumberInputStepUp"]::after{
    position:absolute;
    inset:0;
    display:flex;
    align-items:center;
    justify-content:center;
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    font-family:"Courier New",monospace!important;
    font-size:1.05rem;
    font-weight:900;
    line-height:1;
}
.st-key-option_book_workspace [data-testid="stNumberInputStepDown"]::after{content:"−";}
.st-key-option_book_workspace [data-testid="stNumberInputStepUp"]::after{content:"+";}
.st-key-option_book_workspace [data-testid="stNumberInputStepDown"]:hover,
.st-key-option_book_workspace [data-testid="stNumberInputStepUp"]:hover{
    background:var(--ob-orange)!important;
}
.st-key-option_book_workspace [data-testid="stNumberInputStepDown"]:hover::after,
.st-key-option_book_workspace [data-testid="stNumberInputStepUp"]:hover::after{
    color:#000!important;
    -webkit-text-fill-color:#000!important;
}

.st-key-option_book_workspace [data-testid="stButton"] button{
    width:auto!important;
    min-width:0!important;
    min-height:38px!important;
    height:38px!important;
    padding:0 .72rem!important;
    border:1px solid var(--ob-orange)!important;
    border-radius:0!important;
    background:var(--ob-panel)!important;
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    box-shadow:none!important;
    font-family:"Courier New",monospace!important;
    font-size:.70rem!important;
    font-weight:900!important;
    line-height:1!important;
    white-space:nowrap!important;
}
.st-key-option_book_workspace [data-testid="stButton"] button *{
    color:inherit!important;
    -webkit-text-fill-color:inherit!important;
}
.st-key-option_book_workspace [data-testid="stButton"] button:hover:not(:disabled){
    background:#171007!important;
    color:#ffad52!important;
    -webkit-text-fill-color:#ffad52!important;
}
.st-key-option_book_workspace .st-key-ob_preview button{
    background:var(--ob-orange)!important;
    color:#000!important;
    -webkit-text-fill-color:#000!important;
}
.st-key-option_book_workspace .st-key-ob_preview button:hover:not(:disabled){
    background:#ffad52!important;
    color:#000!important;
    -webkit-text-fill-color:#000!important;
}
.st-key-option_book_workspace [data-testid="stButton"] button:disabled{
    background:#0b0d10!important;
    color:#535d69!important;
    -webkit-text-fill-color:#535d69!important;
    border-color:#2b333e!important;
    opacity:1!important;
}
.st-key-option_book_workspace [class*="st-key-ob_remove_"]{padding-top:23px!important;}

.st-key-option_book_workspace [class*="st-key-ob_leg_box_"]{
    border:1px solid var(--ob-border)!important;
    border-radius:0!important;
    background:#000!important;
    padding:6px 8px!important;
    margin:0 0 5px 0!important;
    box-sizing:border-box!important;
    min-width:0!important;
}

.ob-risk-note{
    display:flex;
    align-items:center;
    min-height:22px;
    box-sizing:border-box;
    margin:0 0 5px 0;
    padding:0;
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    font-family:"Courier New",monospace;
    font-size:.61rem;
    font-weight:800;
    line-height:1.1;
    white-space:nowrap;
    overflow:hidden;
    text-overflow:ellipsis;
}
.ob-risk-note .muted{color:var(--ob-muted)!important;-webkit-text-fill-color:var(--ob-muted)!important;}

.ob-section{
    display:flex;
    align-items:center;
    width:100%;
    height:30px;
    min-height:30px;
    box-sizing:border-box;
    margin:0 0 5px 0;
    padding:0 10px;
    border:1px solid var(--ob-orange);
    background:var(--ob-orange);
    color:#000!important;
    -webkit-text-fill-color:#000!important;
    font-family:"Courier New",monospace;
    font-size:.78rem;
    font-weight:900;
    line-height:1;
    text-transform:uppercase;
}
.ob-section::before{content:none!important;display:none!important;}

.ob-leg-title{
    display:flex;
    align-items:center;
    min-height:18px;
    margin:0 0 4px 0;
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    font-family:"Courier New",monospace;
    font-size:.61rem;
    font-weight:900;
    line-height:1;
}

.ob-metric-grid{
    display:grid;
    gap:8px;
    margin:0 0 5px 0;
    min-width:0;
}
.ob-metric-grid-6{grid-template-columns:repeat(6,minmax(0,1fr));}
.ob-metric-grid-5{grid-template-columns:repeat(5,minmax(0,1fr));}
.ob-metric-grid-4{grid-template-columns:repeat(4,minmax(0,1fr));}
.ob-metric-grid-2{grid-template-columns:repeat(2,minmax(0,1fr));}

.ob-metric-card{
    position:relative;
    min-width:0;
    min-height:52px;
    height:52px;
    box-sizing:border-box;
    padding:6px 8px;
    border:1px solid var(--ob-orange);
    background:#000;
    font-family:"Courier New",monospace;
    overflow:hidden;
}
.ob-metric-label{
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    font-size:.64rem;
    font-weight:900;
    line-height:1;
    white-space:nowrap;
    overflow:hidden;
    text-overflow:ellipsis;
}
.ob-metric-value{
    color:var(--ob-green)!important;
    -webkit-text-fill-color:var(--ob-green)!important;
    font-size:1.06rem;
    font-weight:900;
    line-height:1;
    margin-top:4px;
    white-space:nowrap;
    overflow:hidden;
    text-overflow:ellipsis;
}
.ob-tone-orange .ob-metric-value{color:var(--ob-orange)!important;-webkit-text-fill-color:var(--ob-orange)!important;}
.ob-tone-blue .ob-metric-value{color:var(--ob-blue)!important;-webkit-text-fill-color:var(--ob-blue)!important;}
.ob-tone-red .ob-metric-value{color:var(--ob-red)!important;-webkit-text-fill-color:var(--ob-red)!important;}

.ob-ticket-summary{
    border:1px solid var(--ob-orange);
    background:#000;
    padding:6px 8px;
    min-height:38px;
    box-sizing:border-box;
    margin:0 0 5px 0;
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    font:900 .68rem/1.25 "Courier New",monospace;
    overflow-wrap:anywhere;
}
.ob-ticket-summary b{color:var(--ob-orange)!important;-webkit-text-fill-color:var(--ob-orange)!important;}

.ob-action-note{
    display:flex;
    justify-content:flex-end;
    align-items:center;
    min-height:18px;
    margin:0 0 3px 0;
    color:var(--ob-muted)!important;
    -webkit-text-fill-color:var(--ob-muted)!important;
    font:800 .60rem/1 "Courier New",monospace;
}

.st-key-option_book_workspace [data-testid="stExpander"]{
    border-color:var(--ob-orange)!important;
    border-radius:0!important;
    margin-top:0!important;
}
.st-key-option_book_workspace [data-testid="stExpander"] summary,
.st-key-option_book_workspace [data-testid="stExpander"] summary *{
    color:var(--ob-orange)!important;
    -webkit-text-fill-color:var(--ob-orange)!important;
    font-family:"Courier New",monospace!important;
    font-size:.68rem!important;
    font-weight:900!important;
}

@media (max-width:1100px){
    .ob-metric-grid-6,.ob-metric-grid-5{grid-template-columns:repeat(3,minmax(0,1fr));}
}
@media (max-width:760px){
    .ob-metric-grid-6,.ob-metric-grid-5,.ob-metric-grid-4{grid-template-columns:repeat(2,minmax(0,1fr));}
    .ob-risk-note{white-space:normal;}
    .ob-action-note{justify-content:flex-start;text-align:left;}
}
</style>
"""

_ACTIONS = {
    "BUY_OPEN": "Buy to Open",
    "SELL_OPEN": "Sell to Open",
    "BUY_CLOSE": "Buy to Close",
    "SELL_CLOSE": "Sell to Close",
}
_PRICES = {
    "LIMIT": "Limit",
    "STOP": "Stop",
    "STOP_LIMIT": "Stop Limit",
    "MARKET": "Market",
    "NET_DEBIT": "Limit Debit",
    "NET_CREDIT": "Limit Credit",
}
_DURATIONS = {"GOOD_FOR_DAY": "DAY", "GOOD_UNTIL_CANCEL": "GTC"}
_STRATEGIES = ("Call/Put", "Call Vertical", "Put Vertical", "Custom Spread")
_DEFAULT_ACCOUNT_SUFFIX = "5474"


def _money(value: Any) -> str:
    try:
        return "$" + f"{float(value):,.2f}"
    except (TypeError, ValueError):
        return "—"


def _plain_number(value: Any, digits: int = 2) -> str:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "—"
    if abs(number - round(number)) < 1e-9:
        return f"{int(round(number)):,}"
    return f"{number:,.{digits}f}"


def _metric_grid_markup(
    items: list[tuple[str, str, str]],
    columns: int,
) -> str:
    cells = "".join(
        '<div class="ob-metric-card ob-tone-' + html.escape(str(tone)) + '">'
        '<div class="ob-metric-label">' + html.escape(str(label)) + "</div>"
        '<div class="ob-metric-value">' + html.escape(str(value)) + "</div>"
        "</div>"
        for label, value, tone in items
    )
    return (
        '<div class="ob-metric-grid ob-metric-grid-'
        + str(int(columns))
        + '">'
        + cells
        + "</div>"
    )


def _account_label(account: dict[str, Any]) -> str:
    name = str(account.get("accountDesc") or account.get("accountName") or "E*TRADE")
    ident = str(account.get("accountId") or account.get("accountIdKey") or "")
    return f"{name} // x{ident[-4:]}" if ident else name


def _account_matches_default(account: dict[str, Any]) -> bool:
    """Prefer Raj's x5474 account without overriding a later manual choice."""
    for key in ("accountId", "accountDesc", "accountName", "accountIdKey"):
        raw = str(account.get(key) or "")
        digits = "".join(ch for ch in raw if ch.isdigit())
        if digits.endswith(_DEFAULT_ACCOUNT_SUFFIX):
            return True
    return False


def _default_account_index(accounts: list[dict[str, Any]]) -> int:
    return next(
        (index for index, account in enumerate(accounts) if _account_matches_default(account)),
        0,
    )


def _account_selector_value(account: dict[str, Any], index: int) -> str:
    """Stable selectbox value; accountIdKey remains the broker API identifier."""
    return str(
        account.get("accountIdKey")
        or account.get("accountId")
        or f"OPTION_BOOK_ACCOUNT_{index}"
    )


def _date_label(expiry: date) -> str:
    return expiry.strftime("%b-%d-%y")


def _default_expiry(expirations: list[date]) -> date:
    today = date.today()
    return next((d for d in expirations if (d - today).days >= 14), expirations[0])


def _closest(strikes: list[float], spot: float, offset: int = 0) -> float:
    base = min(range(len(strikes)), key=lambda i: abs(strikes[i] - spot))
    return float(strikes[max(0, min(len(strikes) - 1, base + offset))])


def _market_strip_markup(market: dict[str, Any]) -> str:
    bid = market.get("bid")
    ask = market.get("ask")
    try:
        bid_value = float(bid)
        ask_value = float(ask)
        mid = (bid_value + ask_value) / 2.0
        spread = max(0.0, ask_value - bid_value)
    except (TypeError, ValueError):
        mid = None
        spread = None

    return _metric_grid_markup(
        [
            ("BID", _money(bid), "green"),
            ("ASK", _money(ask), "green"),
            ("MID", _money(mid), "green"),
            ("SPREAD", _money(spread), "orange"),
            ("VOLUME", _plain_number(market.get("volume"), 0), "blue"),
            ("OPEN INT", _plain_number(market.get("open_interest"), 0), "blue"),
        ],
        6,
    )


def _strategy_defaults(strategy: str, symbol: str) -> None:
    signature = f"{symbol}:{strategy}"
    if st.session_state.get("_ob_strategy") == signature:
        return
    defaults = {
        "Call/Put": [("BUY_OPEN", "CALL")],
        "Call Vertical": [("BUY_OPEN", "CALL"), ("SELL_OPEN", "CALL")],
        "Put Vertical": [("BUY_OPEN", "PUT"), ("SELL_OPEN", "PUT")],
        "Custom Spread": [("BUY_OPEN", "CALL"), ("SELL_OPEN", "CALL")],
    }[strategy]
    st.session_state["ob_leg_count"] = len(defaults)
    for i, (action, call_put) in enumerate(defaults):
        st.session_state[f"ob_{i}_action"] = action
        st.session_state[f"ob_{i}_type"] = call_put
    st.session_state["_ob_strategy"] = signature
    st.session_state.pop("_ob_price_seed", None)


def _add_leg() -> None:
    count = int(st.session_state.get("ob_leg_count", 1) or 1)
    if count >= 4:
        return
    st.session_state["option_book_strategy"] = "Custom Spread"
    st.session_state["ob_leg_count"] = count + 1
    st.session_state[f"ob_{count}_action"] = "BUY_OPEN"
    st.session_state[f"ob_{count}_type"] = "CALL"
    symbol = str(st.session_state.get("ob_symbol_value", "SPY") or "SPY").upper()
    st.session_state["_ob_strategy"] = f"{symbol}:Custom Spread"
    st.session_state.pop("_ob_price_seed", None)


def _remove_leg(index: int) -> None:
    count = int(st.session_state.get("ob_leg_count", 1) or 1)
    if count <= 1:
        return
    fields = ("action", "qty", "expiry", "type", "strike")
    for i in range(index, count - 1):
        for field in fields:
            src, dst = f"ob_{i + 1}_{field}", f"ob_{i}_{field}"
            if src in st.session_state:
                st.session_state[dst] = st.session_state[src]
            else:
                st.session_state.pop(dst, None)
    for field in fields:
        st.session_state.pop(f"ob_{count - 1}_{field}", None)
    st.session_state["ob_leg_count"] = count - 1
    st.session_state["option_book_strategy"] = "Custom Spread"
    symbol = str(st.session_state.get("ob_symbol_value", "SPY") or "SPY").upper()
    st.session_state["_ob_strategy"] = f"{symbol}:Custom Spread"
    st.session_state.pop("_ob_price_seed", None)


def _expirations(client, symbol: str, touch_session) -> list[date]:
    payload = client.get_option_expirations(symbol)
    touch_session()
    out = []
    for year, month, day in option_expiration_dates(payload):
        try:
            out.append(date(year, month, day))
        except ValueError:
            pass
    return sorted(set(out))


def _chain(client, symbol: str, expiry: date, touch_session) -> list[dict[str, Any]]:
    payload = client.get_option_chain(
        symbol,
        expiry.year,
        expiry.month,
        expiry.day,
        no_of_strikes=None,
        chain_type="CALLPUT",
    )
    touch_session()
    return extract_option_rows(payload, expiry)


def _save(ticket: dict[str, Any]) -> None:
    rows = list(st.session_state.get("option_book_saved_tickets") or [])
    rows.insert(0, ticket)
    st.session_state["option_book_saved_tickets"] = rows[:25]


# ==============================
# OPTION BOOK TICKET
# ==============================

def render_option_book(client, touch_session) -> None:
    """Render the production E*TRADE Option Book ticket."""
    st.html(_OPTION_BOOK_CSS)

    with st.container(key="option_book_workspace"):
        st.markdown(
            '<div class="ob-risk-note">'
            'PREVIEW ONLY // E*TRADE BROKER VALIDATION // '
            '<span class="muted">SAVE DRAFT STAYS LOCAL // NO LIVE-ORDER SUBMISSION PATH</span>'
            "</div>",
            unsafe_allow_html=True,
        )

        if client is None:
            st.info(
                "Connect E*TRADE to load accounts, quotes, expirations, strikes, "
                "and broker preview."
            )
            return

        offline = bool(getattr(client, "is_offline", False))
        if offline:
            st.warning(
                "OFFLINE SNAPSHOT MODE // ticket data may be cached; broker preview is disabled."
            )

        # ==============================
        # TICKER / ACCOUNT / STRATEGY
        # ==============================
        try:
            accounts = [a for a in client.list_accounts() if isinstance(a, dict)]
        except Exception as exc:
            accounts = []
            st.error(f"E*TRADE accounts unavailable: {exc}")

        top = st.columns([2.15, 1.45, 1.15], gap="small")
        with top[0]:
            current = str(st.session_state.get("ob_symbol_value", "SPY") or "SPY").upper()
            symbol = smart_ticker_selector(
                st.selectbox,
                label="Ticker / Company",
                current=current,
                key="ob_symbol_selector",
                help_text="Type ticker or company name.",
            ).upper()
            st.session_state["ob_symbol_value"] = symbol

        with top[1]:
            if accounts:
                option_values = [
                    _account_selector_value(account, index)
                    for index, account in enumerate(accounts)
                ]
                account_by_value = {
                    value: account for value, account in zip(option_values, accounts)
                }
                preferred = option_values[_default_account_index(accounts)]
                if st.session_state.get("ob_account_key") not in account_by_value:
                    st.session_state["ob_account_key"] = preferred

                selected_account_value = st.selectbox(
                    "Account",
                    option_values,
                    key="ob_account_key",
                    format_func=lambda value: _account_label(account_by_value[value]),
                    help=(
                        "Defaults to the E*TRADE account ending in 5474 when "
                        "available. A manual account change is preserved."
                    ),
                )
                account = account_by_value[selected_account_value]
            else:
                st.selectbox(
                    "Account",
                    ["No account loaded"],
                    disabled=True,
                    key="ob_account_unavailable",
                )
                account = {}
            account_key = str(account.get("accountIdKey") or "")

        with top[2]:
            strategy = st.selectbox(
                "Strategy",
                _STRATEGIES,
                key="option_book_strategy",
            )
        _strategy_defaults(strategy, symbol)

        try:
            quote = quote_summary(client.get_quote(symbol))
            touch_session()
            name = str(quote.get("description") or company_name(symbol) or "").strip()
            record_lookup(symbol, name)
            spot = float(quote.get("last") or 0.0)
        except Exception as exc:
            quote, name, spot = {}, company_name(symbol), 0.0
            st.warning(f"Quote unavailable for {symbol}: {exc}")

        account_value = buying_power = None
        if account_key:
            try:
                balance = client.get_balance(account_key)
                account_value = total_account_value(balance)
                buying_power = find_number(
                    balance,
                    "buyingPower",
                    "cashBuyingPower",
                    "marginBuyingPower",
                )
                touch_session()
            except Exception:
                pass

        st.markdown(
            '<div class="ob-risk-note">'
            + html.escape(f"{symbol} — {name or 'COMPANY NAME UNAVAILABLE'}")
            + " // ACCOUNT "
            + html.escape(_account_label(account) if account else "NO ACCOUNT")
            + "</div>",
            unsafe_allow_html=True,
        )
        st.markdown(
            _metric_grid_markup(
                [
                    ("LAST", _money(quote.get("last")), "green"),
                    ("BID", _money(quote.get("bid")), "green"),
                    ("ASK", _money(quote.get("ask")), "green"),
                    ("ACCOUNT VALUE", _money(account_value), "blue"),
                    ("BUYING POWER", _money(buying_power), "green"),
                ],
                5,
            ),
            unsafe_allow_html=True,
        )

        try:
            expirations = _expirations(client, symbol, touch_session)
        except Exception as exc:
            st.error(f"Option expirations unavailable for {symbol}: {exc}")
            return
        if not expirations:
            st.info("No option expirations are available for this symbol.")
            return

        # ==============================
        # OPTION LEGS
        # ==============================
        st.markdown('<div class="ob-section">OPTION LEGS</div>', unsafe_allow_html=True)
        st.markdown(
            '<div class="ob-risk-note">1–4 LEGS // EXPIRATION + STRIKE COME DIRECTLY FROM E*TRADE</div>',
            unsafe_allow_html=True,
        )
        with st.container(
            horizontal=True,
            vertical_alignment="center",
            gap="small",
            key="ob_add_row",
        ):
            st.button(
                "+ ADD LEG",
                on_click=_add_leg,
                key="ob_add",
                width="content",
                disabled=int(st.session_state.get("ob_leg_count", 1) or 1) >= 4,
            )

        count = int(st.session_state.get("ob_leg_count", 1) or 1)
        chains: dict[date, list[dict[str, Any]]] = {}
        legs: list[dict[str, Any]] = []

        for i in range(count):
            exp_key = f"ob_{i}_expiry"
            type_key = f"ob_{i}_type"
            strike_key = f"ob_{i}_strike"

            if st.session_state.get(exp_key) not in expirations:
                st.session_state[exp_key] = _default_expiry(expirations)
            if st.session_state.get(type_key) not in {"CALL", "PUT"}:
                st.session_state[type_key] = "CALL"

            with st.container(border=True, key=f"ob_leg_box_{i}"):
                st.markdown(
                    f'<div class="ob-leg-title">LEG {i + 1}</div>',
                    unsafe_allow_html=True,
                )
                row = st.columns([1.5, .55, 1.18, .82, .68, .34], gap="small")

                action = row[0].selectbox(
                    "Action",
                    list(_ACTIONS),
                    key=f"ob_{i}_action",
                    format_func=_ACTIONS.get,
                )
                qty = int(
                    row[1].number_input(
                        "Qty",
                        1,
                        5000,
                        1,
                        key=f"ob_{i}_qty",
                    )
                )
                expiry = row[2].selectbox(
                    "Expiration",
                    expirations,
                    key=exp_key,
                    format_func=_date_label,
                )
                call_put = row[4].selectbox(
                    "Type",
                    ["CALL", "PUT"],
                    key=type_key,
                    format_func=str.title,
                )

                if expiry not in chains:
                    try:
                        chains[expiry] = _chain(client, symbol, expiry, touch_session)
                    except Exception as exc:
                        chains[expiry] = []
                        st.warning(f"{_date_label(expiry)} chain unavailable: {exc}")

                strikes = strikes_for(chains[expiry], call_put)
                if not strikes:
                    st.error(
                        f"No {call_put.lower()} strikes available for {_date_label(expiry)}."
                    )
                    continue

                if st.session_state.get(strike_key) not in strikes:
                    offset = (
                        i
                        if strategy == "Call Vertical"
                        else (1 - i if strategy == "Put Vertical" else 0)
                    )
                    st.session_state[strike_key] = _closest(
                        strikes,
                        spot or strikes[len(strikes) // 2],
                        offset,
                    )

                strike = float(
                    row[3].selectbox(
                        "Strike",
                        strikes,
                        key=strike_key,
                        format_func=lambda value: f"{value:,.2f}",
                    )
                )

                row[5].button(
                    "✕",
                    key=f"ob_remove_{i}",
                    on_click=_remove_leg,
                    args=(i,),
                    disabled=count <= 1,
                    width="content",
                    help="Remove this option leg.",
                )

                market = contract_quote(chains[expiry], call_put, strike) or {}
                st.markdown(
                    _market_strip_markup(market),
                    unsafe_allow_html=True,
                )

                legs.append(
                    {
                        "action": action,
                        "quantity": qty,
                        "expiry": expiry,
                        "call_put": call_put,
                        "strike": strike,
                        "bid": market.get("bid"),
                        "ask": market.get("ask"),
                    }
                )

        if len(legs) != count:
            return

        # ==============================
        # PRICE / DURATION
        # ==============================
        net = net_price_snapshot(legs)
        spread = count > 1
        price_choices = (
            ["NET_DEBIT", "NET_CREDIT", "MARKET"]
            if spread
            else ["LIMIT", "STOP", "STOP_LIMIT", "MARKET"]
        )
        default_price = (
            "NET_CREDIT"
            if spread and net.get("side") == "CREDIT"
            else (
                "NET_DEBIT"
                if spread
                else ("STOP" if legs[0]["action"].startswith("SELL") else "LIMIT")
            )
        )
        if st.session_state.get("ob_price_type") not in price_choices:
            st.session_state["ob_price_type"] = default_price

        signature = "v3|" + symbol + "|" + "|".join(
            f"{leg['action']}:{leg['call_put']}:{leg['expiry']}:"
            f"{leg['strike']}:{leg['quantity']}"
            for leg in legs
        )
        if st.session_state.get("_ob_price_seed") != signature:
            mid = net.get("mid")
            st.session_state["ob_limit"] = (
                max(.01, round(abs(float(mid)), 2))
                if mid is not None
                else .01
            )
            try:
                st.session_state["ob_stop"] = max(
                    .01,
                    round(float(legs[0].get("bid")) - .05, 2),
                )
            except (TypeError, ValueError):
                st.session_state["ob_stop"] = st.session_state["ob_limit"]
            st.session_state["_ob_price_seed"] = signature

        st.markdown('<div class="ob-section">PRICE & DURATION</div>', unsafe_allow_html=True)
        st.markdown(
            '<div class="ob-risk-note">ONLY FIELDS REQUIRED BY THE SELECTED ORDER TYPE ARE SHOWN</div>',
            unsafe_allow_html=True,
        )

        price_row = st.columns([1.25, .9, .9, .82, 2.0], gap="small")
        price_type = price_row[0].selectbox(
            "Price Type",
            price_choices,
            key="ob_price_type",
            format_func=_PRICES.get,
        )

        needs_limit = price_type in {
            "LIMIT",
            "STOP_LIMIT",
            "NET_DEBIT",
            "NET_CREDIT",
        }
        needs_stop = price_type in {"STOP", "STOP_LIMIT"}
        limit_price = None
        stop_price = None

        next_col = 1
        if needs_stop:
            stop_price = float(
                price_row[next_col].number_input(
                    "Stop",
                    min_value=.01,
                    step=.01,
                    format="%.2f",
                    key="ob_stop",
                )
            )
            next_col += 1

        if needs_limit:
            limit_label = "Stop-Limit" if price_type == "STOP_LIMIT" else "Limit"
            limit_price = float(
                price_row[next_col].number_input(
                    limit_label,
                    min_value=.01,
                    step=.01,
                    format="%.2f",
                    key="ob_limit",
                )
            )
            next_col += 1

        order_term = price_row[next_col].selectbox(
            "Duration",
            list(_DURATIONS),
            key="ob_duration",
            format_func=_DURATIONS.get,
        )

        natural_text = (
            _money(abs(net["natural"]))
            if net.get("natural") is not None
            else "—"
        )
        mid_text = (
            _money(abs(net["mid"]))
            if net.get("mid") is not None
            else "—"
        )
        opposite_text = (
            _money(abs(net["opposite"]))
            if net.get("opposite") is not None
            else "—"
        )
        st.markdown(
            _metric_grid_markup(
                [
                    ("NATURAL", natural_text, "orange"),
                    ("MID", mid_text, "green"),
                    ("OPPOSITE", opposite_text, "orange"),
                    ("NET", str(net.get("side") or "UNKNOWN"), "blue"),
                ],
                4,
            ),
            unsafe_allow_html=True,
        )

        # ==============================
        # REVIEW / ACTIONS
        # ==============================
        description = " · ".join(
            f"{_ACTIONS[leg['action']]} {leg['quantity']} "
            f"{_date_label(leg['expiry'])} {leg['strike']:g} "
            f"{leg['call_put'].title()}"
            for leg in legs
        )
        st.markdown('<div class="ob-section">ORDER REVIEW</div>', unsafe_allow_html=True)
        st.markdown(
            '<div class="ob-ticket-summary"><b>TICKET //</b> '
            + html.escape(description)
            + "</div>",
            unsafe_allow_html=True,
        )
        st.markdown(
            '<div class="ob-action-note">'
            "E*TRADE PREVIEW VALIDATES ONLY // NO LIVE ORDER IS PLACED"
            "</div>",
            unsafe_allow_html=True,
        )

        with st.container(
            horizontal=True,
            horizontal_alignment="right",
            vertical_alignment="center",
            gap="small",
            key="ob_action_row",
        ):
            local_click = st.button(
                "SAVE DRAFT",
                key="ob_save",
                width="content",
            )
            preview_click = st.button(
                "PREVIEW IN E*TRADE",
                key="ob_preview",
                type="primary",
                width="content",
                disabled=offline or not account_key,
                help="Broker-validates with E*TRADE Preview; never places the order.",
            )

        ticket = {
            "saved_at": datetime.now().astimezone().isoformat(timespec="seconds"),
            "symbol": symbol,
            "strategy": strategy,
            "description": description,
            "price_type": price_type,
            "limit_price": limit_price,
            "stop_price": stop_price,
            "duration": _DURATIONS[order_term],
            "status": "LOCAL DRAFT",
        }

        if local_click:
            _save(dict(ticket))
            st.success("OPTION BOOK SAVED // local draft only // no live order submitted")

        if preview_click:
            try:
                payload = build_preview_payload(
                    symbol=symbol,
                    legs=legs,
                    price_type=price_type,
                    limit_price=limit_price,
                    stop_price=stop_price,
                    order_term=order_term,
                    client_order_id=new_client_order_id(),
                )
                details = preview_details(client.preview_order(account_key, payload))
                touch_session()
                ticket.update(
                    {
                        "status": "E*TRADE PREVIEWED",
                        "preview_id": details.get("preview_id"),
                        "total_order_value": details.get("total_order_value"),
                        "estimated_commission": details.get("estimated_commission"),
                    }
                )
                _save(dict(ticket))
                st.success(
                    "E*TRADE PREVIEW ACCEPTED // Preview ID "
                    f"{details.get('preview_id') or 'N/A'} // NOT PLACED"
                )
                st.markdown(
                    _metric_grid_markup(
                        [
                            (
                                "ESTIMATED ORDER VALUE",
                                _money(details.get("total_order_value")),
                                "green",
                            ),
                            (
                                "ESTIMATED COMMISSION",
                                _money(details.get("estimated_commission")),
                                "orange",
                            ),
                        ],
                        2,
                    ),
                    unsafe_allow_html=True,
                )
                for message in details.get("messages") or []:
                    st.warning(str(message))
            except (ETradeError, ValueError) as exc:
                st.error(f"E*TRADE PREVIEW REJECTED // {exc}")
            except Exception as exc:
                st.error(f"E*TRADE PREVIEW FAILED // {exc}")

        # ==============================
        # SAVED DRAFTS
        # ==============================
        saved = list(st.session_state.get("option_book_saved_tickets") or [])
        if saved:
            with st.expander(
                f"SAVED DRAFTS / PREVIEWS ({len(saved)})",
                expanded=False,
            ):
                frame = pd.DataFrame(saved)
                columns = [
                    column
                    for column in (
                        "saved_at",
                        "symbol",
                        "strategy",
                        "description",
                        "price_type",
                        "limit_price",
                        "stop_price",
                        "duration",
                        "status",
                        "preview_id",
                        "total_order_value",
                        "estimated_commission",
                    )
                    if column in frame.columns
                ]
                st.dataframe(
                    frame[columns],
                    hide_index=True,
                    width="stretch",
                    height=min(360, 34 * len(frame) + 42),
                )
