"""E*TRADE performance workspace for Raj's Terminal.

OWNERSHIP / EDITING NOTES
EDIT THIS FILE FOR: Performance metrics, live chart, transaction analytics, and Performance-only UI.
DO NOT EDIT THIS FILE FOR: OAuth/session behavior, Risk/GEX/Holdings/Orders, navigation, or global theme.

This feature is read-only. It never previews, places, changes, or cancels an order.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date, datetime, timedelta
import math
from typing import Any, Callable
from zoneinfo import ZoneInfo

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from src.etrade_client import ETradeError, normalize_position, total_account_value


_ET = ZoneInfo("America/New_York")
_HISTORY_DAYS = 730
_LIVE_REFRESH_SECONDS = 30
_DEFAULT_ACCOUNT_SUFFIX = "5474"


# ==============================
# UI / CSS
# ==============================

_PERFORMANCE_CSS = """
<style>
.st-key-performance_root {gap:4px!important;padding:0!important;margin:0!important;font-family:"Courier New",monospace}
.st-key-performance_root .perf-section {background:#fb8b1e;color:#000!important;font:900 .82rem/1.08 "Courier New",monospace;letter-spacing:.04em;padding:.30rem .48rem;margin:0;text-transform:uppercase}
.st-key-performance_root .perf-status {border:1px solid #5f431c;background:#080808;color:#b87621!important;font:800 .68rem/1.25 "Courier New",monospace;padding:.34rem .48rem;margin:0}
.st-key-performance_root .perf-kpi {border:1px solid #5f431c;background:#050505;min-height:54px;padding:.35rem .48rem;margin:0}
.st-key-performance_root .perf-kpi-label {color:#b87621!important;font:900 .64rem/1.05 "Courier New",monospace;letter-spacing:.03em}
.st-key-performance_root .perf-kpi-value {color:#f4f4f4!important;font:900 1.02rem/1.15 "Courier New",monospace;margin-top:.12rem}
.st-key-performance_root [data-testid="stDataFrame"],.st-key-performance_root [data-testid="stPlotlyChart"] {border:1px solid #5f431c}
</style>
"""


def _section(title: str) -> None:
    st.html(f'<div class="perf-section">{title}</div>')


def _kpi(label: str, value: str) -> None:
    st.html(
        '<div class="perf-kpi">'
        f'<div class="perf-kpi-label">{label}</div>'
        f'<div class="perf-kpi-value">{value}</div>'
        '</div>'
    )


# ==============================
# TRANSACTION NORMALIZATION
# ==============================

def _find(value: Any, *keys: str) -> Any:
    wanted = {str(key).casefold() for key in keys}
    if isinstance(value, dict):
        for key, child in value.items():
            if str(key).casefold() in wanted:
                return child
        for child in value.values():
            found = _find(child, *keys)
            if found is not None:
                return found
    elif isinstance(value, list):
        for child in value:
            found = _find(child, *keys)
            if found is not None:
                return found
    return None


def _dict(value: Any, *keys: str) -> dict[str, Any]:
    child = _find(value, *keys)
    return child if isinstance(child, dict) else {}


def _num(value: Any, *keys: str) -> float | None:
    try:
        number = float(_find(value, *keys))
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _when(tx: dict[str, Any]) -> datetime | None:
    raw = _find(tx, "transactionDate", "postDate", "settlementDate")
    try:
        value = float(raw)
        if value > 10_000_000_000:
            value /= 1000.0
        return datetime.fromtimestamp(value, tz=_ET)
    except (TypeError, ValueError, OSError, OverflowError):
        return None


def _action(tx: dict[str, Any]) -> str:
    brokerage = _dict(tx, "brokerage")
    raw = str(
        _find(brokerage, "transactionType")
        or _find(tx, "transactionType")
        or _find(tx, "transactionShortDesc")
        or _find(tx, "transactionDescription")
        or _find(tx, "description")
        or ""
    ).upper().replace("-", "_").replace(" ", "_")
    if "BUY_TO_COVER" in raw or "BOUGHT_TO_COVER" in raw:
        return "BUY_TO_COVER"
    if "SELL_SHORT" in raw or "SOLD_SHORT" in raw or "SHORT_SALE" in raw:
        return "SELL_SHORT"
    if "BUY" in raw or "BOUGHT" in raw:
        return "BUY"
    if "SELL" in raw or "SOLD" in raw:
        return "SELL"
    return ""


def _instrument(tx: dict[str, Any]) -> tuple[str, str, str]:
    product = _dict(tx, "product") or _dict(tx, "productId")
    symbol = str(
        _find(product, "displaySymbol", "symbol")
        or _find(tx, "displaySymbol", "symbol")
        or ""
    ).strip().upper()
    security = str(
        _find(product, "securityType", "typeCode")
        or _find(tx, "securityType", "typeCode")
        or "EQ"
    ).strip().upper()
    option = "|".join(
        str(value)
        for key in ("callPut", "strikePrice", "expiryYear", "expiryMonth", "expiryDay")
        if (value := _find(product, key)) not in (None, "")
    )
    return symbol, security, option


def _trade_record(tx: dict[str, Any]) -> dict[str, Any] | None:
    action = _action(tx)
    if not action:
        return None
    brokerage = _dict(tx, "brokerage")
    when = _when(tx)
    symbol, security, option = _instrument(tx)
    qty = abs(_num(brokerage, "quantity") or _num(tx, "quantity") or 0.0)
    price = _num(brokerage, "price")
    if price is None:
        price = _num(tx, "price")
    fee = abs(_num(brokerage, "fee") or _num(tx, "fee", "commission") or 0.0)
    if not symbol or when is None or qty <= 0 or price is None or price < 0:
        return None
    multiplier = _num(brokerage, "optionMultiplier", "multiplier")
    if multiplier is None:
        multiplier = 100.0 if "OPT" in security else 1.0
    return {
        "id": str(_find(tx, "transactionId") or f"{when.timestamp()}:{symbol}:{action}"),
        "when": when,
        "key": (symbol, security, option),
        "symbol": symbol,
        "action": action,
        "quantity": float(qty),
        "price": float(price),
        "fee": float(fee),
        "multiplier": float(multiplier),
    }


def _income_record(tx: dict[str, Any]) -> dict[str, Any] | None:
    if _action(tx):
        return None
    when = _when(tx)
    amount = _num(tx, "amount")
    text = " ".join(
        str(_find(tx, key) or "")
        for key in ("transactionType", "transactionShortDesc", "transactionDescription", "description", "description2", "memo")
    ).lower()
    if when is not None and amount is not None and ("dividend" in text or "interest" in text):
        return {"when": when, "amount": float(amount)}
    return None


# ==============================
# REALIZED TRADE ANALYTICS
# ==============================

def _build_trade_events(transactions: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    trades = [row for tx in transactions if (row := _trade_record(tx)) is not None]
    trades.sort(key=lambda row: (row["when"], row["id"]))
    income = [row for tx in transactions if (row := _income_record(tx)) is not None]
    income.sort(key=lambda row: row["when"])

    longs: dict[tuple[str, str, str], list[dict[str, float]]] = defaultdict(list)
    shorts: dict[tuple[str, str, str], list[dict[str, float]]] = defaultdict(list)
    closes: dict[tuple[str, tuple[str, str, str]], dict[str, Any]] = {}

    def close(trade: dict[str, Any], pnl: float, basis: float) -> None:
        key = (trade["id"], trade["key"])
        row = closes.setdefault(key, {"id": trade["id"], "when": trade["when"], "symbol": trade["symbol"], "pnl": 0.0, "cost_basis": 0.0})
        row["pnl"] += float(pnl)
        row["cost_basis"] += abs(float(basis))

    for trade in trades:
        qty = float(trade["quantity"])
        fee_each = float(trade["fee"]) / qty if qty else 0.0
        px = float(trade["price"]) * float(trade["multiplier"])
        key = trade["key"]
        action = trade["action"]

        if action in {"BUY", "BUY_TO_COVER"}:
            remaining = qty
            while remaining > 1e-9 and shorts[key]:
                lot = shorts[key][0]
                closed = min(remaining, lot["qty"])
                cost = px + fee_each
                close(trade, (lot["unit"] - cost) * closed, lot["unit"] * closed)
                lot["qty"] -= closed
                remaining -= closed
                if lot["qty"] <= 1e-9:
                    shorts[key].pop(0)
            if remaining > 1e-9:
                longs[key].append({"qty": remaining, "unit": px + fee_each})
            continue

        if action == "SELL_SHORT":
            shorts[key].append({"qty": qty, "unit": px - fee_each})
            continue

        if action == "SELL":
            remaining = qty
            while remaining > 1e-9 and longs[key]:
                lot = longs[key][0]
                closed = min(remaining, lot["qty"])
                proceeds = px - fee_each
                close(trade, (proceeds - lot["unit"]) * closed, lot["unit"] * closed)
                lot["qty"] -= closed
                remaining -= closed
                if lot["qty"] <= 1e-9:
                    longs[key].pop(0)
            if remaining > 1e-9:
                shorts[key].append({"qty": remaining, "unit": px - fee_each})

    return sorted(closes.values(), key=lambda row: (row["when"], row["id"])), income


def _period_metrics(
    events: list[dict[str, Any]],
    income: list[dict[str, Any]],
    start: date,
    *,
    account_value: float | None,
) -> dict[str, float | None]:
    selected = [row for row in events if row["when"].date() >= start]
    selected_income = [row for row in income if row["when"].date() >= start]
    realized = sum(float(row["pnl"]) for row in selected)
    cash_income = sum(float(row["amount"]) for row in selected_income)
    net = realized + cash_income
    basis = sum(float(row["cost_basis"]) for row in selected)
    wins = [float(row["pnl"]) for row in selected if float(row["pnl"]) > 1e-9]
    losses = [float(row["pnl"]) for row in selected if float(row["pnl"]) < -1e-9]
    decided = len(wins) + len(losses)

    running = peak = worst_dd = 0.0
    points = [(row["when"], float(row["pnl"])) for row in selected]
    points += [(row["when"], float(row["amount"])) for row in selected_income]
    for _, amount in sorted(points, key=lambda item: item[0]):
        running += amount
        peak = max(peak, running)
        worst_dd = min(worst_dd, running - peak)

    return {
        "net_pnl": net,
        "return_pct": (100.0 * net / basis) if basis > 1e-9 else None,
        "win_rate": (100.0 * len(wins) / decided) if decided else None,
        "profit_factor": (sum(wins) / abs(sum(losses))) if losses else (math.inf if wins else None),
        "max_drawdown_pct": (100.0 * worst_dd / account_value) if account_value and account_value > 1e-9 else None,
        "cost_basis": basis,
    }


# ==============================
# LIVE PORTFOLIO + CHART
# ==============================

def _client_call(client: Any, method: str, account_key: str) -> Any:
    fn = getattr(client, method)
    try:
        return fn(account_key, force_refresh=True)
    except TypeError:
        return fn(account_key)


def _snapshot(client: Any, account_key: str) -> dict[str, Any]:
    raw = _client_call(client, "get_portfolio", account_key)
    balance = _client_call(client, "get_balance", account_key)
    positions = [normalize_position(row) for row in raw if isinstance(row, dict)]
    day_gain = sum(float(row.get("day_gain") or 0.0) for row in positions)
    market_value = sum(float(row.get("market_value") or 0.0) for row in positions)
    total_gain = sum(float(row.get("total_gain") or 0.0) for row in positions)
    total_cost = sum(float(row.get("total_cost") or 0.0) for row in positions)
    day_base = market_value - day_gain
    return {
        "day_gain": day_gain,
        "day_return": (100.0 * day_gain / day_base) if abs(day_base) > 1e-9 else None,
        "unrealized": total_gain,
        "total_cost": total_cost,
        "account_value": total_account_value(balance),
    }


def _money(value: float | None) -> str:
    if value is None or not math.isfinite(float(value)):
        return "—"
    value = float(value)
    sign = "+" if value > 0 else "-" if value < 0 else ""
    return sign + "$" + f"{abs(value):,.0f}"


def _pct(value: float | None) -> str:
    if value is None or not math.isfinite(float(value)):
        return "—"
    value = float(value)
    return ("+" if value > 0 else "") + f"{value:.2f}%"


def _ratio(value: float | None) -> str:
    if value is None:
        return "—"
    return "∞" if math.isinf(float(value)) else f"{float(value):.2f}"


def _scorecard(today: dict[str, Any], mtd: dict[str, Any], ytd: dict[str, Any], all_time: dict[str, Any]) -> pd.DataFrame:
    return pd.DataFrame(
        [
            ["Net P&L", _money(today.get("net_pnl")), _money(mtd.get("net_pnl")), _money(ytd.get("net_pnl")), _money(all_time.get("net_pnl"))],
            ["Return", _pct(today.get("return_pct")), _pct(mtd.get("return_pct")), _pct(ytd.get("return_pct")), _pct(all_time.get("return_pct"))],
            ["Win Rate", "—", _pct(mtd.get("win_rate")), _pct(ytd.get("win_rate")), _pct(all_time.get("win_rate"))],
            ["Profit Factor", "—", _ratio(mtd.get("profit_factor")), _ratio(ytd.get("profit_factor")), _ratio(all_time.get("profit_factor"))],
            ["Max Drawdown", "—", _pct(mtd.get("max_drawdown_pct")), _pct(ytd.get("max_drawdown_pct")), _pct(all_time.get("max_drawdown_pct"))],
        ],
        columns=["PERFORMANCE", "TODAY", "MTD", "YTD", "ALL-TIME"],
    )


def _curve(events: list[dict[str, Any]], income: list[dict[str, Any]], unrealized: float) -> pd.DataFrame:
    daily: dict[date, float] = defaultdict(float)
    for row in events:
        daily[row["when"].date()] += float(row["pnl"])
    for row in income:
        daily[row["when"].date()] += float(row["amount"])
    running = 0.0
    rows: list[tuple[datetime, float]] = []
    for day in sorted(daily):
        running += daily[day]
        rows.append((datetime(day.year, day.month, day.day, 16, tzinfo=_ET), running))
    rows.append((datetime.now(_ET), running + float(unrealized)))
    return pd.DataFrame(rows, columns=["Date", "Net P&L"])


def _chart(frame: pd.DataFrame, key: str) -> None:
    fig = go.Figure(go.Scatter(
        x=frame["Date"],
        y=frame["Net P&L"],
        mode="lines",
        line={"color": "#fb8b1e", "width": 2.4},
        hovertemplate="%{x|%b %d %Y %I:%M %p}<br>NET P&L $%{y:,.2f}<extra></extra>",
    ))
    fig.add_hline(y=0, line_width=1, line_color="#444444")
    fig.update_layout(
        height=350,
        margin={"l": 10, "r": 10, "t": 34, "b": 8},
        paper_bgcolor="#000000",
        plot_bgcolor="#000000",
        font={"family": "Courier New", "color": "#d7d7d7", "size": 11},
        title={"text": "LIVE CUMULATIVE NET P&L // REALIZED HISTORY + CURRENT UNREALIZED", "font": {"color": "#fb8b1e", "size": 13}},
        xaxis={"gridcolor": "#1c1c1c", "title": ""},
        yaxis={"gridcolor": "#1c1c1c", "tickprefix": "$", "tickformat": ",.0f", "title": ""},
        showlegend=False,
    )
    st.plotly_chart(fig, width="stretch", config={"displayModeBar": False}, key=key)


# ==============================
# DATA LOADING / PUBLIC RENDER
# ==============================

def _cache_key(account_key: str) -> str:
    return f"performance_transactions::{account_key}"


def _load_transactions(client: Any, account_key: str, force: bool) -> list[dict[str, Any]]:
    key = _cache_key(account_key)
    if force:
        st.session_state.pop(key, None)
    if isinstance(st.session_state.get(key), list):
        return st.session_state[key]
    end = datetime.now(_ET).date()
    rows = client.get_transactions(account_key, start_date=end - timedelta(days=_HISTORY_DAYS), end_date=end, sort_order="ASC")
    rows = [row for row in rows if isinstance(row, dict)]
    st.session_state[key] = rows
    return rows


def _account_label(account: dict[str, Any]) -> str:
    name = str(account.get("accountName") or account.get("accountDesc") or account.get("accountType") or "E*TRADE ACCOUNT").strip()
    raw = str(account.get("accountId") or "")
    return f"{name} // ••••{raw[-4:]}" if raw else name


def _default_account(accounts: list[dict[str, Any]]) -> str:
    for account in accounts:
        if str(account.get("accountId") or "").endswith(_DEFAULT_ACCOUNT_SUFFIX):
            return str(account.get("accountIdKey") or "")
    return str(accounts[0].get("accountIdKey") or "") if accounts else ""


@st.fragment(run_every=_LIVE_REFRESH_SECONDS)
def _live(client: Any, account: dict[str, Any], transactions: list[dict[str, Any]], touch_session: Callable[[], Any] | None) -> None:
    account_key = str(account.get("accountIdKey") or "").strip()
    try:
        snapshot = _snapshot(client, account_key)
        if touch_session:
            touch_session()
    except Exception as exc:
        st.error(f"PERFORMANCE LIVE DATA UNAVAILABLE // {exc}")
        return

    events, income = _build_trade_events(transactions)
    now = datetime.now(_ET)
    today_date = now.date()
    history_dates = [stamp.date() for tx in transactions if (stamp := _when(tx)) is not None]
    history_start = min(history_dates) if history_dates else today_date

    today = {"net_pnl": snapshot["day_gain"], "return_pct": snapshot["day_return"]}
    mtd = _period_metrics(events, income, today_date.replace(day=1), account_value=snapshot["account_value"])
    ytd = _period_metrics(events, income, date(today_date.year, 1, 1), account_value=snapshot["account_value"])
    all_time = _period_metrics(events, income, history_start, account_value=snapshot["account_value"])
    all_time["net_pnl"] = float(all_time.get("net_pnl") or 0.0) + float(snapshot["unrealized"])
    basis = float(all_time.get("cost_basis") or 0.0) + max(0.0, float(snapshot["total_cost"] or 0.0))
    all_time["return_pct"] = (100.0 * float(all_time["net_pnl"]) / basis) if basis > 1e-9 else None

    cols = st.columns(4, gap="small")
    for col, label, value in zip(
        cols,
        ("ACCOUNT VALUE", "TODAY NET P&L", "CURRENT UNREALIZED", "LIVE UPDATE"),
        (_money(snapshot["account_value"]), _money(snapshot["day_gain"]), _money(snapshot["unrealized"]), now.strftime("%I:%M:%S %p ET")),
    ):
        with col:
            _kpi(label, value)

    _section("PERFORMANCE SCORECARD")
    st.dataframe(_scorecard(today, mtd, ytd, all_time), hide_index=True, width="stretch", row_height=36)

    _section("LIVE PERFORMANCE CURVE")
    suffix = str(account.get("accountId") or account_key)[-6:]
    _chart(_curve(events, income, float(snapshot["unrealized"])), f"performance_curve_{suffix}")

    st.html(
        '<div class="perf-status">'
        f'HISTORY COVERAGE // EARLIEST E*TRADE TRANSACTION LOADED: {history_start:%b %d, %Y} // '
        f'{len(transactions):,} TRANSACTIONS // {len(events):,} CLOSED TRADE EVENTS // '
        'TODAY = live mark-to-market. MTD/YTD trade stats = realized FIFO trade P&L plus dividend/interest cash. '
        'ALL-TIME adds current unrealized P&L. Return is cost-basis return, not TWR/XIRR; Max Drawdown is realized-P&L drawdown versus current account value. '
        'If the account predates the E*TRADE API history window, ALL-TIME is partial until older history is seeded; missing history is never invented.'
        '</div>'
    )


def render_performance(
    client: Any,
    *,
    refresh_accounts: Callable[[Any], list[dict[str, Any]]] | None = None,
    touch_session: Callable[[], Any] | None = None,
) -> None:
    st.html(_PERFORMANCE_CSS)
    with st.container(key="performance_root", gap=None):
        if client is None:
            st.info("CONNECT E*TRADE TO LOAD LIVE PERFORMANCE.")
            return

        accounts = [row for row in (st.session_state.get("etrade_accounts") or []) if isinstance(row, dict)]
        if not accounts and refresh_accounts is not None:
            try:
                accounts = refresh_accounts(client)
            except Exception as exc:
                st.error(f"E*TRADE ACCOUNTS UNAVAILABLE // {exc}")
                return
        accounts = [row for row in accounts if str(row.get("accountIdKey") or "").strip()]
        if not accounts:
            st.info("NO E*TRADE BROKERAGE ACCOUNTS ARE AVAILABLE.")
            return

        by_key = {str(row.get("accountIdKey") or "").strip(): row for row in accounts}
        state_key = "performance_account_key"
        if str(st.session_state.get(state_key) or "") not in by_key:
            st.session_state[state_key] = _default_account(accounts)

        picker, refresh = st.columns([5.2, 1.5], gap="small", vertical_alignment="bottom")
        with picker:
            selected = st.selectbox("E*TRADE Account", list(by_key), key=state_key, format_func=lambda key: _account_label(by_key[key]))
        with refresh:
            force = st.button("REFRESH PERFORMANCE", type="primary", width="stretch", key="performance_refresh")

        if force:
            st.session_state.pop(_cache_key(selected), None)
            invalidate = getattr(client, "invalidate", None)
            if callable(invalidate):
                invalidate("portfolio", "balance")

        try:
            transactions = _load_transactions(client, selected, force)
            if touch_session:
                touch_session()
        except AttributeError:
            transactions = []
            st.warning("LIVE TRANSACTION HISTORY IS NOT AVAILABLE IN OFFLINE SNAPSHOT MODE.")
        except ETradeError as exc:
            transactions = []
            st.warning(f"E*TRADE TRANSACTION HISTORY UNAVAILABLE // {exc}")
        except Exception as exc:
            transactions = []
            st.warning(f"PERFORMANCE HISTORY LOAD FAILED // {exc}")

        _live(client, by_key[selected], transactions, touch_session)


__all__ = ["render_performance", "_build_trade_events", "_period_metrics"]
