"""Protective Puts workspace for Raj's Terminal.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- Protective Puts ticker, purchase-price, shares, expiration-scope controls;
- E*TRADE put-chain loading and read-only married-put analytics;
- Protective Puts-only compact Bloomberg-style presentation.

DO NOT EDIT THIS FILE FOR:
- Risk Sizing UI/math;
- E*TRADE OAuth/session plumbing;
- live order placement, preview, or cancellation;
- GEX, Holdings, Performance, Rebalance, Vertical Options, or shared theme.

The visual contract is copied locally from E*TRADE Risk Sizing: Courier New,
Bloomberg orange/black, 38px controls, 30px section bars, 52px metric cards,
4px vertical rhythm, and 8px horizontal rhythm.
"""

from __future__ import annotations

import html
import time
from datetime import date
from typing import Any

import pandas as pd
import streamlit as st

from src.etrade_client import ETradeError, option_expiration_dates, quote_summary
from src.option_book import extract_option_rows
from src.protective_puts import build_put_analysis, validate_share_quantity
from src.ticker_autocomplete import company_name, record_lookup


_CHAIN_CACHE_SECONDS = 5 * 60
_EXPIRATION_CACHE_SECONDS = 6 * 60 * 60

_PROTECTIVE_PUTS_CSS = """
<style>
.st-key-protective_puts_workspace{
    --pp-orange:#fb8b1e;--pp-green:#4af6c3;--pp-red:#ff433d;--pp-blue:#0068ff;
    --pp-muted:#8f99a8;margin:0!important;padding:0!important;
    font-family:"Courier New",monospace!important;
}
.st-key-protective_puts_workspace [data-testid="stVerticalBlock"]{gap:4px!important;}
.st-key-protective_puts_workspace [data-testid="stHorizontalBlock"]{gap:8px!important;}
.st-key-protective_puts_workspace [data-testid="stColumn"]{min-width:0!important;}
.st-key-protective_puts_workspace [data-testid="stWidgetLabel"],
.st-key-protective_puts_workspace [data-testid="stWidgetLabel"] *{
    color:var(--pp-orange)!important;-webkit-text-fill-color:var(--pp-orange)!important;
    font-family:"Courier New",monospace!important;font-size:.66rem!important;
    font-weight:900!important;text-transform:uppercase!important;
}
.st-key-protective_puts_workspace input,
.st-key-protective_puts_workspace [data-baseweb="select"]>div,
.st-key-protective_puts_workspace [data-baseweb="input"]>div{
    min-height:38px!important;height:38px!important;border-radius:0!important;
    border-color:var(--pp-orange)!important;font-family:"Courier New",monospace!important;
    font-weight:900!important;
}
.st-key-protective_puts_workspace [data-testid="stButton"] button,
.st-key-protective_puts_workspace [data-testid="stDownloadButton"] button{
    min-height:38px!important;height:38px!important;border:1px solid var(--pp-orange)!important;
    border-radius:0!important;font-family:"Courier New",monospace!important;
    font-size:.70rem!important;font-weight:900!important;text-transform:uppercase!important;
}
.st-key-protective_puts_workspace .st-key-pp_scan button{
    background:var(--pp-orange)!important;color:#000!important;-webkit-text-fill-color:#000!important;
}
.pp-company-field{width:100%;min-width:0;font-family:"Courier New",monospace;}
.pp-company-label{display:flex;align-items:center;min-height:20px;margin:0 0 3px 0;
    color:var(--pp-orange)!important;-webkit-text-fill-color:var(--pp-orange)!important;
    font:900 .66rem/1.25 "Courier New",monospace;text-transform:uppercase;}
.pp-company-box{display:flex;align-items:center;width:100%;height:38px;box-sizing:border-box;
    padding:0 10px;border:1px solid var(--pp-orange);background:#050505;
    color:var(--pp-orange)!important;-webkit-text-fill-color:var(--pp-orange)!important;
    font:900 .80rem/1.15 "Courier New",monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
.pp-section{display:flex;align-items:center;width:100%;height:30px;box-sizing:border-box;
    margin:0 0 4px 0;padding:0 10px;border:1px solid var(--pp-orange);background:var(--pp-orange);
    color:#000!important;-webkit-text-fill-color:#000!important;
    font:900 .78rem/1 "Courier New",monospace;text-transform:uppercase;}
.pp-note{min-height:20px;margin:0 0 4px 0;color:var(--pp-orange)!important;
    -webkit-text-fill-color:var(--pp-orange)!important;font:800 .62rem/1.2 "Courier New",monospace;}
.pp-note .muted{color:var(--pp-muted)!important;-webkit-text-fill-color:var(--pp-muted)!important;}
.pp-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px;margin:0 0 4px 0;}
.pp-card{min-width:0;height:52px;box-sizing:border-box;padding:6px 8px;border:1px solid var(--pp-orange);
    background:#000;overflow:hidden;}
.pp-label{color:var(--pp-orange)!important;-webkit-text-fill-color:var(--pp-orange)!important;
    font:900 .62rem/1 "Courier New",monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
.pp-value{color:var(--pp-green)!important;-webkit-text-fill-color:var(--pp-green)!important;
    font:900 1.02rem/1 "Courier New",monospace;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}
.pp-red .pp-value{color:var(--pp-red)!important;-webkit-text-fill-color:var(--pp-red)!important;}
.pp-blue .pp-value{color:var(--pp-blue)!important;-webkit-text-fill-color:var(--pp-blue)!important;}
.pp-orange .pp-value{color:var(--pp-orange)!important;-webkit-text-fill-color:var(--pp-orange)!important;}
@media (max-width:1100px){.pp-grid{grid-template-columns:repeat(3,minmax(0,1fr));}}
@media (max-width:760px){.pp-grid{grid-template-columns:repeat(2,minmax(0,1fr));}}
</style>
"""


def _money(value: Any) -> str:
    try:
        return "$" + f"{float(value):,.2f}"
    except (TypeError, ValueError):
        return "—"


def _normalize_symbol() -> None:
    value = str(st.session_state.get("pp_symbol") or "").strip().upper()
    st.session_state["pp_symbol"] = value or "SPY"


def _company_markup(name: str) -> str:
    safe = html.escape(str(name or "—"))
    return (
        '<div class="pp-company-field"><div class="pp-company-label">Company / ETF</div>'
        f'<div class="pp-company-box" title="{safe}">{safe}</div></div>'
    )


def _metric_markup(items: list[tuple[str, str, str]]) -> str:
    cells = "".join(
        '<div class="pp-card pp-' + html.escape(tone) + '"><div class="pp-label">'
        + html.escape(label) + '</div><div class="pp-value">' + html.escape(value) + "</div></div>"
        for label, value, tone in items
    )
    return '<div class="pp-grid">' + cells + "</div>"


def _expirations(client, symbol: str, touch_session) -> list[date]:
    now = time.time()
    cache = st.session_state.setdefault("_pp_expiration_cache", {})
    cached = cache.get(symbol)
    if cached and now - float(cached.get("loaded_at", 0.0)) < _EXPIRATION_CACHE_SECONDS:
        return list(cached.get("dates") or [])
    payload = client.get_option_expirations(symbol)
    touch_session()
    dates: list[date] = []
    for year, month, day in option_expiration_dates(payload):
        try:
            dates.append(date(year, month, day))
        except ValueError:
            continue
    dates = sorted(set(dates))
    cache[symbol] = {"loaded_at": now, "dates": dates}
    return dates


def _put_chain(client, symbol: str, expiry: date, touch_session) -> tuple[list[dict[str, Any]], bool]:
    cache = st.session_state.setdefault("_pp_chain_cache", {})
    key = f"{symbol}:{expiry.isoformat()}"
    now = time.time()
    cached = cache.get(key)
    if cached and now - float(cached.get("loaded_at", 0.0)) < _CHAIN_CACHE_SECONDS:
        return list(cached.get("rows") or []), True
    payload = client.get_option_chain(
        symbol, expiry.year, expiry.month, expiry.day, no_of_strikes=None, chain_type="PUT"
    )
    touch_session()
    rows = [
        row for row in extract_option_rows(payload, expiry)
        if str(row.get("call_put") or "").upper() == "PUT"
    ]
    cache[key] = {"loaded_at": now, "rows": rows}
    return rows, False


def _default_expiry(expirations: list[date]) -> date:
    today = date.today()
    return next((item for item in expirations if (item - today).days >= 30), expirations[0])


def _render_scan_result(result: dict[str, Any]) -> None:
    frame = result.get("frame")
    if not isinstance(frame, pd.DataFrame) or frame.empty:
        st.info("No usable put contracts were returned for the selected scan.")
        return

    symbol = str(result.get("symbol") or "")
    shares = int(result.get("shares") or 0)
    stock_price = float(result.get("stock_price") or 0.0)
    best_ask = frame.dropna(subset=["Max Loss (Ask)"]).copy()
    best_row = None if best_ask.empty else best_ask.loc[best_ask["Max Loss (Ask)"].idxmin()]

    st.html('<div class="pp-section">PROTECTIVE PUT SUMMARY</div>')
    st.html(
        _metric_markup(
            [
                ("Underlying", symbol, "green"),
                ("Purchase Price", _money(stock_price), "blue"),
                ("Shares Protected", f"{shares:,}", "orange"),
                ("Put Contracts", f"{shares // 100:,}", "orange"),
                (
                    "Lowest ASK Max Loss",
                    "—" if best_row is None else _money(best_row["Max Loss (Ask)"]),
                    "red",
                ),
                (
                    "Lowest ASK Max Loss %",
                    "—" if best_row is None else f"{float(best_row['Max Loss % (Ask)']):.2f}%",
                    "red",
                ),
            ]
        )
    )
    if best_row is not None:
        st.caption(
            "LOWEST DISPLAYED ASK MAX LOSS // "
            f"{best_row['Expiration']} // {float(best_row['Strike']):,.2f} PUT // "
            "loss-minimization reference only; deeper ITM puts generally cost more."
        )

    st.html('<div class="pp-section">PUT CHAIN + MARRIED-PUT LOSS FLOOR</div>')
    display_columns = [
        "Expiration", "DTE", "Strike", "Bid", "Ask", "Last", "Volume", "Open Interest",
        "Put Cost (Ask)", "Max Loss (Ask)", "Max Loss % (Ask)", "Breakeven (Ask)",
        "Put Cost (Last)", "Max Loss (Last)",
    ]
    display = frame[display_columns].copy()
    st.dataframe(
        display,
        hide_index=True,
        width="stretch",
        height=min(920, max(260, 35 * len(display) + 45)),
        column_config={
            "Strike": st.column_config.NumberColumn(format="$%.2f"),
            "Bid": st.column_config.NumberColumn(format="$%.2f"),
            "Ask": st.column_config.NumberColumn(format="$%.2f"),
            "Last": st.column_config.NumberColumn(format="$%.2f"),
            "Put Cost (Ask)": st.column_config.NumberColumn(format="$%.2f"),
            "Max Loss (Ask)": st.column_config.NumberColumn(format="$%.2f"),
            "Max Loss % (Ask)": st.column_config.NumberColumn(format="%.2f%%"),
            "Breakeven (Ask)": st.column_config.NumberColumn(format="$%.2f"),
            "Put Cost (Last)": st.column_config.NumberColumn(format="$%.2f"),
            "Max Loss (Last)": st.column_config.NumberColumn(format="$%.2f"),
        },
    )
    st.download_button(
        "EXPORT PROTECTIVE PUT CSV",
        data=frame.to_csv(index=False),
        file_name=f"{symbol}_protective_puts.csv",
        mime="text/csv",
        width="stretch",
        key="pp_download_csv",
    )
    st.caption(
        "MAX LOSS (ASK) = STOCK COST + PUT ASK COST − STRIKE FLOOR VALUE. "
        "Displayed as a positive dollar loss assuming the put is held through expiration. "
        "LAST is a historical trade reference; ASK is the conservative purchase-side reference."
    )
    errors = list(result.get("errors") or [])
    if errors:
        with st.expander("CHAIN FETCH WARNINGS"):
            for error in errors:
                st.warning(str(error))


@st.fragment
def _render_protective_puts_fragment(client, touch_session) -> None:
    with st.container(key="protective_puts_workspace"):
        st.html(_PROTECTIVE_PUTS_CSS)
        st.markdown(
            '<div class="pp-note">READ-ONLY PROTECTIVE PUT ANALYTICS // '
            '<span class="muted">LEGACY MARRIED-PUT ENGINE ADAPTED TO LIVE E*TRADE QUOTES + CHAINS</span></div>',
            unsafe_allow_html=True,
        )
        if client is None:
            st.info("Connect E*TRADE to load live stock quotes and protective-put chains.")
            return

        top = st.columns([1.0, 2.0, .9, 1.0, .9, 1.15], gap="small")
        with top[0]:
            if "pp_symbol" not in st.session_state:
                st.session_state["pp_symbol"] = "SPY"
            symbol = str(
                st.text_input(
                    "Ticker",
                    key="pp_symbol",
                    placeholder="SPY",
                    on_change=_normalize_symbol,
                    help="Enter the ticker symbol only. Company / ETF name resolves automatically.",
                )
                or "SPY"
            ).strip().upper()

        try:
            quote = quote_summary(client.get_quote(symbol))
            touch_session()
            last = float(quote.get("last") or 0.0)
            resolved_name = str(quote.get("description") or company_name(symbol) or "").strip()
            record_lookup(symbol, resolved_name)
        except Exception as exc:
            with top[1]:
                st.html(_company_markup(company_name(symbol)))
            st.error(f"Quote unavailable for {symbol}: {exc}")
            return

        with top[1]:
            st.html(_company_markup(resolved_name))
        with top[2]:
            st.text_input("Last", value=_money(last), disabled=True, key="pp_last_display")

        if st.session_state.get("_pp_price_seed_symbol") != symbol:
            st.session_state["pp_purchase_price"] = round(last, 2)
            st.session_state["_pp_price_seed_symbol"] = symbol
        with top[3]:
            stock_price = float(
                st.number_input(
                    "Purchase Price", min_value=0.01, step=0.01, format="%.2f",
                    key="pp_purchase_price",
                    help="Your stock cost basis per share. New tickers seed from the E*TRADE last price.",
                )
            )
        with top[4]:
            if "pp_shares" not in st.session_state:
                st.session_state["pp_shares"] = 100
            shares = int(
                st.number_input(
                    "Shares", min_value=100, step=100, key="pp_shares",
                    help="Full protection uses one listed put contract per 100 shares.",
                )
            )
        try:
            validate_share_quantity(shares)
        except ValueError as exc:
            st.error(str(exc))
            return

        try:
            expirations = _expirations(client, symbol, touch_session)
        except Exception as exc:
            st.error(f"Option expirations unavailable for {symbol}: {exc}")
            return
        if not expirations:
            st.info("No listed put expirations are available for this symbol.")
            return

        with top[5]:
            scope = st.selectbox(
                "Expiration Scope", ["ONE EXPIRATION", "ALL EXPIRATIONS"], key="pp_expiry_scope"
            )

        chosen_expiry = None
        if scope == "ONE EXPIRATION":
            if st.session_state.get("pp_expiry") not in expirations:
                st.session_state["pp_expiry"] = _default_expiry(expirations)
            expiry_row = st.columns([1.15, 1.0, 3.85], gap="small")
            chosen_expiry = expiry_row[0].selectbox(
                "Expiration", expirations, key="pp_expiry",
                format_func=lambda value: value.strftime("%m-%d-%y"),
            )
            expiry_row[1].text_input(
                "DTE", value=str(max(0, (chosen_expiry - date.today()).days)),
                disabled=True, key="pp_dte_display",
            )
            expiry_row[2].caption(
                "ONE EXPIRATION is faster. ALL EXPIRATIONS reproduces the legacy married-put scan "
                "across every listed E*TRADE expiry."
            )
        else:
            st.caption(
                f"ALL EXPIRATIONS // {len(expirations):,} listed E*TRADE expirations scan only "
                "when you press RUN PROTECTIVE PUT SCAN."
            )

        current_fingerprint = (
            symbol, round(stock_price, 4), shares, scope,
            "" if chosen_expiry is None else chosen_expiry.isoformat(),
        )
        if st.button("RUN PROTECTIVE PUT SCAN", type="primary", width="stretch", key="pp_scan"):
            selected = [chosen_expiry] if chosen_expiry is not None else expirations
            progress = st.progress(0.0, text="Initializing protective-put scan...")
            frames: list[pd.DataFrame] = []
            errors: list[str] = []
            for index, expiry in enumerate(selected, start=1):
                try:
                    rows, _ = _put_chain(client, symbol, expiry, touch_session)
                    frame = build_put_analysis(
                        rows, expiry=expiry, stock_price=stock_price, shares=shares, today=date.today()
                    )
                    if not frame.empty:
                        frames.append(frame)
                except ETradeError as exc:
                    errors.append(f"{expiry.isoformat()}: {exc}")
                except Exception as exc:
                    errors.append(f"{expiry.isoformat()}: {exc}")
                progress.progress(
                    index / len(selected),
                    text=f"Scanning {expiry.strftime('%m-%d-%y')} // {index}/{len(selected)}",
                )
            progress.empty()
            st.session_state["pp_scan_result"] = {
                "fingerprint": current_fingerprint,
                "symbol": symbol,
                "stock_price": stock_price,
                "shares": shares,
                "frame": pd.concat(frames, ignore_index=True) if frames else pd.DataFrame(),
                "errors": errors,
            }

        result = st.session_state.get("pp_scan_result")
        if isinstance(result, dict):
            if result.get("fingerprint") == current_fingerprint:
                _render_scan_result(result)
            else:
                st.caption("INPUTS CHANGED // run the Protective Put scan again to refresh the table.")


def render_protective_puts(client, touch_session) -> None:
    """Render the production Protective Puts read-only analytics workspace."""
    _render_protective_puts_fragment(client, touch_session)


__all__ = ["render_protective_puts"]
