"""Protective-put analytics for Raj's Terminal.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- protective-put cost, breakeven, downside-floor, and max-loss calculations;
- normalization of already-fetched E*TRADE put rows for display/export.

DO NOT EDIT THIS FILE FOR:
- Streamlit layout/theme;
- E*TRADE OAuth/session behavior;
- order preview/place/cancel behavior;
- Risk Sizing, Vertical Options, GEX, Holdings, or navigation.
"""

from __future__ import annotations

from datetime import date
from typing import Any, Iterable

import pandas as pd


CONTRACT_SIZE = 100


def validate_share_quantity(shares: int) -> int:
    """Require whole 100-share lots so each share is covered by one listed put."""
    try:
        value = int(shares)
    except (TypeError, ValueError) as exc:
        raise ValueError("Shares must be a whole number.") from exc
    if value < CONTRACT_SIZE or value % CONTRACT_SIZE != 0:
        raise ValueError(
            "Protective Puts requires shares in 100-share lots (100, 200, 300, ...)."
        )
    return value


def protective_put_metrics(
    *,
    stock_price: float,
    strike: float,
    premium_per_share: float,
    shares: int,
) -> dict[str, float | int]:
    """Return fully hedged protective-put economics for one premium reference."""
    protected_shares = validate_share_quantity(shares)
    stock_price = float(stock_price)
    strike = float(strike)
    premium_per_share = float(premium_per_share)
    if stock_price <= 0 or strike <= 0:
        raise ValueError("Stock price and strike must be greater than zero.")
    if premium_per_share < 0:
        raise ValueError("Put premium cannot be negative.")

    contracts = protected_shares // CONTRACT_SIZE
    stock_cost = stock_price * protected_shares
    put_cost = premium_per_share * CONTRACT_SIZE * contracts
    floor_value = strike * protected_shares
    max_loss = max(0.0, stock_cost + put_cost - floor_value)
    max_loss_per_share = max_loss / protected_shares
    max_loss_pct = (max_loss / stock_cost * 100.0) if stock_cost else 0.0
    breakeven = stock_price + (put_cost / protected_shares)

    return {
        "contracts": contracts,
        "stock_cost": stock_cost,
        "put_cost": put_cost,
        "floor_value": floor_value,
        "max_loss": max_loss,
        "max_loss_per_share": max_loss_per_share,
        "max_loss_pct": max_loss_pct,
        "breakeven": breakeven,
    }


def build_put_analysis(
    rows: Iterable[dict[str, Any]],
    *,
    expiry: date,
    stock_price: float,
    shares: int,
    today: date,
) -> pd.DataFrame:
    """Convert normalized E*TRADE puts into the legacy married-put analytics."""
    protected_shares = validate_share_quantity(shares)
    records: list[dict[str, Any]] = []
    dte = max(0, (expiry - today).days)

    for row in rows:
        if str(row.get("call_put") or "").upper() != "PUT":
            continue
        try:
            strike = float(row.get("strike"))
        except (TypeError, ValueError):
            continue

        def metrics_for(value: Any):
            try:
                premium = float(value)
            except (TypeError, ValueError):
                return None
            if premium < 0:
                return None
            return protective_put_metrics(
                stock_price=stock_price,
                strike=strike,
                premium_per_share=premium,
                shares=protected_shares,
            )

        ask_metrics = metrics_for(row.get("ask"))
        last_metrics = metrics_for(row.get("last"))
        records.append(
            {
                "Expiration": expiry.strftime("%m-%d-%y"),
                "DTE": dte,
                "Contract": str(row.get("osi") or ""),
                "Strike": strike,
                "Bid": row.get("bid"),
                "Ask": row.get("ask"),
                "Last": row.get("last"),
                "Volume": row.get("volume"),
                "Open Interest": row.get("open_interest"),
                "Contracts": protected_shares // CONTRACT_SIZE,
                "Put Cost (Ask)": None if ask_metrics is None else ask_metrics["put_cost"],
                "Max Loss (Ask)": None if ask_metrics is None else ask_metrics["max_loss"],
                "Max Loss % (Ask)": None if ask_metrics is None else ask_metrics["max_loss_pct"],
                "Breakeven (Ask)": None if ask_metrics is None else ask_metrics["breakeven"],
                "Put Cost (Last)": None if last_metrics is None else last_metrics["put_cost"],
                "Max Loss (Last)": None if last_metrics is None else last_metrics["max_loss"],
                "Max Loss % (Last)": None if last_metrics is None else last_metrics["max_loss_pct"],
                "Breakeven (Last)": None if last_metrics is None else last_metrics["breakeven"],
            }
        )

    if not records:
        return pd.DataFrame()
    return pd.DataFrame.from_records(records).sort_values(["Strike"]).reset_index(drop=True)


__all__ = [
    "CONTRACT_SIZE",
    "build_put_analysis",
    "protective_put_metrics",
    "validate_share_quantity",
]
