"""Smart E*TRADE portfolio rebalancer for Raj's Terminal.

OWNERSHIP / EDITING NOTES
EDIT THIS FILE FOR:
- Rebalance Portfolio targets, drift bands, loss-aware rules, cash-first math, and feature-local UI.
- Rebalance-only E*TRADE holdings/balance loading and persistent target/band settings.

DO NOT EDIT THIS FILE FOR:
- Risk Sizing formulas/order workflows;
- E*TRADE OAuth/session semantics;
- Holdings/GEX/Performance/navigation/global theme.

The rebalancer is READ-ONLY. It never previews, places, changes, or cancels orders.
It intentionally reuses the production E*TRADE Risk Sizing account key, holdings
normalization, LONG-TERM intent memory, and account balance source so both tabs
describe the same book.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path
import time
from typing import Any, Callable

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components

from src.etrade_client import ETradeError
from src.risk_sizing import classify_holdings
from src.risk_sizing_ui import _normalized_holdings
from src.risk_sizing_ui_v2 import (
    RISK_INTENT_LONG_TERM,
    _apply_intent_overrides,
    _load_persisted_intent_overrides,
    _sync_risk_intent_browser,
)


# ==============================
# CONSTANTS / PERSISTENCE
# ==============================

_DEFAULT_TACTICAL_BAND = 2.0
_DEFAULT_LONG_TERM_BAND = 4.0
_DEFAULT_MIN_TRADE = 500.0
_DEFAULT_LOSS_REVIEW_TRIGGER = -10.0
_DEFAULT_HARD_MAX = 25.0
_BAND_REENTRY_BUFFER = 0.10

_REBALANCE_COMPONENT_PATH = Path(__file__).parent / "components" / "risk_book_state_v1"
_rebalance_state_component = components.declare_component(
    "raj_rebalance_state_v1",
    path=str(_REBALANCE_COMPONENT_PATH),
)


def _account_token(account_key: str) -> str:
    raw = str(account_key or "default").encode("utf-8")
    return hashlib.sha256(raw).hexdigest()[:24]


def _session_state_key(account_key: str) -> str:
    return "_rebalance_state::" + _account_token(account_key)


def _browser_storage_key(account_key: str) -> str:
    return "raj-terminal-rebalance-v1:" + _account_token(account_key)


def _finite(value: Any, default: float = 0.0) -> float:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return float(default)
    return number if math.isfinite(number) else float(default)


def _clean_state(raw: Any) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raw = {}

    try:
        revision = max(0, int(raw.get("revision", 0) or 0))
    except (TypeError, ValueError):
        revision = 0

    rows: list[dict[str, Any]] = []
    seen: set[str] = set()
    for item in raw.get("rows", []) or []:
        if not isinstance(item, dict):
            continue
        symbol = str(item.get("symbol") or "").strip().upper()
        if not symbol or symbol in seen:
            continue
        seen.add(symbol)
        target_pct = min(100.0, max(0.0, _finite(item.get("target_pct"), 0.0)))
        legacy_band = min(50.0, max(0.0, _finite(item.get("band_pct"), 0.0)))
        lower_pct = min(
            target_pct,
            max(
                0.0,
                _finite(item.get("lower_pct"), max(0.0, target_pct - legacy_band)),
            ),
        )
        upper_pct = max(
            target_pct,
            min(
                100.0,
                _finite(item.get("upper_pct"), min(100.0, target_pct + legacy_band)),
            ),
        )
        rows.append(
            {
                "symbol": symbol,
                "target_pct": target_pct,
                "lower_pct": lower_pct,
                "upper_pct": upper_pct,
            }
        )

    source_settings = raw.get("settings") if isinstance(raw.get("settings"), dict) else {}
    mode = str(source_settings.get("mode") or "TO BAND").strip().upper()
    if mode not in {"TO BAND", "TO TARGET"}:
        mode = "TO BAND"

    settings = {
        "mode": mode,
        "tactical_band": min(
            25.0,
            max(0.0, _finite(source_settings.get("tactical_band"), _DEFAULT_TACTICAL_BAND)),
        ),
        "long_term_band": min(
            25.0,
            max(0.0, _finite(source_settings.get("long_term_band"), _DEFAULT_LONG_TERM_BAND)),
        ),
        "min_trade": max(0.0, _finite(source_settings.get("min_trade"), _DEFAULT_MIN_TRADE)),
        "loss_review_trigger": min(
            0.0,
            max(-100.0, _finite(source_settings.get("loss_review_trigger"), _DEFAULT_LOSS_REVIEW_TRIGGER)),
        ),
        "hard_max_pct": min(
            100.0,
            max(0.0, _finite(source_settings.get("hard_max_pct"), _DEFAULT_HARD_MAX)),
        ),
    }

    saved_at = max(0.0, _finite(raw.get("saved_at"), 0.0))
    return {
        "revision": revision,
        "saved_at": saved_at,
        # The shared zero-height browser component uses this timestamp only as
        # a stable change fingerprint. No brokerage snapshot is stored here.
        "portfolio_saved_at": max(
            0.0,
            _finite(raw.get("portfolio_saved_at"), saved_at),
        ),
        "rows": rows,
        "settings": settings,
    }


def _state_payload(state: dict[str, Any]) -> tuple[Any, Any]:
    cleaned = _clean_state(state)
    return cleaned["rows"], cleaned["settings"]


def _load_rebalance_state(account_key: str) -> dict[str, Any]:
    session_key = _session_state_key(account_key)
    session_state = _clean_state(st.session_state.get(session_key))

    with st.container(key="rebalance_state_reader_shell", gap=None):
        browser = _rebalance_state_component(
            storage_key=_browser_storage_key(account_key),
            server_state=session_state,
            key="raj_rebalance_state_reader_" + _account_token(account_key),
            default=None,
        )

    if isinstance(browser, dict) and isinstance(browser.get("state"), dict):
        browser_state = _clean_state(browser["state"])
        if browser_state["revision"] > session_state["revision"] or (
            session_state["revision"] == 0
            and not session_state["rows"]
            and browser_state["rows"]
        ):
            session_state = browser_state

    st.session_state[session_key] = session_state
    return session_state


def _persist_rebalance_state(account_key: str, candidate: dict[str, Any]) -> dict[str, Any]:
    """Update the server copy; browser sync happens once at the end of render."""
    session_key = _session_state_key(account_key)
    current = _clean_state(st.session_state.get(session_key))
    cleaned = _clean_state(candidate)

    if _state_payload(current) == _state_payload(cleaned):
        state = current
    else:
        now = time.time()
        state = {
            **cleaned,
            "revision": current["revision"] + 1,
            "saved_at": now,
            "portfolio_saved_at": now,
        }
        st.session_state[session_key] = state
    return state


def _sync_rebalance_state_browser(account_key: str, state: dict[str, Any]) -> None:
    """Write the final per-rerun state exactly once to avoid duplicate component keys."""
    with st.container(key="rebalance_state_writer_shell", gap=None):
        _rebalance_state_component(
            storage_key=_browser_storage_key(account_key),
            server_state=_clean_state(state),
            key="raj_rebalance_state_writer_" + _account_token(account_key),
            default=None,
        )


# ==============================
# SMART REBALANCE MATH
# ==============================

def _inside_band_goal(target: float, band: float, side: str) -> float:
    if band <= 0:
        return max(0.0, target)
    buffer = min(_BAND_REENTRY_BUFFER, band / 2.0)
    if side == "UPPER":
        return max(target, target + band - buffer)
    return min(target, max(0.0, target - band + buffer))


def _build_rebalance_plan(
    holdings: pd.DataFrame,
    *,
    account_value: float,
    cash_available: float,
    config_rows: list[dict[str, Any]],
    settings: dict[str, Any],
) -> tuple[pd.DataFrame, dict[str, float]]:
    """Return a deterministic, read-only smart rebalance proposal.

    Rules:
    - positions inside their target band do not trade;
    - TO BAND moves only just inside the breached band, TO TARGET restores target;
    - underweights at/below the loss-review trigger are never automatically added;
    - LONG-TERM overweights are flagged for review rather than treated as routine trims;
    - trades below the minimum-dollar threshold are suppressed;
    - excess cash is used first, then proceeds from required trims;
    - buys are prorated when funding is insufficient.
    """
    account_value = max(0.0, _finite(account_value, 0.0))
    cash_available = max(0.0, _finite(cash_available, 0.0))
    clean_settings = _clean_state({"settings": settings})["settings"]
    mode = clean_settings["mode"]
    min_trade = clean_settings["min_trade"]
    loss_trigger = clean_settings["loss_review_trigger"]
    hard_max = clean_settings["hard_max_pct"]

    config = {
        str(row.get("symbol") or "").strip().upper(): {
            "target_pct": min(100.0, max(0.0, _finite(row.get("target_pct"), 0.0))),
            "lower_pct": min(100.0, max(0.0, _finite(row.get("lower_pct"), 0.0))),
            "upper_pct": min(100.0, max(0.0, _finite(row.get("upper_pct"), 100.0))),
        }
        for row in config_rows
        if str(row.get("symbol") or "").strip()
    }

    records: list[dict[str, Any]] = []
    target_total = 0.0

    for _, source in holdings.iterrows():
        symbol = str(source.get("Symbol") or "").strip().upper()
        if not symbol:
            continue
        cfg = config.get(
            symbol,
            {"target_pct": 0.0, "lower_pct": 0.0, "upper_pct": 100.0},
        )
        target = cfg["target_pct"]
        lower = min(target, cfg["lower_pct"])
        upper = max(target, cfg["upper_pct"])
        target_total += target

        market_value = _finite(source.get("Market Value"), 0.0)
        pnl_pct = _finite(source.get("Gain/Loss %"), 0.0)
        sleeve = str(source.get("Sleeve") or "TACTICAL").strip().upper()
        current_pct = (market_value / account_value * 100.0) if account_value > 0 else 0.0
        lower_band = max(0.0, target - lower)
        upper_band = max(0.0, upper - target)
        drift = current_pct - target
        tolerance = (
            "IN TOLERANCE"
            if lower - 1e-9 <= current_pct <= upper + 1e-9
            else "OUT OF TOLERANCE"
        )

        action = "HOLD"
        reason = "INSIDE BAND"
        raw_trade = 0.0
        buy_eligible = False

        if market_value < -0.005:
            action = "REVIEW SHORT"
            reason = "SHORT / NEGATIVE MARKET VALUE IS OUTSIDE V1 LONG-ONLY MATH"
        else:
            hard_breach = hard_max > 0 and current_pct > hard_max + 1e-9
            overweight = hard_breach or current_pct > upper + 1e-9
            underweight = current_pct < lower - 1e-9

            if overweight:
                if mode == "TO TARGET":
                    goal_pct = target
                else:
                    goal_pct = _inside_band_goal(target, upper_band, "UPPER")
                if hard_breach:
                    goal_pct = min(
                        goal_pct,
                        max(0.0, hard_max - min(_BAND_REENTRY_BUFFER, hard_max / 2.0)),
                    )
                goal_value = account_value * goal_pct / 100.0
                raw_trade = goal_value - market_value
                if sleeve == "LONG-TERM" and not hard_breach:
                    action = "LONG-TERM TRIM REVIEW"
                    reason = "ABOVE BAND // LONG-TERM FLAG"
                elif hard_breach:
                    action = "HARD LIMIT REVIEW"
                    reason = f"ABOVE {hard_max:.2f}% HARD MAX"
                else:
                    action = "TRIM"
                    reason = "ABOVE UPPER BAND"

            elif underweight:
                if pnl_pct <= loss_trigger:
                    action = "REVIEW LOSS"
                    reason = f"UNDERWEIGHT // P&L <= {loss_trigger:.2f}%"
                    if mode == "TO TARGET":
                        goal_pct = target
                    else:
                        goal_pct = _inside_band_goal(target, lower_band, "LOWER")
                    raw_trade = account_value * goal_pct / 100.0 - market_value
                else:
                    action = "ADD"
                    reason = "BELOW LOWER BAND"
                    buy_eligible = True
                    if mode == "TO TARGET":
                        goal_pct = target
                    else:
                        goal_pct = _inside_band_goal(target, lower_band, "LOWER")
                    raw_trade = account_value * goal_pct / 100.0 - market_value

        if abs(raw_trade) > 0 and abs(raw_trade) < min_trade:
            action = "HOLD // BELOW MIN"
            reason = f"RAW GAP < ${min_trade:,.0f} MINIMUM"
            raw_trade = 0.0
            buy_eligible = False

        records.append(
            {
                "Symbol": symbol,
                "Sleeve": sleeve,
                "P&L %": pnl_pct,
                "Market Value": market_value,
                "Current %": current_pct,
                "Target %": target,
                "Lower %": lower,
                "Upper %": upper,
                "Tolerance": tolerance,
                "Drift %": drift,
                "Action": action,
                "Reason": reason,
                "Raw Gap $": raw_trade,
                "_buy_eligible": buy_eligible,
            }
        )

    target_cash_pct = max(0.0, 100.0 - target_total)
    target_cash_value = account_value * target_cash_pct / 100.0

    trim_proceeds = sum(
        max(0.0, -float(row["Raw Gap $"]))
        for row in records
        if float(row["Raw Gap $"]) < 0
    )
    excess_cash = max(0.0, cash_available - target_cash_value)
    funding = excess_cash + trim_proceeds

    buy_demand = sum(
        max(0.0, float(row["Raw Gap $"]))
        for row in records
        if row["_buy_eligible"] and float(row["Raw Gap $"]) > 0
    )
    buy_factor = min(1.0, funding / buy_demand) if buy_demand > 1e-9 else 0.0

    proposed_buys = 0.0
    proposed_sells = 0.0
    outside_count = 0

    for row in records:
        raw_trade = float(row["Raw Gap $"])
        proposed = raw_trade if raw_trade < 0 else 0.0

        if row["_buy_eligible"] and raw_trade > 0:
            proposed = raw_trade * buy_factor
            if proposed + 1e-9 < min_trade:
                proposed = 0.0
                if buy_factor <= 1e-9:
                    row["Action"] = "WAIT // NO FUNDING"
                    row["Reason"] = "UNDERWEIGHT // NO EXCESS CASH OR TRIM PROCEEDS"
                else:
                    row["Action"] = "HOLD // BELOW MIN"
                    row["Reason"] = f"FUNDED TRADE < ${min_trade:,.0f} MINIMUM"

        if row["Action"] == "REVIEW LOSS":
            proposed = 0.0

        post_value = float(row["Market Value"]) + proposed
        post_pct = (post_value / account_value * 100.0) if account_value > 0 else 0.0
        row["Proposed $"] = proposed
        row["Post %"] = post_pct

        if proposed > 0:
            proposed_buys += proposed
        elif proposed < 0:
            proposed_sells += -proposed

        if row["Tolerance"] == "OUT OF TOLERANCE":
            outside_count += 1

    post_cash = cash_available + proposed_sells - proposed_buys
    gross_trade = proposed_sells + proposed_buys

    public_columns = [
        "Symbol",
        "Sleeve",
        "P&L %",
        "Market Value",
        "Current %",
        "Target %",
        "Lower %",
        "Upper %",
        "Tolerance",
        "Drift %",
        "Action",
        "Raw Gap $",
        "Proposed $",
        "Post %",
        "Reason",
    ]
    plan = pd.DataFrame(records)
    if plan.empty:
        plan = pd.DataFrame(columns=public_columns)
    else:
        plan = plan[public_columns]

    summary = {
        "target_total_pct": target_total,
        "target_cash_pct": target_cash_pct,
        "target_cash_value": target_cash_value,
        "excess_cash": excess_cash,
        "trim_proceeds": proposed_sells,
        "proposed_buys": proposed_buys,
        "gross_trade": gross_trade,
        "post_cash": post_cash,
        "outside_count": float(outside_count),
        "inside_count": float(max(0, len(records) - outside_count)),
        "buy_funding_ratio": buy_factor,
    }
    return plan, summary


# ==============================
# UI / CSS
# ==============================

_REBALANCE_CSS = """
<style>
.st-key-rebalance_root{
    gap:4px!important;
    padding:0!important;
    margin:0!important;
    font-family:"Courier New",monospace!important;
}
.st-key-rebalance_root [data-testid="stVerticalBlock"]{gap:4px!important;}
.st-key-rebalance_root [data-testid="stHorizontalBlock"]{gap:8px!important;}
.st-key-rebalance_root .reb-section{
    display:flex;
    align-items:center;
    width:100%;
    height:36px;
    min-height:36px;
    box-sizing:border-box;
    margin:0;
    padding:0 10px;
    border:1px solid #fb8b1e;
    background:#050505;
    color:#fb8b1e!important;
    -webkit-text-fill-color:#fb8b1e!important;
    font:900 1.02rem/1 "Courier New",monospace;
    text-transform:uppercase;
}
.st-key-rebalance_root .reb-note{
    border:1px solid #fb8b1e;
    background:#050505;
    color:#fb8b1e!important;
    -webkit-text-fill-color:#fb8b1e!important;
    font:800 .72rem/1.28 "Courier New",monospace;
    padding:.36rem .50rem;
    margin:0;
}
.st-key-rebalance_root .reb-memory{
    border:1px solid #4af6c3;
    background:#04110d;
    color:#4af6c3!important;
    -webkit-text-fill-color:#4af6c3!important;
    font:900 .70rem/1.2 "Courier New",monospace;
    padding:.32rem .48rem;
    margin:0;
}
.st-key-rebalance_root .reb-kpi{
    border:1px solid #fb8b1e;
    background:#000;
    min-height:0!important;
    height:auto!important;
    padding:.25rem .38rem .28rem;
    margin:0;
}
.st-key-rebalance_root .reb-kpi-label{
    color:#fb8b1e!important;
    -webkit-text-fill-color:#fb8b1e!important;
    font:900 .61rem/1 "Courier New",monospace;
    letter-spacing:.03em;
}
.st-key-rebalance_root .reb-kpi-value{
    color:#f2f2f2!important;
    -webkit-text-fill-color:#f2f2f2!important;
    font:900 1.02rem/1.08 "Courier New",monospace;
    margin-top:.10rem;
}
.st-key-rebalance_root .reb-kpi-value.positive{
    color:#4af6c3!important;
    -webkit-text-fill-color:#4af6c3!important;
}
.st-key-rebalance_root .reb-kpi-value.negative{
    color:#ff433d!important;
    -webkit-text-fill-color:#ff433d!important;
}
.st-key-rebalance_root [data-testid="stWidgetLabel"] p,
.st-key-rebalance_root [data-testid="stWidgetLabel"] span{
    color:#fb8b1e!important;
    -webkit-text-fill-color:#fb8b1e!important;
    font-family:"Courier New",monospace!important;
    font-weight:900!important;
}
.st-key-rebalance_root [data-testid="stSelectbox"] div[data-baseweb="select"]>div,
.st-key-rebalance_root [data-testid="stNumberInputContainer"],
.st-key-rebalance_root [data-testid="stTextInputRootElement"]{
    min-height:38px!important;
    height:38px!important;
    background:#444444!important;
    border-color:#fb8b1e!important;
    border-radius:0!important;
}
.st-key-rebalance_root [data-testid="stSelectbox"] div[data-baseweb="select"] span,
.st-key-rebalance_root [data-testid="stSelectbox"] div[data-baseweb="select"] input,
.st-key-rebalance_root [data-testid="stNumberInput"] input,
.st-key-rebalance_root [data-testid="stTextInput"] input{
    color:#f2f2f2!important;
    -webkit-text-fill-color:#f2f2f2!important;
    font-family:"Courier New",monospace!important;
    font-weight:900!important;
}
.st-key-rebalance_root [data-testid="stNumberInputStepDown"],
.st-key-rebalance_root [data-testid="stNumberInputStepUp"]{
    min-width:38px!important;
    width:38px!important;
    height:36px!important;
    flex:0 0 38px!important;
    background:#050505!important;
    border-color:#fb8b1e!important;
    border-radius:0!important;
    color:#fb8b1e!important;
}
.st-key-rebalance_root [data-testid="stNumberInputStepDown"] *,
.st-key-rebalance_root [data-testid="stNumberInputStepUp"] *{
    color:#fb8b1e!important;
    -webkit-text-fill-color:#fb8b1e!important;
}
.st-key-rebalance_root [data-testid="stButton"] button,
.st-key-rebalance_root [data-testid="stDownloadButton"] button{
    background:#050505!important;
    border:1px solid #fb8b1e!important;
    border-radius:0!important;
    color:#fb8b1e!important;
    -webkit-text-fill-color:#fb8b1e!important;
    font-family:"Courier New",monospace!important;
    font-weight:900!important;
}
.st-key-rebalance_root [data-testid="stButton"] button:hover,
.st-key-rebalance_root [data-testid="stDownloadButton"] button:hover{
    background:#171007!important;
    color:#ffad52!important;
    -webkit-text-fill-color:#ffad52!important;
}
.st-key-rebalance_root [data-testid="stDataFrame"]{
    border:1px solid #fb8b1e!important;
}
.st-key-rebalance_root .reb-grid-head{
    min-height:26px;
    display:flex;
    align-items:center;
    padding:0 .38rem;
    border:1px solid #fb8b1e;
    background:#050505;
    color:#fb8b1e!important;
    -webkit-text-fill-color:#fb8b1e!important;
    font:900 .70rem/1 "Courier New",monospace;
    text-transform:uppercase;
}
.st-key-rebalance_root .reb-grid-cell{
    min-height:38px;
    display:flex;
    align-items:center;
    padding:0 .38rem;
    box-sizing:border-box;
    border:1px solid #5d3605;
    background:#050505;
    color:#f2f2f2!important;
    -webkit-text-fill-color:#f2f2f2!important;
    font:900 .76rem/1 "Courier New",monospace;
    white-space:nowrap;
    overflow:hidden;
    text-overflow:ellipsis;
}
.st-key-rebalance_root .reb-grid-cell.orange{
    color:#fb8b1e!important;
    -webkit-text-fill-color:#fb8b1e!important;
}
.st-key-rebalance_root .reb-grid-cell.positive{
    color:#4af6c3!important;
    -webkit-text-fill-color:#4af6c3!important;
}
.st-key-rebalance_root .reb-grid-cell.negative{
    color:#ff433d!important;
    -webkit-text-fill-color:#ff433d!important;
}
.st-key-rebalance_root .reb-grid-row [data-testid="stNumberInput"]{
    margin:0!important;
}
.st-key-rebalance_root .reb-grid-row [data-testid="stNumberInputContainer"]{
    min-height:38px!important;
    height:38px!important;
}
.st-key-rebalance_root [data-testid="stAlert"] p,
.st-key-rebalance_root [data-testid="stAlert"] div{
    color:#f2f2f2!important;
    -webkit-text-fill-color:#f2f2f2!important;
}
.st-key-rebalance_state_reader_shell,
.st-key-rebalance_state_writer_shell,
.st-key-risk_intent_state_reader_shell,
.st-key-risk_intent_state_writer_shell{
    position:absolute!important;width:0!important;height:0!important;min-width:0!important;min-height:0!important;
    max-width:0!important;max-height:0!important;margin:0!important;padding:0!important;overflow:hidden!important;pointer-events:none!important
}
.st-key-rebalance_state_reader_shell iframe,
.st-key-rebalance_state_writer_shell iframe,
.st-key-risk_intent_state_reader_shell iframe,
.st-key-risk_intent_state_writer_shell iframe{
    width:0!important;height:0!important;min-width:0!important;min-height:0!important;max-width:0!important;max-height:0!important;
    margin:0!important;padding:0!important;border:0!important;overflow:hidden!important
}
</style>
"""


def _section(title: str) -> None:
    st.html(f'<div class="reb-section">{title}</div>')


def _kpi(label: str, value: str, tone: str = "neutral") -> None:
    tone_class = "positive" if tone == "positive" else "negative" if tone == "negative" else ""
    st.html(
        '<div class="reb-kpi">'
        f'<div class="reb-kpi-label">{label}</div>'
        f'<div class="reb-kpi-value {tone_class}">{value}</div>'
        '</div>'
    )


def _money(value: float) -> str:
    value = _finite(value, 0.0)
    sign = "-" if value < 0 else ""
    return sign + "$" + f"{abs(value):,.0f}"


def _account_label(account: dict[str, Any]) -> str:
    name = str(
        account.get("accountName")
        or account.get("accountDesc")
        or account.get("accountType")
        or "E*TRADE ACCOUNT"
    ).strip()
    raw = str(account.get("accountId") or "")
    return f"{name} // ••••{raw[-4:]}" if raw else name


def _config_from_state(
    state: dict[str, Any],
    classified: pd.DataFrame,
    account_value: float,
) -> tuple[list[dict[str, Any]], bool]:
    existing = {
        str(row.get("symbol") or "").strip().upper(): dict(row)
        for row in state.get("rows", []) or []
        if str(row.get("symbol") or "").strip()
    }
    active: set[str] = set()
    rows: list[dict[str, Any]] = []
    changed = False

    for _, source in classified.iterrows():
        symbol = str(source.get("Symbol") or "").strip().upper()
        if not symbol:
            continue
        active.add(symbol)
        current_pct = (
            _finite(source.get("Market Value"), 0.0) / account_value * 100.0
            if account_value > 0
            else 0.0
        )
        sleeve = str(source.get("Sleeve") or "TACTICAL").strip().upper()
        default_band = (
            state["settings"]["long_term_band"]
            if sleeve == "LONG-TERM"
            else state["settings"]["tactical_band"]
        )
        row = existing.get(symbol)
        if row is None:
            target_pct = max(0.0, current_pct)
            row = {
                "symbol": symbol,
                "target_pct": target_pct,
                "lower_pct": max(0.0, target_pct - default_band),
                "upper_pct": min(100.0, target_pct + default_band),
            }
            changed = True
        target_pct = min(
            100.0,
            max(0.0, _finite(row.get("target_pct"), current_pct)),
        )
        lower_pct = min(
            target_pct,
            max(0.0, _finite(row.get("lower_pct"), max(0.0, target_pct - default_band))),
        )
        upper_pct = max(
            target_pct,
            min(100.0, _finite(row.get("upper_pct"), min(100.0, target_pct + default_band))),
        )
        rows.append(
            {
                "symbol": symbol,
                "target_pct": target_pct,
                "lower_pct": lower_pct,
                "upper_pct": upper_pct,
            }
        )

    if set(existing) != active:
        changed = True
    return rows, changed


def _settings_widget_keys(account_key: str) -> dict[str, str]:
    token = _account_token(account_key)
    return {
        "mode": f"rebalance_mode::{token}",
        "tactical_band": f"rebalance_tactical_band::{token}",
        "long_term_band": f"rebalance_long_term_band::{token}",
        "min_trade": f"rebalance_min_trade::{token}",
        "loss_review_trigger": f"rebalance_loss_trigger::{token}",
        "hard_max_pct": f"rebalance_hard_max::{token}",
    }


def _hydrate_setting_widgets(account_key: str, state: dict[str, Any]) -> dict[str, str]:
    keys = _settings_widget_keys(account_key)
    marker = "_rebalance_loaded_revision::" + _account_token(account_key)
    if st.session_state.get(marker) != state["revision"]:
        for field, key in keys.items():
            st.session_state[key] = state["settings"][field]
        st.session_state[marker] = state["revision"]
    return keys


def _editor_frame(
    classified: pd.DataFrame,
    config_rows: list[dict[str, Any]],
    account_value: float,
) -> pd.DataFrame:
    cfg = {row["symbol"]: row for row in config_rows}
    rows = []
    for _, source in classified.iterrows():
        symbol = str(source.get("Symbol") or "").strip().upper()
        if not symbol:
            continue
        market_value = _finite(source.get("Market Value"), 0.0)
        current_pct = (market_value / account_value * 100.0) if account_value > 0 else 0.0
        target_pct = _finite(cfg.get(symbol, {}).get("target_pct"), 0.0)
        lower_pct = _finite(cfg.get(symbol, {}).get("lower_pct"), target_pct)
        upper_pct = _finite(cfg.get(symbol, {}).get("upper_pct"), target_pct)
        rows.append(
            {
                "Symbol": symbol,
                "Sleeve": str(source.get("Sleeve") or "TACTICAL"),
                "P&L %": _finite(source.get("Gain/Loss %"), 0.0),
                "Current %": current_pct,
                "Target %": target_pct,
                "Lower %": lower_pct,
                "Upper %": upper_pct,
                "Tolerance": (
                    "IN TOLERANCE"
                    if lower_pct - 1e-9 <= current_pct <= upper_pct + 1e-9
                    else "OUT OF TOLERANCE"
                ),
            }
        )
    return pd.DataFrame(rows)



def _style_plan(plan: pd.DataFrame):
    """Make tolerance state unmistakable while keeping every cell light on dark."""
    styled = plan.style.map(
        lambda _value: "color:#f2f2f2;background-color:#050505;"
    )

    def tolerance_row(row: pd.Series) -> list[str]:
        in_tolerance = str(row.get("Tolerance") or "").strip().upper() == "IN TOLERANCE"
        tone = "#4af6c3" if in_tolerance else "#ff433d"
        emphasized = {"Current %", "Tolerance", "Drift %", "Action"}
        return [
            (
                f"color:{tone};background-color:#050505;font-weight:900;"
                if column in emphasized
                else ""
            )
            for column in row.index
        ]

    if not plan.empty and "Tolerance" in plan.columns:
        styled = styled.apply(tolerance_row, axis=1)

    if "P&L %" in plan.columns:
        styled = styled.map(
            lambda value: (
                "color:#4af6c3;background-color:#050505;font-weight:900;"
                if _finite(value, 0.0) >= 0
                else "color:#ff433d;background-color:#050505;font-weight:900;"
            ),
            subset=["P&L %"],
        )
    if "Proposed $" in plan.columns:
        styled = styled.map(
            lambda value: (
                "color:#4af6c3;background-color:#050505;font-weight:900;"
                if _finite(value, 0.0) > 0
                else (
                    "color:#ff433d;background-color:#050505;font-weight:900;"
                    if _finite(value, 0.0) < 0
                    else "color:#f2f2f2;background-color:#050505;"
                )
            ),
            subset=["Proposed $"],
        )
    return styled


def _render_static_grid_cell(value: Any, tone: str = "neutral") -> None:
    tone_class = (
        "positive"
        if tone == "positive"
        else "negative"
        if tone == "negative"
        else "orange"
        if tone == "orange"
        else ""
    )
    st.html(
        f'<div class="reb-grid-cell {tone_class}">{str(value)}</div>'
    )


def _ticker_widget_key(account_key: str, symbol: str, field: str) -> str:
    return (
        "rebalance_ticker::"
        + _account_token(account_key)
        + "::"
        + str(symbol or "").strip().upper()
        + "::"
        + field
    )


def _seed_ticker_widgets(
    account_key: str,
    config_rows: list[dict[str, Any]],
    *,
    revision: int,
    force: bool = False,
) -> None:
    token = _account_token(account_key)
    marker_key = "_rebalance_ticker_widgets_seeded::" + token
    if st.session_state.get(marker_key) == int(revision) and not force:
        return
    for row in config_rows:
        symbol = str(row.get("symbol") or "").strip().upper()
        if not symbol:
            continue
        st.session_state[_ticker_widget_key(account_key, symbol, "target")] = _finite(
            row.get("target_pct"), 0.0
        )
        st.session_state[_ticker_widget_key(account_key, symbol, "lower")] = _finite(
            row.get("lower_pct"), 0.0
        )
        st.session_state[_ticker_widget_key(account_key, symbol, "upper")] = _finite(
            row.get("upper_pct"), 0.0
        )
    st.session_state[marker_key] = int(revision)


def _render_ticker_band_editor(
    *,
    account_key: str,
    classified: pd.DataFrame,
    config_rows: list[dict[str, Any]],
    account_value: float,
) -> list[dict[str, Any]]:
    """Render readable native controls instead of Streamlit's dark canvas editor."""
    by_symbol = {
        str(row.get("symbol") or "").strip().upper(): row for row in config_rows
    }
    state_revision = int(
        st.session_state.get(_session_state_key(account_key), {}).get("revision", 0) or 0
    )
    _seed_ticker_widgets(
        account_key,
        config_rows,
        revision=state_revision,
    )

    widths = [1.0, 1.0, 0.82, 0.92, 0.94, 0.94, 0.94, 1.12]
    headers = [
        "SYMBOL",
        "SLEEVE",
        "P&L %",
        "CURRENT %",
        "TARGET %",
        "LOWER %",
        "UPPER %",
        "TOLERANCE",
    ]
    header_cols = st.columns(widths, gap="small")
    for column, title in zip(header_cols, headers):
        with column:
            st.html(f'<div class="reb-grid-head">{title}</div>')

    edited_rows: list[dict[str, Any]] = []
    for _, source in classified.iterrows():
        symbol = str(source.get("Symbol") or "").strip().upper()
        if not symbol:
            continue
        cfg = by_symbol.get(symbol, {})
        market_value = _finite(source.get("Market Value"), 0.0)
        current_pct = market_value / account_value * 100.0 if account_value > 0 else 0.0
        pnl_pct = _finite(source.get("Gain/Loss %"), 0.0)
        sleeve = str(source.get("Sleeve") or "TACTICAL").strip().upper()

        row_cols = st.columns(widths, gap="small")
        with row_cols[4]:
            target_pct = float(
                st.number_input(
                    f"{symbol} Target %",
                    min_value=0.0,
                    max_value=100.0,
                    step=0.25,
                    format="%.2f",
                    key=_ticker_widget_key(account_key, symbol, "target"),
                    label_visibility="collapsed",
                )
            )
        with row_cols[5]:
            lower_input = float(
                st.number_input(
                    f"{symbol} Lower %",
                    min_value=0.0,
                    max_value=100.0,
                    step=0.25,
                    format="%.2f",
                    key=_ticker_widget_key(account_key, symbol, "lower"),
                    label_visibility="collapsed",
                )
            )
        with row_cols[6]:
            upper_input = float(
                st.number_input(
                    f"{symbol} Upper %",
                    min_value=0.0,
                    max_value=100.0,
                    step=0.25,
                    format="%.2f",
                    key=_ticker_widget_key(account_key, symbol, "upper"),
                    label_visibility="collapsed",
                )
            )

        lower_pct = min(target_pct, lower_input)
        upper_pct = max(target_pct, upper_input)
        in_tolerance = lower_pct - 1e-9 <= current_pct <= upper_pct + 1e-9

        with row_cols[0]:
            _render_static_grid_cell(symbol, "orange")
        with row_cols[1]:
            _render_static_grid_cell(sleeve)
        with row_cols[2]:
            _render_static_grid_cell(
                f"{pnl_pct:+.2f}%",
                "positive" if pnl_pct >= 0 else "negative",
            )
        with row_cols[3]:
            _render_static_grid_cell(
                f"{current_pct:.2f}%",
                "positive" if in_tolerance else "negative",
            )
        with row_cols[7]:
            _render_static_grid_cell(
                "IN TOLERANCE" if in_tolerance else "OUT OF TOLERANCE",
                "positive" if in_tolerance else "negative",
            )

        edited_rows.append(
            {
                "symbol": symbol,
                "target_pct": target_pct,
                "lower_pct": lower_pct,
                "upper_pct": upper_pct,
            }
        )

    return edited_rows


def _config_from_editor(frame: pd.DataFrame) -> list[dict[str, Any]]:
    rows = []
    for _, source in frame.iterrows():
        symbol = str(source.get("Symbol") or "").strip().upper()
        if not symbol:
            continue
        target_pct = min(100.0, max(0.0, _finite(source.get("Target %"), 0.0)))
        lower_pct = min(
            target_pct,
            max(0.0, _finite(source.get("Lower %"), target_pct)),
        )
        upper_pct = max(
            target_pct,
            min(100.0, _finite(source.get("Upper %"), target_pct)),
        )
        rows.append(
            {
                "symbol": symbol,
                "target_pct": target_pct,
                "lower_pct": lower_pct,
                "upper_pct": upper_pct,
            }
        )
    return rows


# ==============================
# PUBLIC RENDER
# ==============================

@st.fragment
def render_rebalance_portfolio(
    client: Any,
    *,
    account_picker: Callable[[str], dict[str, Any] | None],
    refresh_accounts: Callable[[Any], list[dict[str, Any]]],
    account_balance: Callable[..., dict[str, Any]],
    balance_snapshot: Callable[[dict[str, Any]], tuple[float, float, float]],
    touch_session: Callable[[], None],
) -> None:
    st.html(_REBALANCE_CSS)

    with st.container(key="rebalance_root", gap=None):
        if client is None:
            st.info("CONNECT E*TRADE TO LOAD THE SMART REBALANCER.")
            return

        if not st.session_state.get("etrade_accounts"):
            try:
                refresh_accounts(client)
            except Exception as exc:
                st.error(f"E*TRADE ACCOUNTS UNAVAILABLE // {exc}")
                return

        _section("1. ACCOUNT + LIVE BOOK")

        # Intentionally share Risk Sizing's account-state key so changing the
        # account in either workspace keeps both workspaces on the same book.
        account = account_picker("risk_sizing_account")
        if not account:
            st.info("NO E*TRADE BROKERAGE ACCOUNT IS AVAILABLE.")
            return

        account_key = str(account.get("accountIdKey") or "").strip()
        if not account_key:
            st.info("SELECTED E*TRADE ACCOUNT HAS NO ACCOUNT KEY.")
            return

        account_col, refresh_col = st.columns([5.2, 1.5], gap="small", vertical_alignment="bottom")
        with account_col:
            st.html(
                '<div class="reb-note">'
                f'LINKED TO E*TRADE RISK SIZING ACCOUNT // {_account_label(account)}'
                '</div>'
            )
        with refresh_col:
            refresh = st.button(
                "REFRESH REBALANCER",
                type="primary",
                width="stretch",
                key="rebalance_refresh",
            )

        holdings_cache = st.session_state.setdefault("etrade_holdings", {})
        try:
            if refresh or holdings_cache.get(account_key) is None:
                holdings_cache[account_key] = client.get_portfolio(account_key)
                account_balance(client, account, refresh=True)
                touch_session()

            normalized = _normalized_holdings(holdings_cache.get(account_key) or [])
            balance_payload = account_balance(client, account, refresh=False)
            account_total, cash_available, _ = balance_snapshot(balance_payload)
        except ETradeError as exc:
            st.error(f"E*TRADE REBALANCE DATA UNAVAILABLE // {exc}")
            return
        except Exception as exc:
            st.error(f"REBALANCE DATA LOAD FAILED // {exc}")
            return

        if normalized.empty:
            st.info("NO POSITIONS WERE RETURNED FOR THE SELECTED ACCOUNT.")
            return

        market_total = pd.to_numeric(
            normalized.get("Market Value", pd.Series(dtype=float)),
            errors="coerce",
        ).fillna(0.0).sum()
        account_value = float(account_total or (market_total + cash_available))
        cash_available = max(0.0, float(cash_available or 0.0))
        if account_value <= 0:
            st.error("ACCOUNT VALUE IS NOT POSITIVE // REBALANCE MATH IS BLOCKED.")
            return

        active_symbols = (
            normalized["Symbol"].astype(str).str.strip().str.upper().tolist()
            if "Symbol" in normalized.columns
            else []
        )
        account_overrides, risk_intent_state = _load_persisted_intent_overrides(
            account_key,
            active_symbols,
        )
        _sync_risk_intent_browser(account_key, risk_intent_state)

        gain_threshold = _finite(st.session_state.get("risk_gain_threshold"), 5.0)
        classified = classify_holdings(normalized, gain_threshold)
        classified = _apply_intent_overrides(classified, account_overrides)

        state = _load_rebalance_state(account_key)
        config_rows, config_changed = _config_from_state(
            state,
            classified,
            account_value,
        )
        if config_changed:
            state = _persist_rebalance_state(
                account_key,
                {**state, "rows": config_rows},
            )

        keys = _hydrate_setting_widgets(account_key, state)

        k1, k2, k3, k4 = st.columns(4, gap="small")
        with k1:
            _kpi("ACCOUNT VALUE", _money(account_value))
        with k2:
            _kpi("CASH AVAILABLE", _money(cash_available))
        with k3:
            long_term_count = int(
                classified["Sleeve"].astype(str).str.upper().eq("LONG-TERM").sum()
            )
            _kpi("LONG-TERM FLAGS", f"{long_term_count:,}")
        with k4:
            _kpi("POSITIONS", f"{len(classified):,}")

        _section("2. SMART RULES")
        r1, r2, r3 = st.columns(3, gap="small")
        with r1:
            mode = st.selectbox(
                "Rebalance Destination",
                ("TO BAND", "TO TARGET"),
                key=keys["mode"],
                help=(
                    "TO BAND makes the minimum move just back inside the allowed range. "
                    "TO TARGET restores the exact target weight and therefore creates more turnover."
                ),
            )
        with r2:
            tactical_band = float(
                st.number_input(
                    "Default Tactical Band +/- %",
                    min_value=0.0,
                    max_value=25.0,
                    step=0.25,
                    format="%.2f",
                    key=keys["tactical_band"],
                )
            )
        with r3:
            long_term_band = float(
                st.number_input(
                    "Default Long-Term Band +/- %",
                    min_value=0.0,
                    max_value=25.0,
                    step=0.25,
                    format="%.2f",
                    key=keys["long_term_band"],
                    help="LONG-TERM positions default to a wider band, but each row remains editable.",
                )
            )

        r4, r5, r6 = st.columns(3, gap="small")
        with r4:
            min_trade = float(
                st.number_input(
                    "Minimum Rebalance Trade $",
                    min_value=0.0,
                    max_value=10_000_000.0,
                    step=100.0,
                    format="%.0f",
                    key=keys["min_trade"],
                )
            )
        with r5:
            loss_review_trigger = float(
                st.number_input(
                    "Loss Review Trigger %",
                    min_value=-100.0,
                    max_value=0.0,
                    step=1.0,
                    format="%.1f",
                    key=keys["loss_review_trigger"],
                    help=(
                        "An underweight position at or below this unrealized P&L is flagged REVIEW LOSS "
                        "instead of automatically receiving an ADD proposal."
                    ),
                )
            )
        with r6:
            hard_max_pct = float(
                st.number_input(
                    "Hard Max Position %",
                    min_value=0.0,
                    max_value=100.0,
                    step=1.0,
                    format="%.1f",
                    key=keys["hard_max_pct"],
                    help="0 disables the hard concentration limit.",
                )
            )

        settings = {
            "mode": mode,
            "tactical_band": tactical_band,
            "long_term_band": long_term_band,
            "min_trade": min_trade,
            "loss_review_trigger": loss_review_trigger,
            "hard_max_pct": hard_max_pct,
        }

        if settings != state["settings"]:
            state = _persist_rebalance_state(
                account_key,
                {**state, "settings": settings, "rows": config_rows},
            )

        _section("3. TARGETS + TICKER BANDS // AUTO-SAVED")
        control_a, control_b, _ = st.columns([1.4, 1.5, 4.0], gap="small")
        reset_targets = control_a.button(
            "RESET TARGETS TO CURRENT",
            width="stretch",
            key="rebalance_reset_targets",
            help="Seeds every target to the position's current account weight. No trades are proposed until you change targets.",
        )
        apply_bands = control_b.button(
            "APPLY DEFAULT BANDS",
            width="stretch",
            key="rebalance_apply_default_bands",
        )

        if reset_targets or apply_bands:
            by_symbol = {row["symbol"]: dict(row) for row in config_rows}
            rebuilt = []
            for _, source in classified.iterrows():
                symbol = str(source.get("Symbol") or "").strip().upper()
                if not symbol:
                    continue
                current_pct = _finite(source.get("Market Value"), 0.0) / account_value * 100.0
                sleeve = str(source.get("Sleeve") or "TACTICAL").strip().upper()
                band = long_term_band if sleeve == "LONG-TERM" else tactical_band
                previous = by_symbol.get(symbol, {})
                previous_target = _finite(previous.get("target_pct"), max(0.0, current_pct))
                target_pct = max(0.0, current_pct) if reset_targets else previous_target
                if reset_targets or apply_bands:
                    lower_pct = max(0.0, target_pct - band)
                    upper_pct = min(100.0, target_pct + band)
                else:
                    lower_pct = min(
                        target_pct,
                        _finite(previous.get("lower_pct"), max(0.0, target_pct - band)),
                    )
                    upper_pct = max(
                        target_pct,
                        _finite(previous.get("upper_pct"), min(100.0, target_pct + band)),
                    )
                rebuilt.append(
                    {
                        "symbol": symbol,
                        "target_pct": target_pct,
                        "lower_pct": lower_pct,
                        "upper_pct": upper_pct,
                    }
                )
            config_rows = rebuilt
            state = _persist_rebalance_state(
                account_key,
                {**state, "settings": settings, "rows": config_rows},
            )
            _seed_ticker_widgets(
                account_key,
                config_rows,
                revision=int(state.get("revision", 0) or 0),
                force=True,
            )

        edited_rows = _render_ticker_band_editor(
            account_key=account_key,
            classified=classified,
            config_rows=config_rows,
            account_value=account_value,
        )
        if edited_rows != config_rows:
            config_rows = edited_rows
            state = _persist_rebalance_state(
                account_key,
                {**state, "settings": settings, "rows": config_rows},
            )

        # One writer component per rerun: settings, reset actions, and data-editor
        # changes may all mutate state in the same Streamlit pass.
        _sync_rebalance_state_browser(account_key, state)
        st.html(
            '<div class="reb-memory">'
            'MEMORY ACTIVE // TARGET %, LOWER %, UPPER %, MODE, DEFAULT BANDS, MIN TRADE, LOSS TRIGGER, '
            'AND HARD MAX ARE AUTO-SAVED PER E*TRADE ACCOUNT.'
            '</div>'
        )

        target_total = sum(_finite(row.get("target_pct"), 0.0) for row in config_rows)
        if target_total > 100.0001:
            st.error(
                f"TARGET WEIGHTS TOTAL {target_total:.2f}% // V1 LONG-ONLY TARGETS CANNOT EXCEED 100%. "
                "Reduce one or more targets before a plan is generated."
            )
            return

        plan, summary = _build_rebalance_plan(
            classified,
            account_value=account_value,
            cash_available=cash_available,
            config_rows=config_rows,
            settings=settings,
        )

        _section("4. SMART REBALANCE PLAN")
        p1, p2, p3, p4, p5, p6 = st.columns(6, gap="small")
        with p1:
            _kpi("TARGETS", f"{summary['target_total_pct']:.2f}%")
        with p2:
            _kpi("TARGET CASH", f"{summary['target_cash_pct']:.2f}%")
        with p3:
            _kpi("IN TOLERANCE", f"{int(summary['inside_count']):,}", tone="positive")
        with p4:
            _kpi("OUT OF TOLERANCE", f"{int(summary['outside_count']):,}", tone="negative")
        with p5:
            _kpi("PROPOSED SELLS", _money(summary["trim_proceeds"]), tone="negative")
        with p6:
            _kpi("PROPOSED BUYS", _money(summary["proposed_buys"]), tone="positive")

        q1, q2, q3 = st.columns(3, gap="small")
        with q1:
            _kpi("GROSS TRADE PLAN", _money(summary["gross_trade"]))
        with q2:
            _kpi("POST-PLAN CASH", _money(summary["post_cash"]))
        with q3:
            _kpi("BUY FUNDING", f"{summary['buy_funding_ratio'] * 100.0:.1f}%")

        st.dataframe(
            _style_plan(plan),
            hide_index=True,
            width="stretch",
            row_height=34,
            column_config={
                "P&L %": st.column_config.NumberColumn(format="%.2f%%"),
                "Market Value": st.column_config.NumberColumn(format="$%.0f"),
                "Current %": st.column_config.NumberColumn(format="%.2f%%"),
                "Target %": st.column_config.NumberColumn(format="%.2f%%"),
                "Lower %": st.column_config.NumberColumn(format="%.2f%%"),
                "Upper %": st.column_config.NumberColumn(format="%.2f%%"),
                "Tolerance": st.column_config.TextColumn("TOLERANCE"),
                "Drift %": st.column_config.NumberColumn(format="%+.2f%%"),
                "Raw Gap $": st.column_config.NumberColumn(format="$%+.0f"),
                "Proposed $": st.column_config.NumberColumn(format="$%+.0f"),
                "Post %": st.column_config.NumberColumn(format="%.2f%%"),
            },
        )

        export_col, _ = st.columns([1.2, 5.0], gap="small")
        with export_col:
            st.download_button(
                "EXPORT PLAN CSV",
                data=plan.to_csv(index=False).encode("utf-8"),
                file_name="rebalance_plan.csv",
                mime="text/csv",
                width="stretch",
                key="rebalance_export_plan",
            )

        st.html(
            '<div class="reb-note">'
            'GREEN = IN TOLERANCE // RED = OUT OF TOLERANCE OR ACTION REQUIRED // '
            'EACH TICKER HAS ITS OWN SAVED LOWER / TARGET / UPPER BAND // '
            'EXCESS CASH FUNDS ELIGIBLE UNDERWEIGHTS FIRST // LOSS REVIEW NEVER AUTO-AVERAGES DOWN // '
            'TO BAND MINIMIZES TURNOVER // ANALYSIS ONLY: NO E*TRADE ORDER PREVIEW, PLACE, CHANGE, OR CANCEL.'
            '</div>'
        )


__all__ = ["render_rebalance_portfolio", "_build_rebalance_plan"]
