"""Fresh-process deployment guard for Raj's Terminal.

OWNERSHIP / EDITING NOTES
EDIT THIS FILE FOR:
- commit-change detection that forces a full Python process restart after a repo pull.

DO NOT EDIT THIS FILE FOR:
- feature UI, trading logic, authentication rules, or broker behavior.

Streamlit can hot-rerun Python after a Git pull without replacing the interpreter.
Raj requires every production commit to become a fresh process. A marker stored
on Python builtins survives module/script reloads inside the same interpreter but
naturally resets when the hosting platform starts a new Python process.
"""

from __future__ import annotations

import builtins
import os
from pathlib import Path
from typing import Callable


_BOOT_MARKER = "_raj_terminal_boot_commit_v1"


def _git_dir(repo_root: Path) -> Path | None:
    marker = repo_root / ".git"
    if marker.is_dir():
        return marker
    if marker.is_file():
        try:
            text = marker.read_text(encoding="utf-8").strip()
        except OSError:
            return None
        if text.lower().startswith("gitdir:"):
            target = text.split(":", 1)[1].strip()
            path = Path(target)
            return path if path.is_absolute() else (repo_root / path).resolve()
    return None


def _read_packed_ref(git_dir: Path, ref_name: str) -> str:
    packed = git_dir / "packed-refs"
    try:
        lines = packed.read_text(encoding="utf-8").splitlines()
    except OSError:
        return ""
    suffix = " " + ref_name
    for line in lines:
        if line.startswith("#") or line.startswith("^"):
            continue
        if line.endswith(suffix):
            return line.split(" ", 1)[0].strip()
    return ""


def repo_commit(repo_root: Path | None = None) -> str:
    """Return the checked-out Git commit without shelling out to git."""
    root = Path(repo_root or Path(__file__).resolve().parents[1])
    git_dir = _git_dir(root)
    if not git_dir:
        return ""
    try:
        head = (git_dir / "HEAD").read_text(encoding="utf-8").strip()
    except OSError:
        return ""
    if not head:
        return ""
    if not head.startswith("ref:"):
        return head
    ref_name = head.split(":", 1)[1].strip()
    ref_path = git_dir / ref_name
    try:
        value = ref_path.read_text(encoding="utf-8").strip()
    except OSError:
        value = _read_packed_ref(git_dir, ref_name)
    return value


def ensure_fresh_process(
    *,
    current_commit: str | None = None,
    exit_fn: Callable[[int], object] = os._exit,
) -> bool:
    """Exit the stale interpreter if its boot commit differs from repo HEAD.

    Returns True only when a restart was requested. Missing Git metadata is a
    safe no-op so local packaged/test environments are not disrupted.
    """
    current = str(current_commit if current_commit is not None else repo_commit()).strip()
    if not current:
        return False

    boot = str(getattr(builtins, _BOOT_MARKER, "") or "").strip()
    if not boot:
        setattr(builtins, _BOOT_MARKER, current)
        return False
    if boot == current:
        return False

    exit_fn(75)
    return True
