"""Schwab Risk Sizing route for Raj's Terminal.

OWNERSHIP / EDITING NOTES
-------------------------
THIS FILE owns the SCHWAB RISK SIZING tab only.

EDIT THIS FILE FOR:
- Schwab Risk Sizing setup/readiness UI;
- future Schwab account, holdings, balance, and quote binding;
- Schwab-only session/state isolation before live broker data is enabled.

DO NOT EDIT THIS FILE FOR:
- E*TRADE Risk Sizing UI or interaction;
- shared risk formulas (use src/risk_sizing.py);
- GEX, E*TRADE OAuth, Holdings, or top-navigation behavior.

The Schwab developer/API account is not configured yet. Until it is, this
module must never substitute E*TRADE holdings or quotes. The eventual live
implementation should feed Schwab-normalized holdings/balances/quotes into the
same risk formulas in src/risk_sizing.py while keeping broker state separate.
"""

from __future__ import annotations

import streamlit as st


# ==============================
# SCHWAB INTEGRATION STATUS
# ==============================

def render_schwab_risk_sizing() -> None:
    """Render the isolated Schwab Risk Sizing route until API access is wired."""
    st.markdown("**SCHWAB API STATUS // DEVELOPER ACCESS REQUIRED**")
    st.info(
        "SCHWAB RISK SIZING IS READY AS A SEPARATE TERMINAL ROUTE, BUT LIVE "
        "SCHWAB HOLDINGS / BALANCES / QUOTES ARE NOT CONNECTED YET."
    )
    st.caption(
        "PLANNED DATA PATH // SCHWAB ACCOUNTS → SCHWAB HOLDINGS + CASH → "
        "SCHWAB QUOTES → SAME CROWN / STOP-BASED RISK FORMULAS IN src/risk_sizing.py"
    )
    st.caption(
        "BROKER ISOLATION // THIS TAB DOES NOT READ E*TRADE HOLDINGS, E*TRADE "
        "QUOTES, OR E*TRADE ACCOUNT STATE."
    )


__all__ = ["render_schwab_risk_sizing"]
