"""Raj's Terminal visual design system.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- terminal-wide palette and shared appearance;
- shared input/caret/dropdown styling that must apply across every feature;
- shared dataframe visual treatment.

DO NOT EDIT THIS FILE FOR:
- Risk Sizing behavior or formulas;
- GEX layout/analytics;
- E*TRADE OAuth workflow behavior;
- Holdings logic;
- top-navigation spacing.

Source palette: Bloomberg palette from color-hex.com/color-palette/111776.
Keep all terminal modules aligned to these semantic colors.

Streamlit's interactive dataframe header is rendered by Glide Data Grid, not
normal DOM table-header elements. That means ordinary CSS selectors cannot
reliably recolor it. Raj's Terminal therefore uses Streamlit's native dataframe
header theme for the orange header band and keeps dataframe body text orange via
Pandas Styler, while preserving any existing red/green/blue financial styles.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components

try:
    from pandas.io.formats.style import Styler
except Exception:  # pragma: no cover - defensive across pandas builds
    Styler = ()


# ==============================
# BLOOMBERG PALETTE
# ==============================

BB_BLACK = "#000000"
BB_RED = "#ff433d"
BB_BLUE = "#0068ff"
BB_GREEN = "#4af6c3"
BB_ORANGE = "#fb8b1e"

BLOOMBERG_PALETTE = [
    BB_BLACK,
    BB_RED,
    BB_BLUE,
    BB_GREEN,
    BB_ORANGE,
]

CHART_COLORWAY = [
    BB_GREEN,
    BB_BLUE,
    BB_ORANGE,
    BB_RED,
]


# ==============================
# TERMINAL-WIDE INPUT THEME
# ==============================

# IMPORTANT: Keep this as a plain string. CSS uses { ... } blocks, so using a
# Python f-string here can make Python interpret CSS braces as expressions and
# crash the entire app at import time. Substitute colors with .replace().
_TYPING_CARET_CSS = """
<style>
/* Native blinking insertion caret anywhere the user can type. */
input[type="text"]:not(:disabled),
input[type="search"]:not(:disabled),
input[type="password"]:not(:disabled),
input[type="number"]:not(:disabled),
input[type="email"]:not(:disabled),
input[type="tel"]:not(:disabled),
input[type="url"]:not(:disabled),
input:not([type]):not(:disabled),
textarea:not(:disabled),
[contenteditable="true"] {
    caret-color:__RAJ_CARET_COLOR__ !important;
    cursor:text !important;
}

[data-testid="stTextInput"] input:focus,
[data-testid="stNumberInput"] input:focus,
[data-testid="stTextArea"] textarea:focus,
[data-baseweb="input"] input:focus,
[data-baseweb="textarea"] textarea:focus,
[data-baseweb="select"] input:focus,
[role="combobox"]:focus,
[contenteditable="true"]:focus {
    caret-color:__RAJ_CARET_COLOR__ !important;
}

/*
   TERMINAL-WIDE DROPDOWN READABILITY
   .streamlit/config.toml intentionally uses black textColor so interactive
   dataframe headers are black on orange. Therefore select controls MUST
   explicitly override every nested selected-value and menu-option text node.
*/
[data-testid="stSelectbox"] [data-baseweb="select"] > div,
[data-testid="stMultiSelect"] [data-baseweb="select"] > div,
[data-testid="stSelectbox"] [aria-haspopup="listbox"],
[data-testid="stMultiSelect"] [aria-haspopup="listbox"],
[data-baseweb="select"] > div,
[data-baseweb="select"] [role="combobox"] {
    background:#050505 !important;
    border-color:__RAJ_DROPDOWN_ACCENT__ !important;
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    -webkit-text-fill-color:__RAJ_DROPDOWN_ACCENT__ !important;
    box-shadow:none !important;
}

/* Streamlit 1.61+ may render native selects through React Aria instead of
   BaseWeb. Match the closed trigger to the exact same Courier weight used by
   the detached menu options so selected/open states never look mismatched. */
[data-testid="stSelectbox"] [data-baseweb="select"] > div *,
[data-testid="stMultiSelect"] [data-baseweb="select"] > div *,
[data-testid="stSelectbox"] [aria-haspopup="listbox"],
[data-testid="stSelectbox"] [aria-haspopup="listbox"] *,
[data-testid="stMultiSelect"] [aria-haspopup="listbox"],
[data-testid="stMultiSelect"] [aria-haspopup="listbox"] *,
[data-testid="stSelectbox"] [role="group"] *,
[data-testid="stMultiSelect"] [role="group"] *,
[data-baseweb="select"] > div *,
[data-baseweb="select"] [role="combobox"] *,
[data-baseweb="select"] input,
[data-baseweb="select"] span,
[data-baseweb="select"] p {
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    -webkit-text-fill-color:__RAJ_DROPDOWN_ACCENT__ !important;
    font-family:"Courier New",monospace !important;
    font-weight:800 !important;
    opacity:1 !important;
}

[data-baseweb="select"] svg,
[data-testid="stSelectbox"] svg,
[data-testid="stMultiSelect"] svg {
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    fill:__RAJ_DROPDOWN_ACCENT__ !important;
}

/* BaseWeb open menus live in a portal outside the original selectbox DOM. */
[data-baseweb="popover"],
[data-baseweb="popover"] [role="listbox"],
[data-baseweb="popover"] [data-baseweb="menu"],
[data-baseweb="menu"],
[role="listbox"] {
    background:#050505 !important;
    color:#f2f2f2 !important;
}

[data-baseweb="popover"] [role="listbox"],
[data-baseweb="popover"] [data-baseweb="menu"] {
    border:1px solid __RAJ_DROPDOWN_ACCENT__ !important;
}

[data-baseweb="popover"] [role="option"],
[data-baseweb="popover"] [role="option"] *,
[data-baseweb="menu"] [role="option"],
[data-baseweb="menu"] [role="option"] *,
[role="listbox"] [role="option"],
[role="listbox"] [role="option"] * {
    background:#050505 !important;
    color:#f2f2f2 !important;
    -webkit-text-fill-color:#f2f2f2 !important;
    font-family:"Courier New",monospace !important;
    font-weight:800 !important;
    opacity:1 !important;
}

[data-baseweb="popover"] [role="option"]:hover,
[data-baseweb="popover"] [role="option"]:focus,
[data-baseweb="popover"] [role="option"][data-hovered],
[data-baseweb="popover"] [role="option"][data-focused],
[data-baseweb="popover"] [role="option"][data-highlighted],
[data-baseweb="menu"] [role="option"]:hover,
[data-baseweb="menu"] [role="option"]:focus,
[data-baseweb="menu"] [role="option"][data-hovered],
[data-baseweb="menu"] [role="option"][data-focused],
[data-baseweb="menu"] [role="option"][data-highlighted],
[role="listbox"] [role="option"]:hover,
[role="listbox"] [role="option"]:focus,
[role="listbox"] [role="option"][data-hovered],
[role="listbox"] [role="option"][data-focused],
[role="listbox"] [role="option"][data-highlighted] {
    background:#171007 !important;
    color:#ffad52 !important;
    -webkit-text-fill-color:#ffad52 !important;
}

[data-baseweb="popover"] [role="option"]:hover *,
[data-baseweb="popover"] [role="option"]:focus *,
[data-baseweb="popover"] [role="option"][data-hovered] *,
[data-baseweb="popover"] [role="option"][data-focused] *,
[data-baseweb="popover"] [role="option"][data-highlighted] *,
[data-baseweb="menu"] [role="option"]:hover *,
[data-baseweb="menu"] [role="option"]:focus *,
[data-baseweb="menu"] [role="option"][data-hovered] *,
[data-baseweb="menu"] [role="option"][data-focused] *,
[data-baseweb="menu"] [role="option"][data-highlighted] *,
[role="listbox"] [role="option"]:hover *,
[role="listbox"] [role="option"]:focus *,
[role="listbox"] [role="option"][data-hovered] *,
[role="listbox"] [role="option"][data-focused] *,
[role="listbox"] [role="option"][data-highlighted] * {
    color:#ffad52 !important;
    -webkit-text-fill-color:#ffad52 !important;
}

[data-baseweb="popover"] [role="option"][aria-selected="true"],
[data-baseweb="popover"] [role="option"][aria-selected="true"] *,
[data-baseweb="menu"] [role="option"][aria-selected="true"],
[data-baseweb="menu"] [role="option"][aria-selected="true"] *,
[role="listbox"] [role="option"][aria-selected="true"],
[role="listbox"] [role="option"][aria-selected="true"] * {
    background:__RAJ_DROPDOWN_ACCENT__ !important;
    color:#000000 !important;
    -webkit-text-fill-color:#000000 !important;
}

/*
   E*TRADE ACCOUNT PICKER TYPOGRAPHY
   Streamlit 1.61+ renders the closed selected value as a React Aria input,
   while opened choices render as divs in a detached listbox portal. Browsers
   can rasterize those element types differently even when inherited weight
   values match. Give the shared account picker one explicit real-bold Courier
   face and rendering contract for its label, closed value, and open rows.
*/
[data-testid="stSelectbox"]:has(input[aria-label="E*TRADE Account"]) [data-testid="stWidgetLabel"] p,
[data-testid="stSelectbox"] input[role="combobox"][aria-label="E*TRADE Account"],
[role="listbox"][aria-label="E*TRADE Account"] [role="option"],
[role="listbox"][aria-label="E*TRADE Account"] [role="option"] * {
    font-family:"Courier New",Courier,monospace !important;
    font-size:14px !important;
    font-weight:700 !important;
    font-style:normal !important;
    font-stretch:normal !important;
    letter-spacing:0 !important;
    line-height:1.2 !important;
    font-synthesis:none !important;
    text-rendering:geometricPrecision !important;
    -webkit-font-smoothing:auto !important;
}

select:not(:disabled) {
    background:#050505 !important;
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    border-color:__RAJ_DROPDOWN_ACCENT__ !important;
}
select:not(:disabled) option {
    background:#050505 !important;
    color:#f2f2f2 !important;
}

/*
   DATAFRAME COLUMN-MENU READABILITY
   Streamlit renders dataframe column actions in its shared overlay portal.
   The app-level textColor is intentionally black for black-on-orange dataframe
   headers, so these dark overlay panels need an explicit light foreground.
   Keep the selectors tied to Streamlit's dataframe-menu testids so unrelated
   buttons/popovers are not recolored.
*/
[data-testid="stDataFrameColumnMenu"],
[data-testid="stDataFrameStatisticsMenu"],
[data-testid="stDataFrameColumnFormattingMenu"] {
    background:#050505 !important;
    color:#f2f2f2 !important;
    border:1px solid __RAJ_DROPDOWN_ACCENT__ !important;
}

[data-testid="stDataFrameColumnMenu"] *,
[data-testid="stDataFrameStatisticsMenu"] *,
[data-testid="stDataFrameColumnFormattingMenu"] * {
    color:#f2f2f2 !important;
    -webkit-text-fill-color:#f2f2f2 !important;
}

[data-testid="stDataFrameColumnMenu"] [role="menuitem"],
[data-testid="stDataFrameColumnFormattingMenu"] [role="menuitem"] {
    background:transparent !important;
}

[data-testid="stDataFrameColumnMenu"] [role="menuitem"]:hover,
[data-testid="stDataFrameColumnMenu"] [role="menuitem"]:focus,
[data-testid="stDataFrameColumnMenu"] [role="menuitem"][aria-expanded="true"],
[data-testid="stDataFrameColumnFormattingMenu"] [role="menuitem"]:hover,
[data-testid="stDataFrameColumnFormattingMenu"] [role="menuitem"]:focus {
    background:#171007 !important;
    color:#ffad52 !important;
    -webkit-text-fill-color:#ffad52 !important;
}

[data-testid="stDataFrameColumnMenu"] [role="menuitem"]:hover *,
[data-testid="stDataFrameColumnMenu"] [role="menuitem"]:focus *,
[data-testid="stDataFrameColumnMenu"] [role="menuitem"][aria-expanded="true"] *,
[data-testid="stDataFrameColumnFormattingMenu"] [role="menuitem"]:hover *,
[data-testid="stDataFrameColumnFormattingMenu"] [role="menuitem"]:focus * {
    color:#ffad52 !important;
    -webkit-text-fill-color:#ffad52 !important;
}

/*
   STREAMLIT TOOLBAR / RUNNING CONTROL
   Global textColor is intentionally black elsewhere for dataframe headers, but
   the native top-right Stop/running control sits on a dark toolbar. Force all
   of its nested label/icon nodes back to terminal orange on every rerun.
*/
[data-testid="stToolbar"],
[data-testid="stToolbar"] button,
[data-testid="stToolbar"] button *,
[data-testid="stToolbar"] [role="button"],
[data-testid="stToolbar"] [role="button"] *,
[data-testid="stStatusWidget"],
[data-testid="stStatusWidget"] *,
[data-testid="stStatusWidget"] button,
[data-testid="stStatusWidget"] button * {
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    -webkit-text-fill-color:__RAJ_DROPDOWN_ACCENT__ !important;
}

[data-testid="stToolbar"] svg,
[data-testid="stStatusWidget"] svg {
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    fill:currentColor !important;
    stroke:currentColor !important;
}

[data-testid="stStatusWidget"] button,
[data-testid="stToolbar"] button[aria-label="Stop"],
[data-testid="stToolbar"] button[title="Stop"] {
    border-color:__RAJ_DROPDOWN_ACCENT__ !important;
    background:#050505 !important;
}
</style>
""".replace("__RAJ_CARET_COLOR__", BB_ORANGE).replace("__RAJ_DROPDOWN_ACCENT__", BB_ORANGE)


def install_typing_caret_theme() -> None:
    """Emit shared input/dropdown/toolbar CSS for the current Streamlit render.

    Streamlit output is session/rerun scoped. Do not use a process-global
    "already installed" flag here: later browser sessions would otherwise lose
    this stylesheet and fall back to black dropdown or toolbar text.
    """
    st.html(_TYPING_CARET_CSS)


# ==============================
# LEGACY COMPONENT COMPATIBILITY
# ==============================

def _install_components_html_compat() -> None:
    """Route legacy components.html calls through Streamlit's current st.iframe API."""
    if getattr(components, "_raj_html_compat_installed", False):
        return

    def _html_via_iframe(
        html_body,
        width=None,
        height=None,
        scrolling=False,
        **_kwargs,
    ):
        iframe_width = width if width is not None else "stretch"
        iframe_height = height if height is not None else "content"
        return st.iframe(
            html_body,
            width=iframe_width,
            height=iframe_height,
        )

    components.html = _html_via_iframe
    components._raj_html_compat_installed = True


# ==============================
# DATAFRAME THEME
# ==============================

def _style_dataframe_body(data):
    """Keep body text orange without overwriting existing financial colors."""
    if isinstance(data, pd.DataFrame):
        return data.style.set_properties(**{"color": BB_ORANGE})

    if Styler and isinstance(data, Styler):
        try:
            data._compute()
            existing_ctx = dict(getattr(data, "ctx", {}) or {})
            body = data.data
            defaults = pd.DataFrame("", index=body.index, columns=body.columns)
            has_defaults = False

            for row_pos in range(len(body.index)):
                for col_pos in range(len(body.columns)):
                    declarations = existing_ctx.get((row_pos, col_pos), []) or []
                    has_color = any(
                        str(prop).strip().casefold() == "color"
                        for prop, _value in declarations
                    )
                    if not has_color:
                        defaults.iat[row_pos, col_pos] = f"color:{BB_ORANGE};"
                        has_defaults = True

            if has_defaults:
                data = data.apply(lambda _frame: defaults, axis=None)
        except Exception:
            pass
        return data

    return data


def install_bloomberg_dataframe_theme() -> None:
    """Install the interactive-table body-color adapter exactly once."""
    if getattr(st, "_raj_bloomberg_dataframe_theme", False):
        return

    original_dataframe = st.dataframe

    def bloomberg_dataframe(data=None, *args, **kwargs):
        try:
            data = _style_dataframe_body(data)
        except Exception:
            pass
        return original_dataframe(data, *args, **kwargs)

    st.dataframe = bloomberg_dataframe
    st._raj_bloomberg_dataframe_theme = True


# Theme rendering itself is intentionally NOT executed at import time. The
# entrypoint calls install_typing_caret_theme() after terminal_core has completed
# st.set_page_config and does so on every Streamlit rerun/session.
_install_components_html_compat()
install_bloomberg_dataframe_theme()
