"""Raj's Terminal visual design system.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- terminal-wide palette and shared appearance;
- shared input/caret/dropdown styling that must apply across every feature;
- shared dataframe visual treatment.

DO NOT EDIT THIS FILE FOR:
- Risk Sizing behavior or formulas;
- GEX layout/analytics;
- E*TRADE OAuth workflow behavior;
- Holdings logic;
- top-navigation spacing.

Source palette: Bloomberg palette from color-hex.com/color-palette/111776.
Keep all terminal modules aligned to these semantic colors.

Streamlit's interactive dataframe header is rendered by Glide Data Grid, not
normal DOM table-header elements. That means ordinary CSS selectors cannot
reliably recolor it. Raj's Terminal therefore uses Streamlit's native dataframe
header theme for the orange header band and keeps dataframe body text orange via
Pandas Styler, while preserving any existing red/green/blue financial styles.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components

try:
    from pandas.io.formats.style import Styler
except Exception:  # pragma: no cover - defensive across pandas builds
    Styler = ()


# ==============================
# BLOOMBERG PALETTE
# ==============================

BB_BLACK = "#000000"
BB_RED = "#ff433d"
BB_BLUE = "#0068ff"
BB_GREEN = "#4af6c3"
BB_ORANGE = "#fb8b1e"

BLOOMBERG_PALETTE = [
    BB_BLACK,
    BB_RED,
    BB_BLUE,
    BB_GREEN,
    BB_ORANGE,
]

CHART_COLORWAY = [
    BB_GREEN,
    BB_BLUE,
    BB_ORANGE,
    BB_RED,
]


# ==============================
# TERMINAL-WIDE INPUT THEME
# ==============================

# IMPORTANT: Keep this as a plain string. CSS uses { ... } blocks, so using a
# Python f-string here can make Python interpret CSS braces as expressions and
# crash the entire app at import time. Substitute colors with .replace().
_TYPING_CARET_CSS = """
<style>
/*
   Use the browser's native blinking insertion caret everywhere the user can
   type. Do not fake a cursor with pseudo-elements or JavaScript: the native
   caret tracks selection, keyboard navigation, accessibility, and IME input.
*/
input[type="text"]:not(:disabled),
input[type="search"]:not(:disabled),
input[type="password"]:not(:disabled),
input[type="number"]:not(:disabled),
input[type="email"]:not(:disabled),
input[type="tel"]:not(:disabled),
input[type="url"]:not(:disabled),
input:not([type]):not(:disabled),
textarea:not(:disabled),
[contenteditable="true"] {
    caret-color:__RAJ_CARET_COLOR__ !important;
    cursor:text !important;
}

/* Keep the insertion bar clearly visible in focused Streamlit/BaseWeb fields. */
[data-testid="stTextInput"] input:focus,
[data-testid="stNumberInput"] input:focus,
[data-testid="stTextArea"] textarea:focus,
[data-baseweb="input"] input:focus,
[data-baseweb="textarea"] textarea:focus,
[data-baseweb="select"] input:focus,
[role="combobox"]:focus,
[contenteditable="true"]:focus {
    caret-color:__RAJ_CARET_COLOR__ !important;
}

/*
   TERMINAL-WIDE DROPDOWN READABILITY
   BaseWeb changes its nested markup between Streamlit releases. Style the
   actual select shell AND all nested value nodes so no inherited black text can
   survive on the terminal's dark background. Open menus render in a portal, so
   their listbox/option descendants are covered separately below.
*/
[data-testid="stSelectbox"] [data-baseweb="select"] > div,
[data-testid="stMultiSelect"] [data-baseweb="select"] > div,
[data-baseweb="select"] > div,
[data-baseweb="select"] [role="combobox"] {
    background:#050505 !important;
    border-color:__RAJ_DROPDOWN_ACCENT__ !important;
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    -webkit-text-fill-color:__RAJ_DROPDOWN_ACCENT__ !important;
    box-shadow:none !important;
}

[data-testid="stSelectbox"] [data-baseweb="select"] > div *,
[data-testid="stMultiSelect"] [data-baseweb="select"] > div *,
[data-baseweb="select"] > div *,
[data-baseweb="select"] [role="combobox"],
[data-baseweb="select"] [role="combobox"] *,
[data-baseweb="select"] input,
[data-baseweb="select"] span,
[data-baseweb="select"] p {
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    -webkit-text-fill-color:__RAJ_DROPDOWN_ACCENT__ !important;
    font-family:"Courier New",monospace !important;
    font-weight:800 !important;
}

[data-baseweb="select"] svg,
[data-testid="stSelectbox"] svg,
[data-testid="stMultiSelect"] svg {
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    fill:__RAJ_DROPDOWN_ACCENT__ !important;
}

/* Open BaseWeb menu/listbox portal. */
[data-baseweb="popover"],
[data-baseweb="popover"] [role="listbox"],
[data-baseweb="popover"] ul[role="listbox"],
[data-baseweb="popover"] [data-baseweb="menu"],
[data-baseweb="menu"],
[role="listbox"] {
    background:#050505 !important;
    color:#f2f2f2 !important;
}

[data-baseweb="popover"] [role="listbox"],
[data-baseweb="popover"] ul[role="listbox"],
[data-baseweb="popover"] [data-baseweb="menu"] {
    border:1px solid __RAJ_DROPDOWN_ACCENT__ !important;
}

[data-baseweb="popover"] [role="option"],
[data-baseweb="popover"] [role="option"] *,
[data-baseweb="menu"] [role="option"],
[data-baseweb="menu"] [role="option"] *,
[role="listbox"] [role="option"],
[role="listbox"] [role="option"] * {
    background:#050505 !important;
    color:#f2f2f2 !important;
    -webkit-text-fill-color:#f2f2f2 !important;
    font-family:"Courier New",monospace !important;
    font-weight:800 !important;
}

[data-baseweb="popover"] [role="option"]:hover,
[data-baseweb="popover"] [role="option"]:focus,
[data-baseweb="menu"] [role="option"]:hover,
[data-baseweb="menu"] [role="option"]:focus,
[role="listbox"] [role="option"]:hover,
[role="listbox"] [role="option"]:focus {
    background:#171007 !important;
    color:#ffad52 !important;
    -webkit-text-fill-color:#ffad52 !important;
}

[data-baseweb="popover"] [role="option"][aria-selected="true"],
[data-baseweb="popover"] [role="option"][aria-selected="true"] *,
[data-baseweb="menu"] [role="option"][aria-selected="true"],
[data-baseweb="menu"] [role="option"][aria-selected="true"] *,
[role="listbox"] [role="option"][aria-selected="true"],
[role="listbox"] [role="option"][aria-selected="true"] * {
    background:__RAJ_DROPDOWN_ACCENT__ !important;
    color:#000000 !important;
    -webkit-text-fill-color:#000000 !important;
}

/* Native select fallback for any non-BaseWeb controls. */
select:not(:disabled) {
    background:#050505 !important;
    color:__RAJ_DROPDOWN_ACCENT__ !important;
    border-color:__RAJ_DROPDOWN_ACCENT__ !important;
}
select:not(:disabled) option {
    background:#050505 !important;
    color:#f2f2f2 !important;
}
</style>
""".replace("__RAJ_CARET_COLOR__", BB_ORANGE).replace("__RAJ_DROPDOWN_ACCENT__", BB_ORANGE)


def install_typing_caret_theme() -> None:
    """Emit shared editable-field/dropdown CSS for the current Streamlit render.

    This intentionally runs on every script render/session. Streamlit output is
    session-scoped; a process-global "already installed" flag can leave later
    browser sessions or reruns without the stylesheet and cause black-on-black
    dropdown values.
    """
    st.html(_TYPING_CARET_CSS)


# ==============================
# LEGACY COMPONENT COMPATIBILITY
# ==============================

def _install_components_html_compat() -> None:
    """Route legacy components.html calls through Streamlit's current st.iframe API.

    Streamlit 1.56+ deprecated st.components.v1.html. Raj's Terminal still has
    older renderers that call components.html for trusted, locally generated
    HTML/JavaScript (for example the E*TRADE session timer). Patching the shared
    module object here removes the deprecated runtime call without changing the
    behavior of those renderers one by one.
    """
    if getattr(components, "_raj_html_compat_installed", False):
        return

    def _html_via_iframe(
        html_body,
        width=None,
        height=None,
        scrolling=False,
        **_kwargs,
    ):
        # st.iframe accepts raw HTML and executes JavaScript inside an iframe.
        # The legacy `scrolling` flag has no direct replacement; existing Raj's
        # Terminal component frames are explicitly sized and do not rely on it.
        iframe_width = width if width is not None else "stretch"
        iframe_height = height if height is not None else "content"
        return st.iframe(
            html_body,
            width=iframe_width,
            height=iframe_height,
        )

    components.html = _html_via_iframe
    components._raj_html_compat_installed = True


# ==============================
# DATAFRAME THEME
# ==============================

def _style_dataframe_body(data):
    """Keep body text orange without overwriting existing financial colors.

    The app theme intentionally uses black as Streamlit's base text color so
    dataframe headers can render black text on the native orange header band.
    Interactive dataframe body cells therefore need an explicit orange default.
    Existing Styler colors (green gains, red losses, blue tactical percentages,
    etc.) are detected first and left untouched.
    """
    if isinstance(data, pd.DataFrame):
        return data.style.set_properties(**{"color": BB_ORANGE})

    if Styler and isinstance(data, Styler):
        try:
            # Compute the current style context before adding our fallback.
            # ctx is keyed by (row_position, column_position).
            data._compute()
            existing_ctx = dict(getattr(data, "ctx", {}) or {})
            body = data.data
            defaults = pd.DataFrame("", index=body.index, columns=body.columns)
            has_defaults = False

            for row_pos in range(len(body.index)):
                for col_pos in range(len(body.columns)):
                    declarations = existing_ctx.get((row_pos, col_pos), []) or []
                    has_color = any(
                        str(prop).strip().casefold() == "color"
                        for prop, _value in declarations
                    )
                    if not has_color:
                        defaults.iat[row_pos, col_pos] = f"color:{BB_ORANGE};"
                        has_defaults = True

            if has_defaults:
                data = data.apply(lambda _frame: defaults, axis=None)
        except Exception:
            # Styling must never make a functional table fail to render.
            pass
        return data

    return data


def install_bloomberg_dataframe_theme() -> None:
    """Install the interactive-table body-color adapter exactly once."""
    if getattr(st, "_raj_bloomberg_dataframe_theme", False):
        return

    original_dataframe = st.dataframe

    def bloomberg_dataframe(data=None, *args, **kwargs):
        try:
            data = _style_dataframe_body(data)
        except Exception:
            pass
        return original_dataframe(data, *args, **kwargs)

    st.dataframe = bloomberg_dataframe
    st._raj_bloomberg_dataframe_theme = True


# The stylesheet is emitted by streamlit_app.py after the core has completed
# st.set_page_config, on every rerun/session. Keep only non-layout compatibility
# installs here; they do not emit visible Streamlit elements.
_install_components_html_compat()
install_bloomberg_dataframe_theme()
