"""Shared yfinance options-market fallback for Raj's Terminal.

OWNERSHIP / EDITING NOTES
-------------------------
EDIT THIS FILE FOR:
- terminal-wide public options quote/expiration/chain fallback;
- adapting yfinance option data to the E*TRADE-style payload shape already
  consumed by Bull Debit, Vertical Options, Option Book, and GEX.

DO NOT EDIT THIS FILE FOR:
- E*TRADE OAuth/session behavior;
- order preview/place/cancel behavior;
- strategy formulas or feature UI styling.

E*TRADE remains primary. This adapter is used only when the broker connector is
not live. It is intentionally read-only.
"""

from __future__ import annotations

import math
from datetime import date, datetime
from typing import Any
from zoneinfo import ZoneInfo

import pandas as pd
import yfinance as yf

from src.etrade_client import ETradeError


_SOURCE = "YFINANCE"
_MARKET_TZ = ZoneInfo("America/New_York")


def _number(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def _fast_value(fast: Any, *keys: str) -> float | None:
    for key in keys:
        try:
            value = fast.get(key) if hasattr(fast, "get") else fast[key]
        except Exception:
            value = None
        number = _number(value)
        if number is not None:
            return number
    return None


def _ticker_quote(ticker: Any, symbol: str) -> tuple[float, float | None, float | None, str]:
    last = bid = ask = None
    try:
        fast = ticker.fast_info
        last = _fast_value(fast, "last_price", "lastPrice")
        bid = _fast_value(fast, "bid")
        ask = _fast_value(fast, "ask")
    except Exception:
        pass

    if last is None:
        try:
            history = ticker.history(period="5d", auto_adjust=False)
            if not history.empty:
                last = _number(history["Close"].dropna().iloc[-1])
        except Exception:
            last = None
    if last is None:
        raise ETradeError(f"yfinance returned no usable quote for {symbol}.")

    name = ""
    try:
        info = ticker.info or {}
        name = str(info.get("longName") or info.get("shortName") or "").strip()
    except Exception:
        pass
    return float(last), bid, ask, name


def _expiration_date(year: int, month: int, day: int) -> date:
    try:
        return date(int(year), int(month), int(day))
    except (TypeError, ValueError) as exc:
        raise ETradeError("Invalid option expiration date.") from exc


def _normalized_iv(raw: Any) -> float | None:
    iv = _number(raw)
    if iv is None or iv <= 0:
        return None
    if iv > 5.0:
        iv /= 100.0
    return iv if 0.0 < iv < 5.0 else None


def _greeks(spot: float, strike: float, iv_raw: Any, expiry: date) -> dict[str, float]:
    iv = _normalized_iv(iv_raw)
    if iv is None or spot <= 0 or strike <= 0:
        return {}
    today = datetime.now(_MARKET_TZ).date()
    dte = max(0, (expiry - today).days)
    years = max(dte / 365.0, 1.0 / 365.0)
    sqrt_t = math.sqrt(years)
    denominator = iv * sqrt_t
    if denominator <= 0:
        return {"iv": iv}
    d1 = (math.log(spot / strike) + 0.5 * iv * iv * years) / denominator
    density = math.exp(-0.5 * d1 * d1) / math.sqrt(2.0 * math.pi)
    gamma = density / (spot * denominator)
    vega = spot * density * sqrt_t * 0.01
    return {
        "iv": float(iv),
        "gamma": float(gamma),
        "vega": float(vega),
    }


def _option_record(row: Any, *, spot: float, expiry: date) -> dict[str, Any] | None:
    strike = _number(row.get("strike"))
    if strike is None or strike <= 0:
        return None
    record = {
        "strikePrice": float(strike),
        "bid": _number(row.get("bid")),
        "ask": _number(row.get("ask")),
        "lastPrice": _number(row.get("lastPrice")),
        "volume": _number(row.get("volume")),
        "openInterest": _number(row.get("openInterest")),
        "osiKey": str(row.get("contractSymbol") or ""),
        "displaySymbol": str(row.get("contractSymbol") or ""),
        "OptionGreeks": _greeks(
            float(spot),
            float(strike),
            row.get("impliedVolatility"),
            expiry,
        ),
    }
    return record


def _frame_rows(frame: pd.DataFrame, *, spot: float, expiry: date) -> dict[float, dict[str, Any]]:
    rows: dict[float, dict[str, Any]] = {}
    if frame is None or frame.empty:
        return rows
    for _, raw in frame.iterrows():
        record = _option_record(raw, spot=spot, expiry=expiry)
        if record is not None:
            rows[float(record["strikePrice"])] = record
    return rows


class YFinanceOptionsClient:
    """Read-only E*TRADE-style market client backed by yfinance."""

    is_offline = True
    is_yfinance_options_fallback = True
    options_source = _SOURCE

    def __init__(self, base_client: Any | None = None) -> None:
        self._base_client = base_client

    def get_quote(self, symbol: str, force_refresh: bool = False) -> dict[str, Any]:
        del force_refresh
        symbol = str(symbol or "").strip().upper()
        if not symbol:
            raise ETradeError("Ticker is required.")
        ticker = yf.Ticker(symbol)
        last, bid, ask, name = _ticker_quote(ticker, symbol)
        return {
            "quoteData": [
                {
                    "symbol": symbol,
                    "companyName": name,
                    "lastTrade": last,
                    "bid": bid,
                    "ask": ask,
                    "source": _SOURCE,
                }
            ]
        }

    def get_option_expirations(
        self,
        symbol: str,
        force_refresh: bool = False,
    ) -> dict[str, Any]:
        del force_refresh
        symbol = str(symbol or "").strip().upper()
        if not symbol:
            raise ETradeError("Ticker is required.")
        values = list(yf.Ticker(symbol).options or [])
        dates: list[date] = []
        for value in values:
            try:
                dates.append(datetime.strptime(str(value), "%Y-%m-%d").date())
            except ValueError:
                continue
        dates = sorted(set(dates))
        if not dates:
            raise ETradeError(f"yfinance returned no option expirations for {symbol}.")
        return {
            "OptionExpireDateResponse": {
                "ExpirationDate": [
                    {
                        "year": item.year,
                        "month": item.month,
                        "day": item.day,
                        "expiryType": _SOURCE,
                    }
                    for item in dates
                ]
            },
            "_source": _SOURCE,
        }

    def get_option_chain(
        self,
        symbol: str,
        expiry_year: int,
        expiry_month: int,
        expiry_day: int,
        no_of_strikes: int | None = 100,
        chain_type: str = "CALLPUT",
        force_refresh: bool = False,
    ) -> dict[str, Any]:
        del force_refresh
        symbol = str(symbol or "").strip().upper()
        chain_type = str(chain_type or "CALLPUT").strip().upper()
        if chain_type not in {"CALL", "PUT", "CALLPUT"}:
            raise ETradeError(f"Unsupported option chain type: {chain_type}")
        expiry = _expiration_date(expiry_year, expiry_month, expiry_day)
        ticker = yf.Ticker(symbol)
        last, _, _, _ = _ticker_quote(ticker, symbol)
        try:
            chain = ticker.option_chain(expiry.isoformat())
        except Exception as exc:
            raise ETradeError(
                f"yfinance option chain unavailable for {symbol} {expiry.isoformat()}: {exc}"
            ) from exc

        calls = _frame_rows(chain.calls, spot=last, expiry=expiry)
        puts = _frame_rows(chain.puts, spot=last, expiry=expiry)
        strikes = sorted(set(calls) | set(puts))
        if no_of_strikes is not None:
            limit = max(1, int(no_of_strikes))
            strikes = sorted(
                sorted(strikes, key=lambda strike: abs(float(strike) - float(last)))[:limit]
            )

        pairs: list[dict[str, Any]] = []
        for strike in strikes:
            pair: dict[str, Any] = {}
            if chain_type in {"CALL", "CALLPUT"} and strike in calls:
                pair["Call"] = calls[strike]
            if chain_type in {"PUT", "CALLPUT"} and strike in puts:
                pair["Put"] = puts[strike]
            if pair:
                pairs.append(pair)

        if not pairs:
            raise ETradeError(
                f"yfinance returned no usable {chain_type} contracts for "
                f"{symbol} {expiry.isoformat()}."
            )
        return {
            "OptionChainResponse": {
                "OptionPair": pairs,
                "symbol": symbol,
                "expiryYear": expiry.year,
                "expiryMonth": expiry.month,
                "expiryDay": expiry.day,
            },
            "_source": _SOURCE,
        }

    def list_accounts(self, force_refresh: bool = False) -> list[dict[str, Any]]:
        if self._base_client is None:
            return []
        try:
            return list(self._base_client.list_accounts(force_refresh=force_refresh))
        except TypeError:
            return list(self._base_client.list_accounts())
        except Exception:
            return []

    def __getattr__(self, name: str) -> Any:
        if self._base_client is not None:
            return getattr(self._base_client, name)
        raise AttributeError(name)


def options_market_client(client: Any | None) -> Any:
    """Return E*TRADE when live; otherwise return yfinance options fallback."""
    if client is not None and not bool(getattr(client, "is_offline", False)):
        return client
    if bool(getattr(client, "is_yfinance_options_fallback", False)):
        return client
    return YFinanceOptionsClient(client)


__all__ = ["YFinanceOptionsClient", "options_market_client"]
